class CookerExecutor {

    public static void main(String[] args) {

        Cooker cooker1 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker1.cookerBrand);
        System.out.println("The cookerId is : " + cooker1.cookerId);
        System.out.println("The cookerPrice is : " + cooker1.cookerPrice);
        System.out.println("The isAvailable is : " + cooker1.isAvailable);
        System.out.println("The cookerType is : " + cooker1.cookerType);
        System.out.println("The capacity is : " + cooker1.capacity);
        System.out.println("The weight is : " + cooker1.weight);
        System.out.println("The isInductionCompatible is : " + cooker1.isInductionCompatible);
        System.out.println("The material is : " + cooker1.material);
        System.out.println("The warrantyYears is : " + cooker1.warrantyYears);
        System.out.println("The diameter is : " + cooker1.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker1.isDishwasherSafe);
        System.out.println("The color is : " + cooker1.color);
        System.out.println("The stockQuantity is : " + cooker1.stockQuantity);
        System.out.println("The thickness is : " + cooker1.thickness);
        System.out.println("The isEcoFriendly is : " + cooker1.isEcoFriendly);
        System.out.println("The lidType is : " + cooker1.lidType);
        System.out.println("The rating is : " + cooker1.rating);
        System.out.println("The pressureLevel is : " + cooker1.pressureLevel);
        System.out.println("The isCertified is : " + cooker1.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker1.manufacturingYear);
        System.out.println("The handleLength is : " + cooker1.handleLength);
        System.out.println("The isNonStick is : " + cooker1.isNonStick);
        System.out.println("The certificationType is : " + cooker1.certificationType);

        cooker1.cookerBrand = "Brand1";
        cooker1.cookerId = 1;
        cooker1.cookerPrice = 10.5;
        cooker1.isAvailable = true;
        cooker1.cookerType = "Pressure";
        cooker1.capacity = 5;
        cooker1.weight = 2.5;
        cooker1.isInductionCompatible = true;
        cooker1.material = "Aluminium";
        cooker1.warrantyYears = 5;
        cooker1.diameter = 22.5;
        cooker1.isDishwasherSafe = false;
        cooker1.color = "Silver";
        cooker1.stockQuantity = 50;
        cooker1.thickness = 0.8;
        cooker1.isEcoFriendly = true;
        cooker1.lidType = "Inner Lid";
        cooker1.rating = 5;
        cooker1.pressureLevel = 15.0;
        cooker1.isCertified = true;
        cooker1.countryOfOrigin = "India";
        cooker1.manufacturingYear = 2025;
        cooker1.handleLength = 12.0;
        cooker1.isNonStick = false;
        cooker1.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker1.cookerBrand);
        System.out.println("The cookerId is : " + cooker1.cookerId);
        System.out.println("The cookerPrice is : " + cooker1.cookerPrice);
        System.out.println("The isAvailable is : " + cooker1.isAvailable);
        System.out.println("The cookerType is : " + cooker1.cookerType);
        System.out.println("The capacity is : " + cooker1.capacity);
        System.out.println("The weight is : " + cooker1.weight);
        System.out.println("The isInductionCompatible is : " + cooker1.isInductionCompatible);
        System.out.println("The material is : " + cooker1.material);
        System.out.println("The warrantyYears is : " + cooker1.warrantyYears);
        System.out.println("The diameter is : " + cooker1.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker1.isDishwasherSafe);
        System.out.println("The color is : " + cooker1.color);
        System.out.println("The stockQuantity is : " + cooker1.stockQuantity);
        System.out.println("The thickness is : " + cooker1.thickness);
        System.out.println("The isEcoFriendly is : " + cooker1.isEcoFriendly);
        System.out.println("The lidType is : " + cooker1.lidType);
        System.out.println("The rating is : " + cooker1.rating);
        System.out.println("The pressureLevel is : " + cooker1.pressureLevel);
        System.out.println("The isCertified is : " + cooker1.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker1.manufacturingYear);
        System.out.println("The handleLength is : " + cooker1.handleLength);
        System.out.println("The isNonStick is : " + cooker1.isNonStick);
        System.out.println("The certificationType is : " + cooker1.certificationType);


        Cooker cooker2 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker2.cookerBrand);
        System.out.println("The cookerId is : " + cooker2.cookerId);
        System.out.println("The cookerPrice is : " + cooker2.cookerPrice);
        System.out.println("The isAvailable is : " + cooker2.isAvailable);
        System.out.println("The cookerType is : " + cooker2.cookerType);
        System.out.println("The capacity is : " + cooker2.capacity);
        System.out.println("The weight is : " + cooker2.weight);
        System.out.println("The isInductionCompatible is : " + cooker2.isInductionCompatible);
        System.out.println("The material is : " + cooker2.material);
        System.out.println("The warrantyYears is : " + cooker2.warrantyYears);
        System.out.println("The diameter is : " + cooker2.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker2.isDishwasherSafe);
        System.out.println("The color is : " + cooker2.color);
        System.out.println("The stockQuantity is : " + cooker2.stockQuantity);
        System.out.println("The thickness is : " + cooker2.thickness);
        System.out.println("The isEcoFriendly is : " + cooker2.isEcoFriendly);
        System.out.println("The lidType is : " + cooker2.lidType);
        System.out.println("The rating is : " + cooker2.rating);
        System.out.println("The pressureLevel is : " + cooker2.pressureLevel);
        System.out.println("The isCertified is : " + cooker2.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker2.manufacturingYear);
        System.out.println("The handleLength is : " + cooker2.handleLength);
        System.out.println("The isNonStick is : " + cooker2.isNonStick);
        System.out.println("The certificationType is : " + cooker2.certificationType);

        cooker2.cookerBrand = "Brand2";
        cooker2.cookerId = 2;
        cooker2.cookerPrice = 20.5;
        cooker2.isAvailable = true;
        cooker2.cookerType = "Pressure";
        cooker2.capacity = 5;
        cooker2.weight = 2.5;
        cooker2.isInductionCompatible = true;
        cooker2.material = "Aluminium";
        cooker2.warrantyYears = 5;
        cooker2.diameter = 22.5;
        cooker2.isDishwasherSafe = false;
        cooker2.color = "Silver";
        cooker2.stockQuantity = 50;
        cooker2.thickness = 0.8;
        cooker2.isEcoFriendly = true;
        cooker2.lidType = "Inner Lid";
        cooker2.rating = 5;
        cooker2.pressureLevel = 15.0;
        cooker2.isCertified = true;
        cooker2.countryOfOrigin = "India";
        cooker2.manufacturingYear = 2025;
        cooker2.handleLength = 12.0;
        cooker2.isNonStick = false;
        cooker2.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker2.cookerBrand);
        System.out.println("The cookerId is : " + cooker2.cookerId);
        System.out.println("The cookerPrice is : " + cooker2.cookerPrice);
        System.out.println("The isAvailable is : " + cooker2.isAvailable);
        System.out.println("The cookerType is : " + cooker2.cookerType);
        System.out.println("The capacity is : " + cooker2.capacity);
        System.out.println("The weight is : " + cooker2.weight);
        System.out.println("The isInductionCompatible is : " + cooker2.isInductionCompatible);
        System.out.println("The material is : " + cooker2.material);
        System.out.println("The warrantyYears is : " + cooker2.warrantyYears);
        System.out.println("The diameter is : " + cooker2.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker2.isDishwasherSafe);
        System.out.println("The color is : " + cooker2.color);
        System.out.println("The stockQuantity is : " + cooker2.stockQuantity);
        System.out.println("The thickness is : " + cooker2.thickness);
        System.out.println("The isEcoFriendly is : " + cooker2.isEcoFriendly);
        System.out.println("The lidType is : " + cooker2.lidType);
        System.out.println("The rating is : " + cooker2.rating);
        System.out.println("The pressureLevel is : " + cooker2.pressureLevel);
        System.out.println("The isCertified is : " + cooker2.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker2.manufacturingYear);
        System.out.println("The handleLength is : " + cooker2.handleLength);
        System.out.println("The isNonStick is : " + cooker2.isNonStick);
        System.out.println("The certificationType is : " + cooker2.certificationType);


        Cooker cooker3 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker3.cookerBrand);
        System.out.println("The cookerId is : " + cooker3.cookerId);
        System.out.println("The cookerPrice is : " + cooker3.cookerPrice);
        System.out.println("The isAvailable is : " + cooker3.isAvailable);
        System.out.println("The cookerType is : " + cooker3.cookerType);
        System.out.println("The capacity is : " + cooker3.capacity);
        System.out.println("The weight is : " + cooker3.weight);
        System.out.println("The isInductionCompatible is : " + cooker3.isInductionCompatible);
        System.out.println("The material is : " + cooker3.material);
        System.out.println("The warrantyYears is : " + cooker3.warrantyYears);
        System.out.println("The diameter is : " + cooker3.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker3.isDishwasherSafe);
        System.out.println("The color is : " + cooker3.color);
        System.out.println("The stockQuantity is : " + cooker3.stockQuantity);
        System.out.println("The thickness is : " + cooker3.thickness);
        System.out.println("The isEcoFriendly is : " + cooker3.isEcoFriendly);
        System.out.println("The lidType is : " + cooker3.lidType);
        System.out.println("The rating is : " + cooker3.rating);
        System.out.println("The pressureLevel is : " + cooker3.pressureLevel);
        System.out.println("The isCertified is : " + cooker3.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker3.manufacturingYear);
        System.out.println("The handleLength is : " + cooker3.handleLength);
        System.out.println("The isNonStick is : " + cooker3.isNonStick);
        System.out.println("The certificationType is : " + cooker3.certificationType);

        cooker3.cookerBrand = "Brand3";
        cooker3.cookerId = 3;
        cooker3.cookerPrice = 30.5;
        cooker3.isAvailable = true;
        cooker3.cookerType = "Pressure";
        cooker3.capacity = 5;
        cooker3.weight = 2.5;
        cooker3.isInductionCompatible = true;
        cooker3.material = "Aluminium";
        cooker3.warrantyYears = 5;
        cooker3.diameter = 22.5;
        cooker3.isDishwasherSafe = false;
        cooker3.color = "Silver";
        cooker3.stockQuantity = 50;
        cooker3.thickness = 0.8;
        cooker3.isEcoFriendly = true;
        cooker3.lidType = "Inner Lid";
        cooker3.rating = 5;
        cooker3.pressureLevel = 15.0;
        cooker3.isCertified = true;
        cooker3.countryOfOrigin = "India";
        cooker3.manufacturingYear = 2025;
        cooker3.handleLength = 12.0;
        cooker3.isNonStick = false;
        cooker3.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker3.cookerBrand);
        System.out.println("The cookerId is : " + cooker3.cookerId);
        System.out.println("The cookerPrice is : " + cooker3.cookerPrice);
        System.out.println("The isAvailable is : " + cooker3.isAvailable);
        System.out.println("The cookerType is : " + cooker3.cookerType);
        System.out.println("The capacity is : " + cooker3.capacity);
        System.out.println("The weight is : " + cooker3.weight);
        System.out.println("The isInductionCompatible is : " + cooker3.isInductionCompatible);
        System.out.println("The material is : " + cooker3.material);
        System.out.println("The warrantyYears is : " + cooker3.warrantyYears);
        System.out.println("The diameter is : " + cooker3.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker3.isDishwasherSafe);
        System.out.println("The color is : " + cooker3.color);
        System.out.println("The stockQuantity is : " + cooker3.stockQuantity);
        System.out.println("The thickness is : " + cooker3.thickness);
        System.out.println("The isEcoFriendly is : " + cooker3.isEcoFriendly);
        System.out.println("The lidType is : " + cooker3.lidType);
        System.out.println("The rating is : " + cooker3.rating);
        System.out.println("The pressureLevel is : " + cooker3.pressureLevel);
        System.out.println("The isCertified is : " + cooker3.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker3.manufacturingYear);
        System.out.println("The handleLength is : " + cooker3.handleLength);
        System.out.println("The isNonStick is : " + cooker3.isNonStick);
        System.out.println("The certificationType is : " + cooker3.certificationType);


        Cooker cooker4 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker4.cookerBrand);
        System.out.println("The cookerId is : " + cooker4.cookerId);
        System.out.println("The cookerPrice is : " + cooker4.cookerPrice);
        System.out.println("The isAvailable is : " + cooker4.isAvailable);
        System.out.println("The cookerType is : " + cooker4.cookerType);
        System.out.println("The capacity is : " + cooker4.capacity);
        System.out.println("The weight is : " + cooker4.weight);
        System.out.println("The isInductionCompatible is : " + cooker4.isInductionCompatible);
        System.out.println("The material is : " + cooker4.material);
        System.out.println("The warrantyYears is : " + cooker4.warrantyYears);
        System.out.println("The diameter is : " + cooker4.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker4.isDishwasherSafe);
        System.out.println("The color is : " + cooker4.color);
        System.out.println("The stockQuantity is : " + cooker4.stockQuantity);
        System.out.println("The thickness is : " + cooker4.thickness);
        System.out.println("The isEcoFriendly is : " + cooker4.isEcoFriendly);
        System.out.println("The lidType is : " + cooker4.lidType);
        System.out.println("The rating is : " + cooker4.rating);
        System.out.println("The pressureLevel is : " + cooker4.pressureLevel);
        System.out.println("The isCertified is : " + cooker4.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker4.manufacturingYear);
        System.out.println("The handleLength is : " + cooker4.handleLength);
        System.out.println("The isNonStick is : " + cooker4.isNonStick);
        System.out.println("The certificationType is : " + cooker4.certificationType);

        cooker4.cookerBrand = "Brand4";
        cooker4.cookerId = 4;
        cooker4.cookerPrice = 40.5;
        cooker4.isAvailable = true;
        cooker4.cookerType = "Pressure";
        cooker4.capacity = 5;
        cooker4.weight = 2.5;
        cooker4.isInductionCompatible = true;
        cooker4.material = "Aluminium";
        cooker4.warrantyYears = 5;
        cooker4.diameter = 22.5;
        cooker4.isDishwasherSafe = false;
        cooker4.color = "Silver";
        cooker4.stockQuantity = 50;
        cooker4.thickness = 0.8;
        cooker4.isEcoFriendly = true;
        cooker4.lidType = "Inner Lid";
        cooker4.rating = 5;
        cooker4.pressureLevel = 15.0;
        cooker4.isCertified = true;
        cooker4.countryOfOrigin = "India";
        cooker4.manufacturingYear = 2025;
        cooker4.handleLength = 12.0;
        cooker4.isNonStick = false;
        cooker4.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker4.cookerBrand);
        System.out.println("The cookerId is : " + cooker4.cookerId);
        System.out.println("The cookerPrice is : " + cooker4.cookerPrice);
        System.out.println("The isAvailable is : " + cooker4.isAvailable);
        System.out.println("The cookerType is : " + cooker4.cookerType);
        System.out.println("The capacity is : " + cooker4.capacity);
        System.out.println("The weight is : " + cooker4.weight);
        System.out.println("The isInductionCompatible is : " + cooker4.isInductionCompatible);
        System.out.println("The material is : " + cooker4.material);
        System.out.println("The warrantyYears is : " + cooker4.warrantyYears);
        System.out.println("The diameter is : " + cooker4.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker4.isDishwasherSafe);
        System.out.println("The color is : " + cooker4.color);
        System.out.println("The stockQuantity is : " + cooker4.stockQuantity);
        System.out.println("The thickness is : " + cooker4.thickness);
        System.out.println("The isEcoFriendly is : " + cooker4.isEcoFriendly);
        System.out.println("The lidType is : " + cooker4.lidType);
        System.out.println("The rating is : " + cooker4.rating);
        System.out.println("The pressureLevel is : " + cooker4.pressureLevel);
        System.out.println("The isCertified is : " + cooker4.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker4.manufacturingYear);
        System.out.println("The handleLength is : " + cooker4.handleLength);
        System.out.println("The isNonStick is : " + cooker4.isNonStick);
        System.out.println("The certificationType is : " + cooker4.certificationType);


        Cooker cooker5 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker5.cookerBrand);
        System.out.println("The cookerId is : " + cooker5.cookerId);
        System.out.println("The cookerPrice is : " + cooker5.cookerPrice);
        System.out.println("The isAvailable is : " + cooker5.isAvailable);
        System.out.println("The cookerType is : " + cooker5.cookerType);
        System.out.println("The capacity is : " + cooker5.capacity);
        System.out.println("The weight is : " + cooker5.weight);
        System.out.println("The isInductionCompatible is : " + cooker5.isInductionCompatible);
        System.out.println("The material is : " + cooker5.material);
        System.out.println("The warrantyYears is : " + cooker5.warrantyYears);
        System.out.println("The diameter is : " + cooker5.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker5.isDishwasherSafe);
        System.out.println("The color is : " + cooker5.color);
        System.out.println("The stockQuantity is : " + cooker5.stockQuantity);
        System.out.println("The thickness is : " + cooker5.thickness);
        System.out.println("The isEcoFriendly is : " + cooker5.isEcoFriendly);
        System.out.println("The lidType is : " + cooker5.lidType);
        System.out.println("The rating is : " + cooker5.rating);
        System.out.println("The pressureLevel is : " + cooker5.pressureLevel);
        System.out.println("The isCertified is : " + cooker5.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker5.manufacturingYear);
        System.out.println("The handleLength is : " + cooker5.handleLength);
        System.out.println("The isNonStick is : " + cooker5.isNonStick);
        System.out.println("The certificationType is : " + cooker5.certificationType);

        cooker5.cookerBrand = "Brand5";
        cooker5.cookerId = 5;
        cooker5.cookerPrice = 50.5;
        cooker5.isAvailable = true;
        cooker5.cookerType = "Pressure";
        cooker5.capacity = 5;
        cooker5.weight = 2.5;
        cooker5.isInductionCompatible = true;
        cooker5.material = "Aluminium";
        cooker5.warrantyYears = 5;
        cooker5.diameter = 22.5;
        cooker5.isDishwasherSafe = false;
        cooker5.color = "Silver";
        cooker5.stockQuantity = 50;
        cooker5.thickness = 0.8;
        cooker5.isEcoFriendly = true;
        cooker5.lidType = "Inner Lid";
        cooker5.rating = 5;
        cooker5.pressureLevel = 15.0;
        cooker5.isCertified = true;
        cooker5.countryOfOrigin = "India";
        cooker5.manufacturingYear = 2025;
        cooker5.handleLength = 12.0;
        cooker5.isNonStick = false;
        cooker5.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker5.cookerBrand);
        System.out.println("The cookerId is : " + cooker5.cookerId);
        System.out.println("The cookerPrice is : " + cooker5.cookerPrice);
        System.out.println("The isAvailable is : " + cooker5.isAvailable);
        System.out.println("The cookerType is : " + cooker5.cookerType);
        System.out.println("The capacity is : " + cooker5.capacity);
        System.out.println("The weight is : " + cooker5.weight);
        System.out.println("The isInductionCompatible is : " + cooker5.isInductionCompatible);
        System.out.println("The material is : " + cooker5.material);
        System.out.println("The warrantyYears is : " + cooker5.warrantyYears);
        System.out.println("The diameter is : " + cooker5.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker5.isDishwasherSafe);
        System.out.println("The color is : " + cooker5.color);
        System.out.println("The stockQuantity is : " + cooker5.stockQuantity);
        System.out.println("The thickness is : " + cooker5.thickness);
        System.out.println("The isEcoFriendly is : " + cooker5.isEcoFriendly);
        System.out.println("The lidType is : " + cooker5.lidType);
        System.out.println("The rating is : " + cooker5.rating);
        System.out.println("The pressureLevel is : " + cooker5.pressureLevel);
        System.out.println("The isCertified is : " + cooker5.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker5.manufacturingYear);
        System.out.println("The handleLength is : " + cooker5.handleLength);
        System.out.println("The isNonStick is : " + cooker5.isNonStick);
        System.out.println("The certificationType is : " + cooker5.certificationType);


        Cooker cooker6 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker6.cookerBrand);
        System.out.println("The cookerId is : " + cooker6.cookerId);
        System.out.println("The cookerPrice is : " + cooker6.cookerPrice);
        System.out.println("The isAvailable is : " + cooker6.isAvailable);
        System.out.println("The cookerType is : " + cooker6.cookerType);
        System.out.println("The capacity is : " + cooker6.capacity);
        System.out.println("The weight is : " + cooker6.weight);
        System.out.println("The isInductionCompatible is : " + cooker6.isInductionCompatible);
        System.out.println("The material is : " + cooker6.material);
        System.out.println("The warrantyYears is : " + cooker6.warrantyYears);
        System.out.println("The diameter is : " + cooker6.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker6.isDishwasherSafe);
        System.out.println("The color is : " + cooker6.color);
        System.out.println("The stockQuantity is : " + cooker6.stockQuantity);
        System.out.println("The thickness is : " + cooker6.thickness);
        System.out.println("The isEcoFriendly is : " + cooker6.isEcoFriendly);
        System.out.println("The lidType is : " + cooker6.lidType);
        System.out.println("The rating is : " + cooker6.rating);
        System.out.println("The pressureLevel is : " + cooker6.pressureLevel);
        System.out.println("The isCertified is : " + cooker6.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker6.manufacturingYear);
        System.out.println("The handleLength is : " + cooker6.handleLength);
        System.out.println("The isNonStick is : " + cooker6.isNonStick);
        System.out.println("The certificationType is : " + cooker6.certificationType);

        cooker6.cookerBrand = "Brand6";
        cooker6.cookerId = 6;
        cooker6.cookerPrice = 60.5;
        cooker6.isAvailable = true;
        cooker6.cookerType = "Pressure";
        cooker6.capacity = 5;
        cooker6.weight = 2.5;
        cooker6.isInductionCompatible = true;
        cooker6.material = "Aluminium";
        cooker6.warrantyYears = 5;
        cooker6.diameter = 22.5;
        cooker6.isDishwasherSafe = false;
        cooker6.color = "Silver";
        cooker6.stockQuantity = 50;
        cooker6.thickness = 0.8;
        cooker6.isEcoFriendly = true;
        cooker6.lidType = "Inner Lid";
        cooker6.rating = 5;
        cooker6.pressureLevel = 15.0;
        cooker6.isCertified = true;
        cooker6.countryOfOrigin = "India";
        cooker6.manufacturingYear = 2025;
        cooker6.handleLength = 12.0;
        cooker6.isNonStick = false;
        cooker6.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker6.cookerBrand);
        System.out.println("The cookerId is : " + cooker6.cookerId);
        System.out.println("The cookerPrice is : " + cooker6.cookerPrice);
        System.out.println("The isAvailable is : " + cooker6.isAvailable);
        System.out.println("The cookerType is : " + cooker6.cookerType);
        System.out.println("The capacity is : " + cooker6.capacity);
        System.out.println("The weight is : " + cooker6.weight);
        System.out.println("The isInductionCompatible is : " + cooker6.isInductionCompatible);
        System.out.println("The material is : " + cooker6.material);
        System.out.println("The warrantyYears is : " + cooker6.warrantyYears);
        System.out.println("The diameter is : " + cooker6.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker6.isDishwasherSafe);
        System.out.println("The color is : " + cooker6.color);
        System.out.println("The stockQuantity is : " + cooker6.stockQuantity);
        System.out.println("The thickness is : " + cooker6.thickness);
        System.out.println("The isEcoFriendly is : " + cooker6.isEcoFriendly);
        System.out.println("The lidType is : " + cooker6.lidType);
        System.out.println("The rating is : " + cooker6.rating);
        System.out.println("The pressureLevel is : " + cooker6.pressureLevel);
        System.out.println("The isCertified is : " + cooker6.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker6.manufacturingYear);
        System.out.println("The handleLength is : " + cooker6.handleLength);
        System.out.println("The isNonStick is : " + cooker6.isNonStick);
        System.out.println("The certificationType is : " + cooker6.certificationType);


        Cooker cooker7 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker7.cookerBrand);
        System.out.println("The cookerId is : " + cooker7.cookerId);
        System.out.println("The cookerPrice is : " + cooker7.cookerPrice);
        System.out.println("The isAvailable is : " + cooker7.isAvailable);
        System.out.println("The cookerType is : " + cooker7.cookerType);
        System.out.println("The capacity is : " + cooker7.capacity);
        System.out.println("The weight is : " + cooker7.weight);
        System.out.println("The isInductionCompatible is : " + cooker7.isInductionCompatible);
        System.out.println("The material is : " + cooker7.material);
        System.out.println("The warrantyYears is : " + cooker7.warrantyYears);
        System.out.println("The diameter is : " + cooker7.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker7.isDishwasherSafe);
        System.out.println("The color is : " + cooker7.color);
        System.out.println("The stockQuantity is : " + cooker7.stockQuantity);
        System.out.println("The thickness is : " + cooker7.thickness);
        System.out.println("The isEcoFriendly is : " + cooker7.isEcoFriendly);
        System.out.println("The lidType is : " + cooker7.lidType);
        System.out.println("The rating is : " + cooker7.rating);
        System.out.println("The pressureLevel is : " + cooker7.pressureLevel);
        System.out.println("The isCertified is : " + cooker7.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker7.manufacturingYear);
        System.out.println("The handleLength is : " + cooker7.handleLength);
        System.out.println("The isNonStick is : " + cooker7.isNonStick);
        System.out.println("The certificationType is : " + cooker7.certificationType);

        cooker7.cookerBrand = "Brand7";
        cooker7.cookerId = 7;
        cooker7.cookerPrice = 70.5;
        cooker7.isAvailable = true;
        cooker7.cookerType = "Pressure";
        cooker7.capacity = 5;
        cooker7.weight = 2.5;
        cooker7.isInductionCompatible = true;
        cooker7.material = "Aluminium";
        cooker7.warrantyYears = 5;
        cooker7.diameter = 22.5;
        cooker7.isDishwasherSafe = false;
        cooker7.color = "Silver";
        cooker7.stockQuantity = 50;
        cooker7.thickness = 0.8;
        cooker7.isEcoFriendly = true;
        cooker7.lidType = "Inner Lid";
        cooker7.rating = 5;
        cooker7.pressureLevel = 15.0;
        cooker7.isCertified = true;
        cooker7.countryOfOrigin = "India";
        cooker7.manufacturingYear = 2025;
        cooker7.handleLength = 12.0;
        cooker7.isNonStick = false;
        cooker7.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker7.cookerBrand);
        System.out.println("The cookerId is : " + cooker7.cookerId);
        System.out.println("The cookerPrice is : " + cooker7.cookerPrice);
        System.out.println("The isAvailable is : " + cooker7.isAvailable);
        System.out.println("The cookerType is : " + cooker7.cookerType);
        System.out.println("The capacity is : " + cooker7.capacity);
        System.out.println("The weight is : " + cooker7.weight);
        System.out.println("The isInductionCompatible is : " + cooker7.isInductionCompatible);
        System.out.println("The material is : " + cooker7.material);
        System.out.println("The warrantyYears is : " + cooker7.warrantyYears);
        System.out.println("The diameter is : " + cooker7.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker7.isDishwasherSafe);
        System.out.println("The color is : " + cooker7.color);
        System.out.println("The stockQuantity is : " + cooker7.stockQuantity);
        System.out.println("The thickness is : " + cooker7.thickness);
        System.out.println("The isEcoFriendly is : " + cooker7.isEcoFriendly);
        System.out.println("The lidType is : " + cooker7.lidType);
        System.out.println("The rating is : " + cooker7.rating);
        System.out.println("The pressureLevel is : " + cooker7.pressureLevel);
        System.out.println("The isCertified is : " + cooker7.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker7.manufacturingYear);
        System.out.println("The handleLength is : " + cooker7.handleLength);
        System.out.println("The isNonStick is : " + cooker7.isNonStick);
        System.out.println("The certificationType is : " + cooker7.certificationType);


        Cooker cooker8 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker8.cookerBrand);
        System.out.println("The cookerId is : " + cooker8.cookerId);
        System.out.println("The cookerPrice is : " + cooker8.cookerPrice);
        System.out.println("The isAvailable is : " + cooker8.isAvailable);
        System.out.println("The cookerType is : " + cooker8.cookerType);
        System.out.println("The capacity is : " + cooker8.capacity);
        System.out.println("The weight is : " + cooker8.weight);
        System.out.println("The isInductionCompatible is : " + cooker8.isInductionCompatible);
        System.out.println("The material is : " + cooker8.material);
        System.out.println("The warrantyYears is : " + cooker8.warrantyYears);
        System.out.println("The diameter is : " + cooker8.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker8.isDishwasherSafe);
        System.out.println("The color is : " + cooker8.color);
        System.out.println("The stockQuantity is : " + cooker8.stockQuantity);
        System.out.println("The thickness is : " + cooker8.thickness);
        System.out.println("The isEcoFriendly is : " + cooker8.isEcoFriendly);
        System.out.println("The lidType is : " + cooker8.lidType);
        System.out.println("The rating is : " + cooker8.rating);
        System.out.println("The pressureLevel is : " + cooker8.pressureLevel);
        System.out.println("The isCertified is : " + cooker8.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker8.manufacturingYear);
        System.out.println("The handleLength is : " + cooker8.handleLength);
        System.out.println("The isNonStick is : " + cooker8.isNonStick);
        System.out.println("The certificationType is : " + cooker8.certificationType);

        cooker8.cookerBrand = "Brand8";
        cooker8.cookerId = 8;
        cooker8.cookerPrice = 80.5;
        cooker8.isAvailable = true;
        cooker8.cookerType = "Pressure";
        cooker8.capacity = 5;
        cooker8.weight = 2.5;
        cooker8.isInductionCompatible = true;
        cooker8.material = "Aluminium";
        cooker8.warrantyYears = 5;
        cooker8.diameter = 22.5;
        cooker8.isDishwasherSafe = false;
        cooker8.color = "Silver";
        cooker8.stockQuantity = 50;
        cooker8.thickness = 0.8;
        cooker8.isEcoFriendly = true;
        cooker8.lidType = "Inner Lid";
        cooker8.rating = 5;
        cooker8.pressureLevel = 15.0;
        cooker8.isCertified = true;
        cooker8.countryOfOrigin = "India";
        cooker8.manufacturingYear = 2025;
        cooker8.handleLength = 12.0;
        cooker8.isNonStick = false;
        cooker8.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker8.cookerBrand);
        System.out.println("The cookerId is : " + cooker8.cookerId);
        System.out.println("The cookerPrice is : " + cooker8.cookerPrice);
        System.out.println("The isAvailable is : " + cooker8.isAvailable);
        System.out.println("The cookerType is : " + cooker8.cookerType);
        System.out.println("The capacity is : " + cooker8.capacity);
        System.out.println("The weight is : " + cooker8.weight);
        System.out.println("The isInductionCompatible is : " + cooker8.isInductionCompatible);
        System.out.println("The material is : " + cooker8.material);
        System.out.println("The warrantyYears is : " + cooker8.warrantyYears);
        System.out.println("The diameter is : " + cooker8.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker8.isDishwasherSafe);
        System.out.println("The color is : " + cooker8.color);
        System.out.println("The stockQuantity is : " + cooker8.stockQuantity);
        System.out.println("The thickness is : " + cooker8.thickness);
        System.out.println("The isEcoFriendly is : " + cooker8.isEcoFriendly);
        System.out.println("The lidType is : " + cooker8.lidType);
        System.out.println("The rating is : " + cooker8.rating);
        System.out.println("The pressureLevel is : " + cooker8.pressureLevel);
        System.out.println("The isCertified is : " + cooker8.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker8.manufacturingYear);
        System.out.println("The handleLength is : " + cooker8.handleLength);
        System.out.println("The isNonStick is : " + cooker8.isNonStick);
        System.out.println("The certificationType is : " + cooker8.certificationType);


        Cooker cooker9 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker9.cookerBrand);
        System.out.println("The cookerId is : " + cooker9.cookerId);
        System.out.println("The cookerPrice is : " + cooker9.cookerPrice);
        System.out.println("The isAvailable is : " + cooker9.isAvailable);
        System.out.println("The cookerType is : " + cooker9.cookerType);
        System.out.println("The capacity is : " + cooker9.capacity);
        System.out.println("The weight is : " + cooker9.weight);
        System.out.println("The isInductionCompatible is : " + cooker9.isInductionCompatible);
        System.out.println("The material is : " + cooker9.material);
        System.out.println("The warrantyYears is : " + cooker9.warrantyYears);
        System.out.println("The diameter is : " + cooker9.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker9.isDishwasherSafe);
        System.out.println("The color is : " + cooker9.color);
        System.out.println("The stockQuantity is : " + cooker9.stockQuantity);
        System.out.println("The thickness is : " + cooker9.thickness);
        System.out.println("The isEcoFriendly is : " + cooker9.isEcoFriendly);
        System.out.println("The lidType is : " + cooker9.lidType);
        System.out.println("The rating is : " + cooker9.rating);
        System.out.println("The pressureLevel is : " + cooker9.pressureLevel);
        System.out.println("The isCertified is : " + cooker9.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker9.manufacturingYear);
        System.out.println("The handleLength is : " + cooker9.handleLength);
        System.out.println("The isNonStick is : " + cooker9.isNonStick);
        System.out.println("The certificationType is : " + cooker9.certificationType);

        cooker9.cookerBrand = "Brand9";
        cooker9.cookerId = 9;
        cooker9.cookerPrice = 90.5;
        cooker9.isAvailable = true;
        cooker9.cookerType = "Pressure";
        cooker9.capacity = 5;
        cooker9.weight = 2.5;
        cooker9.isInductionCompatible = true;
        cooker9.material = "Aluminium";
        cooker9.warrantyYears = 5;
        cooker9.diameter = 22.5;
        cooker9.isDishwasherSafe = false;
        cooker9.color = "Silver";
        cooker9.stockQuantity = 50;
        cooker9.thickness = 0.8;
        cooker9.isEcoFriendly = true;
        cooker9.lidType = "Inner Lid";
        cooker9.rating = 5;
        cooker9.pressureLevel = 15.0;
        cooker9.isCertified = true;
        cooker9.countryOfOrigin = "India";
        cooker9.manufacturingYear = 2025;
        cooker9.handleLength = 12.0;
        cooker9.isNonStick = false;
        cooker9.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker9.cookerBrand);
        System.out.println("The cookerId is : " + cooker9.cookerId);
        System.out.println("The cookerPrice is : " + cooker9.cookerPrice);
        System.out.println("The isAvailable is : " + cooker9.isAvailable);
        System.out.println("The cookerType is : " + cooker9.cookerType);
        System.out.println("The capacity is : " + cooker9.capacity);
        System.out.println("The weight is : " + cooker9.weight);
        System.out.println("The isInductionCompatible is : " + cooker9.isInductionCompatible);
        System.out.println("The material is : " + cooker9.material);
        System.out.println("The warrantyYears is : " + cooker9.warrantyYears);
        System.out.println("The diameter is : " + cooker9.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker9.isDishwasherSafe);
        System.out.println("The color is : " + cooker9.color);
        System.out.println("The stockQuantity is : " + cooker9.stockQuantity);
        System.out.println("The thickness is : " + cooker9.thickness);
        System.out.println("The isEcoFriendly is : " + cooker9.isEcoFriendly);
        System.out.println("The lidType is : " + cooker9.lidType);
        System.out.println("The rating is : " + cooker9.rating);
        System.out.println("The pressureLevel is : " + cooker9.pressureLevel);
        System.out.println("The isCertified is : " + cooker9.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker9.manufacturingYear);
        System.out.println("The handleLength is : " + cooker9.handleLength);
        System.out.println("The isNonStick is : " + cooker9.isNonStick);
        System.out.println("The certificationType is : " + cooker9.certificationType);


        Cooker cooker10 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker10.cookerBrand);
        System.out.println("The cookerId is : " + cooker10.cookerId);
        System.out.println("The cookerPrice is : " + cooker10.cookerPrice);
        System.out.println("The isAvailable is : " + cooker10.isAvailable);
        System.out.println("The cookerType is : " + cooker10.cookerType);
        System.out.println("The capacity is : " + cooker10.capacity);
        System.out.println("The weight is : " + cooker10.weight);
        System.out.println("The isInductionCompatible is : " + cooker10.isInductionCompatible);
        System.out.println("The material is : " + cooker10.material);
        System.out.println("The warrantyYears is : " + cooker10.warrantyYears);
        System.out.println("The diameter is : " + cooker10.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker10.isDishwasherSafe);
        System.out.println("The color is : " + cooker10.color);
        System.out.println("The stockQuantity is : " + cooker10.stockQuantity);
        System.out.println("The thickness is : " + cooker10.thickness);
        System.out.println("The isEcoFriendly is : " + cooker10.isEcoFriendly);
        System.out.println("The lidType is : " + cooker10.lidType);
        System.out.println("The rating is : " + cooker10.rating);
        System.out.println("The pressureLevel is : " + cooker10.pressureLevel);
        System.out.println("The isCertified is : " + cooker10.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker10.manufacturingYear);
        System.out.println("The handleLength is : " + cooker10.handleLength);
        System.out.println("The isNonStick is : " + cooker10.isNonStick);
        System.out.println("The certificationType is : " + cooker10.certificationType);

        cooker10.cookerBrand = "Brand10";
        cooker10.cookerId = 10;
        cooker10.cookerPrice = 100.5;
        cooker10.isAvailable = true;
        cooker10.cookerType = "Pressure";
        cooker10.capacity = 5;
        cooker10.weight = 2.5;
        cooker10.isInductionCompatible = true;
        cooker10.material = "Aluminium";
        cooker10.warrantyYears = 5;
        cooker10.diameter = 22.5;
        cooker10.isDishwasherSafe = false;
        cooker10.color = "Silver";
        cooker10.stockQuantity = 50;
        cooker10.thickness = 0.8;
        cooker10.isEcoFriendly = true;
        cooker10.lidType = "Inner Lid";
        cooker10.rating = 5;
        cooker10.pressureLevel = 15.0;
        cooker10.isCertified = true;
        cooker10.countryOfOrigin = "India";
        cooker10.manufacturingYear = 2025;
        cooker10.handleLength = 12.0;
        cooker10.isNonStick = false;
        cooker10.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker10.cookerBrand);
        System.out.println("The cookerId is : " + cooker10.cookerId);
        System.out.println("The cookerPrice is : " + cooker10.cookerPrice);
        System.out.println("The isAvailable is : " + cooker10.isAvailable);
        System.out.println("The cookerType is : " + cooker10.cookerType);
        System.out.println("The capacity is : " + cooker10.capacity);
        System.out.println("The weight is : " + cooker10.weight);
        System.out.println("The isInductionCompatible is : " + cooker10.isInductionCompatible);
        System.out.println("The material is : " + cooker10.material);
        System.out.println("The warrantyYears is : " + cooker10.warrantyYears);
        System.out.println("The diameter is : " + cooker10.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker10.isDishwasherSafe);
        System.out.println("The color is : " + cooker10.color);
        System.out.println("The stockQuantity is : " + cooker10.stockQuantity);
        System.out.println("The thickness is : " + cooker10.thickness);
        System.out.println("The isEcoFriendly is : " + cooker10.isEcoFriendly);
        System.out.println("The lidType is : " + cooker10.lidType);
        System.out.println("The rating is : " + cooker10.rating);
        System.out.println("The pressureLevel is : " + cooker10.pressureLevel);
        System.out.println("The isCertified is : " + cooker10.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker10.manufacturingYear);
        System.out.println("The handleLength is : " + cooker10.handleLength);
        System.out.println("The isNonStick is : " + cooker10.isNonStick);
        System.out.println("The certificationType is : " + cooker10.certificationType);


        Cooker cooker11 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker11.cookerBrand);
        System.out.println("The cookerId is : " + cooker11.cookerId);
        System.out.println("The cookerPrice is : " + cooker11.cookerPrice);
        System.out.println("The isAvailable is : " + cooker11.isAvailable);
        System.out.println("The cookerType is : " + cooker11.cookerType);
        System.out.println("The capacity is : " + cooker11.capacity);
        System.out.println("The weight is : " + cooker11.weight);
        System.out.println("The isInductionCompatible is : " + cooker11.isInductionCompatible);
        System.out.println("The material is : " + cooker11.material);
        System.out.println("The warrantyYears is : " + cooker11.warrantyYears);
        System.out.println("The diameter is : " + cooker11.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker11.isDishwasherSafe);
        System.out.println("The color is : " + cooker11.color);
        System.out.println("The stockQuantity is : " + cooker11.stockQuantity);
        System.out.println("The thickness is : " + cooker11.thickness);
        System.out.println("The isEcoFriendly is : " + cooker11.isEcoFriendly);
        System.out.println("The lidType is : " + cooker11.lidType);
        System.out.println("The rating is : " + cooker11.rating);
        System.out.println("The pressureLevel is : " + cooker11.pressureLevel);
        System.out.println("The isCertified is : " + cooker11.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker11.manufacturingYear);
        System.out.println("The handleLength is : " + cooker11.handleLength);
        System.out.println("The isNonStick is : " + cooker11.isNonStick);
        System.out.println("The certificationType is : " + cooker11.certificationType);

        cooker11.cookerBrand = "Brand11";
        cooker11.cookerId = 11;
        cooker11.cookerPrice = 110.5;
        cooker11.isAvailable = true;
        cooker11.cookerType = "Pressure";
        cooker11.capacity = 5;
        cooker11.weight = 2.5;
        cooker11.isInductionCompatible = true;
        cooker11.material = "Aluminium";
        cooker11.warrantyYears = 5;
        cooker11.diameter = 22.5;
        cooker11.isDishwasherSafe = false;
        cooker11.color = "Silver";
        cooker11.stockQuantity = 50;
        cooker11.thickness = 0.8;
        cooker11.isEcoFriendly = true;
        cooker11.lidType = "Inner Lid";
        cooker11.rating = 5;
        cooker11.pressureLevel = 15.0;
        cooker11.isCertified = true;
        cooker11.countryOfOrigin = "India";
        cooker11.manufacturingYear = 2025;
        cooker11.handleLength = 12.0;
        cooker11.isNonStick = false;
        cooker11.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker11.cookerBrand);
        System.out.println("The cookerId is : " + cooker11.cookerId);
        System.out.println("The cookerPrice is : " + cooker11.cookerPrice);
        System.out.println("The isAvailable is : " + cooker11.isAvailable);
        System.out.println("The cookerType is : " + cooker11.cookerType);
        System.out.println("The capacity is : " + cooker11.capacity);
        System.out.println("The weight is : " + cooker11.weight);
        System.out.println("The isInductionCompatible is : " + cooker11.isInductionCompatible);
        System.out.println("The material is : " + cooker11.material);
        System.out.println("The warrantyYears is : " + cooker11.warrantyYears);
        System.out.println("The diameter is : " + cooker11.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker11.isDishwasherSafe);
        System.out.println("The color is : " + cooker11.color);
        System.out.println("The stockQuantity is : " + cooker11.stockQuantity);
        System.out.println("The thickness is : " + cooker11.thickness);
        System.out.println("The isEcoFriendly is : " + cooker11.isEcoFriendly);
        System.out.println("The lidType is : " + cooker11.lidType);
        System.out.println("The rating is : " + cooker11.rating);
        System.out.println("The pressureLevel is : " + cooker11.pressureLevel);
        System.out.println("The isCertified is : " + cooker11.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker11.manufacturingYear);
        System.out.println("The handleLength is : " + cooker11.handleLength);
        System.out.println("The isNonStick is : " + cooker11.isNonStick);
        System.out.println("The certificationType is : " + cooker11.certificationType);


        Cooker cooker12 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker12.cookerBrand);
        System.out.println("The cookerId is : " + cooker12.cookerId);
        System.out.println("The cookerPrice is : " + cooker12.cookerPrice);
        System.out.println("The isAvailable is : " + cooker12.isAvailable);
        System.out.println("The cookerType is : " + cooker12.cookerType);
        System.out.println("The capacity is : " + cooker12.capacity);
        System.out.println("The weight is : " + cooker12.weight);
        System.out.println("The isInductionCompatible is : " + cooker12.isInductionCompatible);
        System.out.println("The material is : " + cooker12.material);
        System.out.println("The warrantyYears is : " + cooker12.warrantyYears);
        System.out.println("The diameter is : " + cooker12.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker12.isDishwasherSafe);
        System.out.println("The color is : " + cooker12.color);
        System.out.println("The stockQuantity is : " + cooker12.stockQuantity);
        System.out.println("The thickness is : " + cooker12.thickness);
        System.out.println("The isEcoFriendly is : " + cooker12.isEcoFriendly);
        System.out.println("The lidType is : " + cooker12.lidType);
        System.out.println("The rating is : " + cooker12.rating);
        System.out.println("The pressureLevel is : " + cooker12.pressureLevel);
        System.out.println("The isCertified is : " + cooker12.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker12.manufacturingYear);
        System.out.println("The handleLength is : " + cooker12.handleLength);
        System.out.println("The isNonStick is : " + cooker12.isNonStick);
        System.out.println("The certificationType is : " + cooker12.certificationType);

        cooker12.cookerBrand = "Brand12";
        cooker12.cookerId = 12;
        cooker12.cookerPrice = 120.5;
        cooker12.isAvailable = true;
        cooker12.cookerType = "Pressure";
        cooker12.capacity = 5;
        cooker12.weight = 2.5;
        cooker12.isInductionCompatible = true;
        cooker12.material = "Aluminium";
        cooker12.warrantyYears = 5;
        cooker12.diameter = 22.5;
        cooker12.isDishwasherSafe = false;
        cooker12.color = "Silver";
        cooker12.stockQuantity = 50;
        cooker12.thickness = 0.8;
        cooker12.isEcoFriendly = true;
        cooker12.lidType = "Inner Lid";
        cooker12.rating = 5;
        cooker12.pressureLevel = 15.0;
        cooker12.isCertified = true;
        cooker12.countryOfOrigin = "India";
        cooker12.manufacturingYear = 2025;
        cooker12.handleLength = 12.0;
        cooker12.isNonStick = false;
        cooker12.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker12.cookerBrand);
        System.out.println("The cookerId is : " + cooker12.cookerId);
        System.out.println("The cookerPrice is : " + cooker12.cookerPrice);
        System.out.println("The isAvailable is : " + cooker12.isAvailable);
        System.out.println("The cookerType is : " + cooker12.cookerType);
        System.out.println("The capacity is : " + cooker12.capacity);
        System.out.println("The weight is : " + cooker12.weight);
        System.out.println("The isInductionCompatible is : " + cooker12.isInductionCompatible);
        System.out.println("The material is : " + cooker12.material);
        System.out.println("The warrantyYears is : " + cooker12.warrantyYears);
        System.out.println("The diameter is : " + cooker12.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker12.isDishwasherSafe);
        System.out.println("The color is : " + cooker12.color);
        System.out.println("The stockQuantity is : " + cooker12.stockQuantity);
        System.out.println("The thickness is : " + cooker12.thickness);
        System.out.println("The isEcoFriendly is : " + cooker12.isEcoFriendly);
        System.out.println("The lidType is : " + cooker12.lidType);
        System.out.println("The rating is : " + cooker12.rating);
        System.out.println("The pressureLevel is : " + cooker12.pressureLevel);
        System.out.println("The isCertified is : " + cooker12.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker12.manufacturingYear);
        System.out.println("The handleLength is : " + cooker12.handleLength);
        System.out.println("The isNonStick is : " + cooker12.isNonStick);
        System.out.println("The certificationType is : " + cooker12.certificationType);


        Cooker cooker13 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker13.cookerBrand);
        System.out.println("The cookerId is : " + cooker13.cookerId);
        System.out.println("The cookerPrice is : " + cooker13.cookerPrice);
        System.out.println("The isAvailable is : " + cooker13.isAvailable);
        System.out.println("The cookerType is : " + cooker13.cookerType);
        System.out.println("The capacity is : " + cooker13.capacity);
        System.out.println("The weight is : " + cooker13.weight);
        System.out.println("The isInductionCompatible is : " + cooker13.isInductionCompatible);
        System.out.println("The material is : " + cooker13.material);
        System.out.println("The warrantyYears is : " + cooker13.warrantyYears);
        System.out.println("The diameter is : " + cooker13.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker13.isDishwasherSafe);
        System.out.println("The color is : " + cooker13.color);
        System.out.println("The stockQuantity is : " + cooker13.stockQuantity);
        System.out.println("The thickness is : " + cooker13.thickness);
        System.out.println("The isEcoFriendly is : " + cooker13.isEcoFriendly);
        System.out.println("The lidType is : " + cooker13.lidType);
        System.out.println("The rating is : " + cooker13.rating);
        System.out.println("The pressureLevel is : " + cooker13.pressureLevel);
        System.out.println("The isCertified is : " + cooker13.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker13.manufacturingYear);
        System.out.println("The handleLength is : " + cooker13.handleLength);
        System.out.println("The isNonStick is : " + cooker13.isNonStick);
        System.out.println("The certificationType is : " + cooker13.certificationType);

        cooker13.cookerBrand = "Brand13";
        cooker13.cookerId = 13;
        cooker13.cookerPrice = 130.5;
        cooker13.isAvailable = true;
        cooker13.cookerType = "Pressure";
        cooker13.capacity = 5;
        cooker13.weight = 2.5;
        cooker13.isInductionCompatible = true;
        cooker13.material = "Aluminium";
        cooker13.warrantyYears = 5;
        cooker13.diameter = 22.5;
        cooker13.isDishwasherSafe = false;
        cooker13.color = "Silver";
        cooker13.stockQuantity = 50;
        cooker13.thickness = 0.8;
        cooker13.isEcoFriendly = true;
        cooker13.lidType = "Inner Lid";
        cooker13.rating = 5;
        cooker13.pressureLevel = 15.0;
        cooker13.isCertified = true;
        cooker13.countryOfOrigin = "India";
        cooker13.manufacturingYear = 2025;
        cooker13.handleLength = 12.0;
        cooker13.isNonStick = false;
        cooker13.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker13.cookerBrand);
        System.out.println("The cookerId is : " + cooker13.cookerId);
        System.out.println("The cookerPrice is : " + cooker13.cookerPrice);
        System.out.println("The isAvailable is : " + cooker13.isAvailable);
        System.out.println("The cookerType is : " + cooker13.cookerType);
        System.out.println("The capacity is : " + cooker13.capacity);
        System.out.println("The weight is : " + cooker13.weight);
        System.out.println("The isInductionCompatible is : " + cooker13.isInductionCompatible);
        System.out.println("The material is : " + cooker13.material);
        System.out.println("The warrantyYears is : " + cooker13.warrantyYears);
        System.out.println("The diameter is : " + cooker13.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker13.isDishwasherSafe);
        System.out.println("The color is : " + cooker13.color);
        System.out.println("The stockQuantity is : " + cooker13.stockQuantity);
        System.out.println("The thickness is : " + cooker13.thickness);
        System.out.println("The isEcoFriendly is : " + cooker13.isEcoFriendly);
        System.out.println("The lidType is : " + cooker13.lidType);
        System.out.println("The rating is : " + cooker13.rating);
        System.out.println("The pressureLevel is : " + cooker13.pressureLevel);
        System.out.println("The isCertified is : " + cooker13.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker13.manufacturingYear);
        System.out.println("The handleLength is : " + cooker13.handleLength);
        System.out.println("The isNonStick is : " + cooker13.isNonStick);
        System.out.println("The certificationType is : " + cooker13.certificationType);


        Cooker cooker14 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker14.cookerBrand);
        System.out.println("The cookerId is : " + cooker14.cookerId);
        System.out.println("The cookerPrice is : " + cooker14.cookerPrice);
        System.out.println("The isAvailable is : " + cooker14.isAvailable);
        System.out.println("The cookerType is : " + cooker14.cookerType);
        System.out.println("The capacity is : " + cooker14.capacity);
        System.out.println("The weight is : " + cooker14.weight);
        System.out.println("The isInductionCompatible is : " + cooker14.isInductionCompatible);
        System.out.println("The material is : " + cooker14.material);
        System.out.println("The warrantyYears is : " + cooker14.warrantyYears);
        System.out.println("The diameter is : " + cooker14.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker14.isDishwasherSafe);
        System.out.println("The color is : " + cooker14.color);
        System.out.println("The stockQuantity is : " + cooker14.stockQuantity);
        System.out.println("The thickness is : " + cooker14.thickness);
        System.out.println("The isEcoFriendly is : " + cooker14.isEcoFriendly);
        System.out.println("The lidType is : " + cooker14.lidType);
        System.out.println("The rating is : " + cooker14.rating);
        System.out.println("The pressureLevel is : " + cooker14.pressureLevel);
        System.out.println("The isCertified is : " + cooker14.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker14.manufacturingYear);
        System.out.println("The handleLength is : " + cooker14.handleLength);
        System.out.println("The isNonStick is : " + cooker14.isNonStick);
        System.out.println("The certificationType is : " + cooker14.certificationType);

        cooker14.cookerBrand = "Brand14";
        cooker14.cookerId = 14;
        cooker14.cookerPrice = 140.5;
        cooker14.isAvailable = true;
        cooker14.cookerType = "Pressure";
        cooker14.capacity = 5;
        cooker14.weight = 2.5;
        cooker14.isInductionCompatible = true;
        cooker14.material = "Aluminium";
        cooker14.warrantyYears = 5;
        cooker14.diameter = 22.5;
        cooker14.isDishwasherSafe = false;
        cooker14.color = "Silver";
        cooker14.stockQuantity = 50;
        cooker14.thickness = 0.8;
        cooker14.isEcoFriendly = true;
        cooker14.lidType = "Inner Lid";
        cooker14.rating = 5;
        cooker14.pressureLevel = 15.0;
        cooker14.isCertified = true;
        cooker14.countryOfOrigin = "India";
        cooker14.manufacturingYear = 2025;
        cooker14.handleLength = 12.0;
        cooker14.isNonStick = false;
        cooker14.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker14.cookerBrand);
        System.out.println("The cookerId is : " + cooker14.cookerId);
        System.out.println("The cookerPrice is : " + cooker14.cookerPrice);
        System.out.println("The isAvailable is : " + cooker14.isAvailable);
        System.out.println("The cookerType is : " + cooker14.cookerType);
        System.out.println("The capacity is : " + cooker14.capacity);
        System.out.println("The weight is : " + cooker14.weight);
        System.out.println("The isInductionCompatible is : " + cooker14.isInductionCompatible);
        System.out.println("The material is : " + cooker14.material);
        System.out.println("The warrantyYears is : " + cooker14.warrantyYears);
        System.out.println("The diameter is : " + cooker14.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker14.isDishwasherSafe);
        System.out.println("The color is : " + cooker14.color);
        System.out.println("The stockQuantity is : " + cooker14.stockQuantity);
        System.out.println("The thickness is : " + cooker14.thickness);
        System.out.println("The isEcoFriendly is : " + cooker14.isEcoFriendly);
        System.out.println("The lidType is : " + cooker14.lidType);
        System.out.println("The rating is : " + cooker14.rating);
        System.out.println("The pressureLevel is : " + cooker14.pressureLevel);
        System.out.println("The isCertified is : " + cooker14.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker14.manufacturingYear);
        System.out.println("The handleLength is : " + cooker14.handleLength);
        System.out.println("The isNonStick is : " + cooker14.isNonStick);
        System.out.println("The certificationType is : " + cooker14.certificationType);


        Cooker cooker15 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker15.cookerBrand);
        System.out.println("The cookerId is : " + cooker15.cookerId);
        System.out.println("The cookerPrice is : " + cooker15.cookerPrice);
        System.out.println("The isAvailable is : " + cooker15.isAvailable);
        System.out.println("The cookerType is : " + cooker15.cookerType);
        System.out.println("The capacity is : " + cooker15.capacity);
        System.out.println("The weight is : " + cooker15.weight);
        System.out.println("The isInductionCompatible is : " + cooker15.isInductionCompatible);
        System.out.println("The material is : " + cooker15.material);
        System.out.println("The warrantyYears is : " + cooker15.warrantyYears);
        System.out.println("The diameter is : " + cooker15.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker15.isDishwasherSafe);
        System.out.println("The color is : " + cooker15.color);
        System.out.println("The stockQuantity is : " + cooker15.stockQuantity);
        System.out.println("The thickness is : " + cooker15.thickness);
        System.out.println("The isEcoFriendly is : " + cooker15.isEcoFriendly);
        System.out.println("The lidType is : " + cooker15.lidType);
        System.out.println("The rating is : " + cooker15.rating);
        System.out.println("The pressureLevel is : " + cooker15.pressureLevel);
        System.out.println("The isCertified is : " + cooker15.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker15.manufacturingYear);
        System.out.println("The handleLength is : " + cooker15.handleLength);
        System.out.println("The isNonStick is : " + cooker15.isNonStick);
        System.out.println("The certificationType is : " + cooker15.certificationType);

        cooker15.cookerBrand = "Brand15";
        cooker15.cookerId = 15;
        cooker15.cookerPrice = 150.5;
        cooker15.isAvailable = true;
        cooker15.cookerType = "Pressure";
        cooker15.capacity = 5;
        cooker15.weight = 2.5;
        cooker15.isInductionCompatible = true;
        cooker15.material = "Aluminium";
        cooker15.warrantyYears = 5;
        cooker15.diameter = 22.5;
        cooker15.isDishwasherSafe = false;
        cooker15.color = "Silver";
        cooker15.stockQuantity = 50;
        cooker15.thickness = 0.8;
        cooker15.isEcoFriendly = true;
        cooker15.lidType = "Inner Lid";
        cooker15.rating = 5;
        cooker15.pressureLevel = 15.0;
        cooker15.isCertified = true;
        cooker15.countryOfOrigin = "India";
        cooker15.manufacturingYear = 2025;
        cooker15.handleLength = 12.0;
        cooker15.isNonStick = false;
        cooker15.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker15.cookerBrand);
        System.out.println("The cookerId is : " + cooker15.cookerId);
        System.out.println("The cookerPrice is : " + cooker15.cookerPrice);
        System.out.println("The isAvailable is : " + cooker15.isAvailable);
        System.out.println("The cookerType is : " + cooker15.cookerType);
        System.out.println("The capacity is : " + cooker15.capacity);
        System.out.println("The weight is : " + cooker15.weight);
        System.out.println("The isInductionCompatible is : " + cooker15.isInductionCompatible);
        System.out.println("The material is : " + cooker15.material);
        System.out.println("The warrantyYears is : " + cooker15.warrantyYears);
        System.out.println("The diameter is : " + cooker15.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker15.isDishwasherSafe);
        System.out.println("The color is : " + cooker15.color);
        System.out.println("The stockQuantity is : " + cooker15.stockQuantity);
        System.out.println("The thickness is : " + cooker15.thickness);
        System.out.println("The isEcoFriendly is : " + cooker15.isEcoFriendly);
        System.out.println("The lidType is : " + cooker15.lidType);
        System.out.println("The rating is : " + cooker15.rating);
        System.out.println("The pressureLevel is : " + cooker15.pressureLevel);
        System.out.println("The isCertified is : " + cooker15.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker15.manufacturingYear);
        System.out.println("The handleLength is : " + cooker15.handleLength);
        System.out.println("The isNonStick is : " + cooker15.isNonStick);
        System.out.println("The certificationType is : " + cooker15.certificationType);


        Cooker cooker16 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker16.cookerBrand);
        System.out.println("The cookerId is : " + cooker16.cookerId);
        System.out.println("The cookerPrice is : " + cooker16.cookerPrice);
        System.out.println("The isAvailable is : " + cooker16.isAvailable);
        System.out.println("The cookerType is : " + cooker16.cookerType);
        System.out.println("The capacity is : " + cooker16.capacity);
        System.out.println("The weight is : " + cooker16.weight);
        System.out.println("The isInductionCompatible is : " + cooker16.isInductionCompatible);
        System.out.println("The material is : " + cooker16.material);
        System.out.println("The warrantyYears is : " + cooker16.warrantyYears);
        System.out.println("The diameter is : " + cooker16.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker16.isDishwasherSafe);
        System.out.println("The color is : " + cooker16.color);
        System.out.println("The stockQuantity is : " + cooker16.stockQuantity);
        System.out.println("The thickness is : " + cooker16.thickness);
        System.out.println("The isEcoFriendly is : " + cooker16.isEcoFriendly);
        System.out.println("The lidType is : " + cooker16.lidType);
        System.out.println("The rating is : " + cooker16.rating);
        System.out.println("The pressureLevel is : " + cooker16.pressureLevel);
        System.out.println("The isCertified is : " + cooker16.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker16.manufacturingYear);
        System.out.println("The handleLength is : " + cooker16.handleLength);
        System.out.println("The isNonStick is : " + cooker16.isNonStick);
        System.out.println("The certificationType is : " + cooker16.certificationType);

        cooker16.cookerBrand = "Brand16";
        cooker16.cookerId = 16;
        cooker16.cookerPrice = 160.5;
        cooker16.isAvailable = true;
        cooker16.cookerType = "Pressure";
        cooker16.capacity = 5;
        cooker16.weight = 2.5;
        cooker16.isInductionCompatible = true;
        cooker16.material = "Aluminium";
        cooker16.warrantyYears = 5;
        cooker16.diameter = 22.5;
        cooker16.isDishwasherSafe = false;
        cooker16.color = "Silver";
        cooker16.stockQuantity = 50;
        cooker16.thickness = 0.8;
        cooker16.isEcoFriendly = true;
        cooker16.lidType = "Inner Lid";
        cooker16.rating = 5;
        cooker16.pressureLevel = 15.0;
        cooker16.isCertified = true;
        cooker16.countryOfOrigin = "India";
        cooker16.manufacturingYear = 2025;
        cooker16.handleLength = 12.0;
        cooker16.isNonStick = false;
        cooker16.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker16.cookerBrand);
        System.out.println("The cookerId is : " + cooker16.cookerId);
        System.out.println("The cookerPrice is : " + cooker16.cookerPrice);
        System.out.println("The isAvailable is : " + cooker16.isAvailable);
        System.out.println("The cookerType is : " + cooker16.cookerType);
        System.out.println("The capacity is : " + cooker16.capacity);
        System.out.println("The weight is : " + cooker16.weight);
        System.out.println("The isInductionCompatible is : " + cooker16.isInductionCompatible);
        System.out.println("The material is : " + cooker16.material);
        System.out.println("The warrantyYears is : " + cooker16.warrantyYears);
        System.out.println("The diameter is : " + cooker16.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker16.isDishwasherSafe);
        System.out.println("The color is : " + cooker16.color);
        System.out.println("The stockQuantity is : " + cooker16.stockQuantity);
        System.out.println("The thickness is : " + cooker16.thickness);
        System.out.println("The isEcoFriendly is : " + cooker16.isEcoFriendly);
        System.out.println("The lidType is : " + cooker16.lidType);
        System.out.println("The rating is : " + cooker16.rating);
        System.out.println("The pressureLevel is : " + cooker16.pressureLevel);
        System.out.println("The isCertified is : " + cooker16.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker16.manufacturingYear);
        System.out.println("The handleLength is : " + cooker16.handleLength);
        System.out.println("The isNonStick is : " + cooker16.isNonStick);
        System.out.println("The certificationType is : " + cooker16.certificationType);


        Cooker cooker17 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker17.cookerBrand);
        System.out.println("The cookerId is : " + cooker17.cookerId);
        System.out.println("The cookerPrice is : " + cooker17.cookerPrice);
        System.out.println("The isAvailable is : " + cooker17.isAvailable);
        System.out.println("The cookerType is : " + cooker17.cookerType);
        System.out.println("The capacity is : " + cooker17.capacity);
        System.out.println("The weight is : " + cooker17.weight);
        System.out.println("The isInductionCompatible is : " + cooker17.isInductionCompatible);
        System.out.println("The material is : " + cooker17.material);
        System.out.println("The warrantyYears is : " + cooker17.warrantyYears);
        System.out.println("The diameter is : " + cooker17.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker17.isDishwasherSafe);
        System.out.println("The color is : " + cooker17.color);
        System.out.println("The stockQuantity is : " + cooker17.stockQuantity);
        System.out.println("The thickness is : " + cooker17.thickness);
        System.out.println("The isEcoFriendly is : " + cooker17.isEcoFriendly);
        System.out.println("The lidType is : " + cooker17.lidType);
        System.out.println("The rating is : " + cooker17.rating);
        System.out.println("The pressureLevel is : " + cooker17.pressureLevel);
        System.out.println("The isCertified is : " + cooker17.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker17.manufacturingYear);
        System.out.println("The handleLength is : " + cooker17.handleLength);
        System.out.println("The isNonStick is : " + cooker17.isNonStick);
        System.out.println("The certificationType is : " + cooker17.certificationType);

        cooker17.cookerBrand = "Brand17";
        cooker17.cookerId = 17;
        cooker17.cookerPrice = 170.5;
        cooker17.isAvailable = true;
        cooker17.cookerType = "Pressure";
        cooker17.capacity = 5;
        cooker17.weight = 2.5;
        cooker17.isInductionCompatible = true;
        cooker17.material = "Aluminium";
        cooker17.warrantyYears = 5;
        cooker17.diameter = 22.5;
        cooker17.isDishwasherSafe = false;
        cooker17.color = "Silver";
        cooker17.stockQuantity = 50;
        cooker17.thickness = 0.8;
        cooker17.isEcoFriendly = true;
        cooker17.lidType = "Inner Lid";
        cooker17.rating = 5;
        cooker17.pressureLevel = 15.0;
        cooker17.isCertified = true;
        cooker17.countryOfOrigin = "India";
        cooker17.manufacturingYear = 2025;
        cooker17.handleLength = 12.0;
        cooker17.isNonStick = false;
        cooker17.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker17.cookerBrand);
        System.out.println("The cookerId is : " + cooker17.cookerId);
        System.out.println("The cookerPrice is : " + cooker17.cookerPrice);
        System.out.println("The isAvailable is : " + cooker17.isAvailable);
        System.out.println("The cookerType is : " + cooker17.cookerType);
        System.out.println("The capacity is : " + cooker17.capacity);
        System.out.println("The weight is : " + cooker17.weight);
        System.out.println("The isInductionCompatible is : " + cooker17.isInductionCompatible);
        System.out.println("The material is : " + cooker17.material);
        System.out.println("The warrantyYears is : " + cooker17.warrantyYears);
        System.out.println("The diameter is : " + cooker17.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker17.isDishwasherSafe);
        System.out.println("The color is : " + cooker17.color);
        System.out.println("The stockQuantity is : " + cooker17.stockQuantity);
        System.out.println("The thickness is : " + cooker17.thickness);
        System.out.println("The isEcoFriendly is : " + cooker17.isEcoFriendly);
        System.out.println("The lidType is : " + cooker17.lidType);
        System.out.println("The rating is : " + cooker17.rating);
        System.out.println("The pressureLevel is : " + cooker17.pressureLevel);
        System.out.println("The isCertified is : " + cooker17.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker17.manufacturingYear);
        System.out.println("The handleLength is : " + cooker17.handleLength);
        System.out.println("The isNonStick is : " + cooker17.isNonStick);
        System.out.println("The certificationType is : " + cooker17.certificationType);


        Cooker cooker18 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker18.cookerBrand);
        System.out.println("The cookerId is : " + cooker18.cookerId);
        System.out.println("The cookerPrice is : " + cooker18.cookerPrice);
        System.out.println("The isAvailable is : " + cooker18.isAvailable);
        System.out.println("The cookerType is : " + cooker18.cookerType);
        System.out.println("The capacity is : " + cooker18.capacity);
        System.out.println("The weight is : " + cooker18.weight);
        System.out.println("The isInductionCompatible is : " + cooker18.isInductionCompatible);
        System.out.println("The material is : " + cooker18.material);
        System.out.println("The warrantyYears is : " + cooker18.warrantyYears);
        System.out.println("The diameter is : " + cooker18.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker18.isDishwasherSafe);
        System.out.println("The color is : " + cooker18.color);
        System.out.println("The stockQuantity is : " + cooker18.stockQuantity);
        System.out.println("The thickness is : " + cooker18.thickness);
        System.out.println("The isEcoFriendly is : " + cooker18.isEcoFriendly);
        System.out.println("The lidType is : " + cooker18.lidType);
        System.out.println("The rating is : " + cooker18.rating);
        System.out.println("The pressureLevel is : " + cooker18.pressureLevel);
        System.out.println("The isCertified is : " + cooker18.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker18.manufacturingYear);
        System.out.println("The handleLength is : " + cooker18.handleLength);
        System.out.println("The isNonStick is : " + cooker18.isNonStick);
        System.out.println("The certificationType is : " + cooker18.certificationType);

        cooker18.cookerBrand = "Brand18";
        cooker18.cookerId = 18;
        cooker18.cookerPrice = 180.5;
        cooker18.isAvailable = true;
        cooker18.cookerType = "Pressure";
        cooker18.capacity = 5;
        cooker18.weight = 2.5;
        cooker18.isInductionCompatible = true;
        cooker18.material = "Aluminium";
        cooker18.warrantyYears = 5;
        cooker18.diameter = 22.5;
        cooker18.isDishwasherSafe = false;
        cooker18.color = "Silver";
        cooker18.stockQuantity = 50;
        cooker18.thickness = 0.8;
        cooker18.isEcoFriendly = true;
        cooker18.lidType = "Inner Lid";
        cooker18.rating = 5;
        cooker18.pressureLevel = 15.0;
        cooker18.isCertified = true;
        cooker18.countryOfOrigin = "India";
        cooker18.manufacturingYear = 2025;
        cooker18.handleLength = 12.0;
        cooker18.isNonStick = false;
        cooker18.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker18.cookerBrand);
        System.out.println("The cookerId is : " + cooker18.cookerId);
        System.out.println("The cookerPrice is : " + cooker18.cookerPrice);
        System.out.println("The isAvailable is : " + cooker18.isAvailable);
        System.out.println("The cookerType is : " + cooker18.cookerType);
        System.out.println("The capacity is : " + cooker18.capacity);
        System.out.println("The weight is : " + cooker18.weight);
        System.out.println("The isInductionCompatible is : " + cooker18.isInductionCompatible);
        System.out.println("The material is : " + cooker18.material);
        System.out.println("The warrantyYears is : " + cooker18.warrantyYears);
        System.out.println("The diameter is : " + cooker18.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker18.isDishwasherSafe);
        System.out.println("The color is : " + cooker18.color);
        System.out.println("The stockQuantity is : " + cooker18.stockQuantity);
        System.out.println("The thickness is : " + cooker18.thickness);
        System.out.println("The isEcoFriendly is : " + cooker18.isEcoFriendly);
        System.out.println("The lidType is : " + cooker18.lidType);
        System.out.println("The rating is : " + cooker18.rating);
        System.out.println("The pressureLevel is : " + cooker18.pressureLevel);
        System.out.println("The isCertified is : " + cooker18.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker18.manufacturingYear);
        System.out.println("The handleLength is : " + cooker18.handleLength);
        System.out.println("The isNonStick is : " + cooker18.isNonStick);
        System.out.println("The certificationType is : " + cooker18.certificationType);


        Cooker cooker19 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker19.cookerBrand);
        System.out.println("The cookerId is : " + cooker19.cookerId);
        System.out.println("The cookerPrice is : " + cooker19.cookerPrice);
        System.out.println("The isAvailable is : " + cooker19.isAvailable);
        System.out.println("The cookerType is : " + cooker19.cookerType);
        System.out.println("The capacity is : " + cooker19.capacity);
        System.out.println("The weight is : " + cooker19.weight);
        System.out.println("The isInductionCompatible is : " + cooker19.isInductionCompatible);
        System.out.println("The material is : " + cooker19.material);
        System.out.println("The warrantyYears is : " + cooker19.warrantyYears);
        System.out.println("The diameter is : " + cooker19.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker19.isDishwasherSafe);
        System.out.println("The color is : " + cooker19.color);
        System.out.println("The stockQuantity is : " + cooker19.stockQuantity);
        System.out.println("The thickness is : " + cooker19.thickness);
        System.out.println("The isEcoFriendly is : " + cooker19.isEcoFriendly);
        System.out.println("The lidType is : " + cooker19.lidType);
        System.out.println("The rating is : " + cooker19.rating);
        System.out.println("The pressureLevel is : " + cooker19.pressureLevel);
        System.out.println("The isCertified is : " + cooker19.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker19.manufacturingYear);
        System.out.println("The handleLength is : " + cooker19.handleLength);
        System.out.println("The isNonStick is : " + cooker19.isNonStick);
        System.out.println("The certificationType is : " + cooker19.certificationType);

        cooker19.cookerBrand = "Brand19";
        cooker19.cookerId = 19;
        cooker19.cookerPrice = 190.5;
        cooker19.isAvailable = true;
        cooker19.cookerType = "Pressure";
        cooker19.capacity = 5;
        cooker19.weight = 2.5;
        cooker19.isInductionCompatible = true;
        cooker19.material = "Aluminium";
        cooker19.warrantyYears = 5;
        cooker19.diameter = 22.5;
        cooker19.isDishwasherSafe = false;
        cooker19.color = "Silver";
        cooker19.stockQuantity = 50;
        cooker19.thickness = 0.8;
        cooker19.isEcoFriendly = true;
        cooker19.lidType = "Inner Lid";
        cooker19.rating = 5;
        cooker19.pressureLevel = 15.0;
        cooker19.isCertified = true;
        cooker19.countryOfOrigin = "India";
        cooker19.manufacturingYear = 2025;
        cooker19.handleLength = 12.0;
        cooker19.isNonStick = false;
        cooker19.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker19.cookerBrand);
        System.out.println("The cookerId is : " + cooker19.cookerId);
        System.out.println("The cookerPrice is : " + cooker19.cookerPrice);
        System.out.println("The isAvailable is : " + cooker19.isAvailable);
        System.out.println("The cookerType is : " + cooker19.cookerType);
        System.out.println("The capacity is : " + cooker19.capacity);
        System.out.println("The weight is : " + cooker19.weight);
        System.out.println("The isInductionCompatible is : " + cooker19.isInductionCompatible);
        System.out.println("The material is : " + cooker19.material);
        System.out.println("The warrantyYears is : " + cooker19.warrantyYears);
        System.out.println("The diameter is : " + cooker19.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker19.isDishwasherSafe);
        System.out.println("The color is : " + cooker19.color);
        System.out.println("The stockQuantity is : " + cooker19.stockQuantity);
        System.out.println("The thickness is : " + cooker19.thickness);
        System.out.println("The isEcoFriendly is : " + cooker19.isEcoFriendly);
        System.out.println("The lidType is : " + cooker19.lidType);
        System.out.println("The rating is : " + cooker19.rating);
        System.out.println("The pressureLevel is : " + cooker19.pressureLevel);
        System.out.println("The isCertified is : " + cooker19.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker19.manufacturingYear);
        System.out.println("The handleLength is : " + cooker19.handleLength);
        System.out.println("The isNonStick is : " + cooker19.isNonStick);
        System.out.println("The certificationType is : " + cooker19.certificationType);


        Cooker cooker20 = new Cooker();

        System.out.println("Before initialization");

        System.out.println("The cookerBrand is : " + cooker20.cookerBrand);
        System.out.println("The cookerId is : " + cooker20.cookerId);
        System.out.println("The cookerPrice is : " + cooker20.cookerPrice);
        System.out.println("The isAvailable is : " + cooker20.isAvailable);
        System.out.println("The cookerType is : " + cooker20.cookerType);
        System.out.println("The capacity is : " + cooker20.capacity);
        System.out.println("The weight is : " + cooker20.weight);
        System.out.println("The isInductionCompatible is : " + cooker20.isInductionCompatible);
        System.out.println("The material is : " + cooker20.material);
        System.out.println("The warrantyYears is : " + cooker20.warrantyYears);
        System.out.println("The diameter is : " + cooker20.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker20.isDishwasherSafe);
        System.out.println("The color is : " + cooker20.color);
        System.out.println("The stockQuantity is : " + cooker20.stockQuantity);
        System.out.println("The thickness is : " + cooker20.thickness);
        System.out.println("The isEcoFriendly is : " + cooker20.isEcoFriendly);
        System.out.println("The lidType is : " + cooker20.lidType);
        System.out.println("The rating is : " + cooker20.rating);
        System.out.println("The pressureLevel is : " + cooker20.pressureLevel);
        System.out.println("The isCertified is : " + cooker20.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker20.manufacturingYear);
        System.out.println("The handleLength is : " + cooker20.handleLength);
        System.out.println("The isNonStick is : " + cooker20.isNonStick);
        System.out.println("The certificationType is : " + cooker20.certificationType);

        cooker20.cookerBrand = "Brand20";
        cooker20.cookerId = 20;
        cooker20.cookerPrice = 200.5;
        cooker20.isAvailable = true;
        cooker20.cookerType = "Pressure";
        cooker20.capacity = 5;
        cooker20.weight = 2.5;
        cooker20.isInductionCompatible = true;
        cooker20.material = "Aluminium";
        cooker20.warrantyYears = 5;
        cooker20.diameter = 22.5;
        cooker20.isDishwasherSafe = false;
        cooker20.color = "Silver";
        cooker20.stockQuantity = 50;
        cooker20.thickness = 0.8;
        cooker20.isEcoFriendly = true;
        cooker20.lidType = "Inner Lid";
        cooker20.rating = 5;
        cooker20.pressureLevel = 15.0;
        cooker20.isCertified = true;
        cooker20.countryOfOrigin = "India";
        cooker20.manufacturingYear = 2025;
        cooker20.handleLength = 12.0;
        cooker20.isNonStick = false;
        cooker20.certificationType = "ISI";

        System.out.println("After initialization");

        System.out.println("The cookerBrand is : " + cooker20.cookerBrand);
        System.out.println("The cookerId is : " + cooker20.cookerId);
        System.out.println("The cookerPrice is : " + cooker20.cookerPrice);
        System.out.println("The isAvailable is : " + cooker20.isAvailable);
        System.out.println("The cookerType is : " + cooker20.cookerType);
        System.out.println("The capacity is : " + cooker20.capacity);
        System.out.println("The weight is : " + cooker20.weight);
        System.out.println("The isInductionCompatible is : " + cooker20.isInductionCompatible);
        System.out.println("The material is : " + cooker20.material);
        System.out.println("The warrantyYears is : " + cooker20.warrantyYears);
        System.out.println("The diameter is : " + cooker20.diameter);
        System.out.println("The isDishwasherSafe is : " + cooker20.isDishwasherSafe);
        System.out.println("The color is : " + cooker20.color);
        System.out.println("The stockQuantity is : " + cooker20.stockQuantity);
        System.out.println("The thickness is : " + cooker20.thickness);
        System.out.println("The isEcoFriendly is : " + cooker20.isEcoFriendly);
        System.out.println("The lidType is : " + cooker20.lidType);
        System.out.println("The rating is : " + cooker20.rating);
        System.out.println("The pressureLevel is : " + cooker20.pressureLevel);
        System.out.println("The isCertified is : " + cooker20.isCertified);
        System.out.println("The countryOfOrigin is : " + cooker20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cooker20.manufacturingYear);
        System.out.println("The handleLength is : " + cooker20.handleLength);
        System.out.println("The isNonStick is : " + cooker20.isNonStick);
        System.out.println("The certificationType is : " + cooker20.certificationType);


    }
}
