class DroneExecutor {

    public static void main(String[] args) {

        Drone drone1 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone1.droneBrand);
        System.out.println("The droneId is : " + drone1.droneId);
        System.out.println("The dronePrice is : " + drone1.dronePrice);
        System.out.println("The isAvailable is : " + drone1.isAvailable);
        System.out.println("The droneType is : " + drone1.droneType);
        System.out.println("The maxSpeed is : " + drone1.maxSpeed);
        System.out.println("The weight is : " + drone1.weight);
        System.out.println("The hasCamera is : " + drone1.hasCamera);
        System.out.println("The cameraResolution is : " + drone1.cameraResolution);
        System.out.println("The warrantyYears is : " + drone1.warrantyYears);
        System.out.println("The flightTime is : " + drone1.flightTime);
        System.out.println("The hasGPS is : " + drone1.hasGPS);
        System.out.println("The color is : " + drone1.color);
        System.out.println("The stockQuantity is : " + drone1.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone1.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone1.isEcoFriendly);
        System.out.println("The controlType is : " + drone1.controlType);
        System.out.println("The rating is : " + drone1.rating);
        System.out.println("The maxRange is : " + drone1.maxRange);
        System.out.println("The isCertified is : " + drone1.isCertified);
        System.out.println("The countryOfOrigin is : " + drone1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone1.manufacturingYear);
        System.out.println("The propellerSize is : " + drone1.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone1.supportsMobileApp);
        System.out.println("The certificationType is : " + drone1.certificationType);

        drone1.droneBrand = "SkyTech";
        drone1.droneId = 1;
        drone1.dronePrice = 1500.99;
        drone1.isAvailable = true;
        drone1.droneType = "Quadcopter";
        drone1.maxSpeed = 60.0;
        drone1.weight = 1.4;
        drone1.hasCamera = true;
        drone1.cameraResolution = "4K";
        drone1.warrantyYears = 2;
        drone1.flightTime = 30.0;
        drone1.hasGPS = true;
        drone1.color = "Black";
        drone1.stockQuantity = 12;
        drone1.batteryCapacity = 4500.0;
        drone1.isEcoFriendly = true;
        drone1.controlType = "Remote";
        drone1.rating = 5;
        drone1.maxRange = 5000.0;
        drone1.isCertified = true;
        drone1.countryOfOrigin = "China";
        drone1.manufacturingYear = 2025;
        drone1.propellerSize = 10.0;
        drone1.supportsMobileApp = true;
        drone1.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone1.droneBrand);
        System.out.println("The droneId is : " + drone1.droneId);
        System.out.println("The dronePrice is : " + drone1.dronePrice);
        System.out.println("The isAvailable is : " + drone1.isAvailable);
        System.out.println("The droneType is : " + drone1.droneType);
        System.out.println("The maxSpeed is : " + drone1.maxSpeed);
        System.out.println("The weight is : " + drone1.weight);
        System.out.println("The hasCamera is : " + drone1.hasCamera);
        System.out.println("The cameraResolution is : " + drone1.cameraResolution);
        System.out.println("The warrantyYears is : " + drone1.warrantyYears);
        System.out.println("The flightTime is : " + drone1.flightTime);
        System.out.println("The hasGPS is : " + drone1.hasGPS);
        System.out.println("The color is : " + drone1.color);
        System.out.println("The stockQuantity is : " + drone1.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone1.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone1.isEcoFriendly);
        System.out.println("The controlType is : " + drone1.controlType);
        System.out.println("The rating is : " + drone1.rating);
        System.out.println("The maxRange is : " + drone1.maxRange);
        System.out.println("The isCertified is : " + drone1.isCertified);
        System.out.println("The countryOfOrigin is : " + drone1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone1.manufacturingYear);
        System.out.println("The propellerSize is : " + drone1.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone1.supportsMobileApp);
        System.out.println("The certificationType is : " + drone1.certificationType);


        Drone drone2 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone2.droneBrand);
        System.out.println("The droneId is : " + drone2.droneId);
        System.out.println("The dronePrice is : " + drone2.dronePrice);
        System.out.println("The isAvailable is : " + drone2.isAvailable);
        System.out.println("The droneType is : " + drone2.droneType);
        System.out.println("The maxSpeed is : " + drone2.maxSpeed);
        System.out.println("The weight is : " + drone2.weight);
        System.out.println("The hasCamera is : " + drone2.hasCamera);
        System.out.println("The cameraResolution is : " + drone2.cameraResolution);
        System.out.println("The warrantyYears is : " + drone2.warrantyYears);
        System.out.println("The flightTime is : " + drone2.flightTime);
        System.out.println("The hasGPS is : " + drone2.hasGPS);
        System.out.println("The color is : " + drone2.color);
        System.out.println("The stockQuantity is : " + drone2.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone2.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone2.isEcoFriendly);
        System.out.println("The controlType is : " + drone2.controlType);
        System.out.println("The rating is : " + drone2.rating);
        System.out.println("The maxRange is : " + drone2.maxRange);
        System.out.println("The isCertified is : " + drone2.isCertified);
        System.out.println("The countryOfOrigin is : " + drone2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone2.manufacturingYear);
        System.out.println("The propellerSize is : " + drone2.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone2.supportsMobileApp);
        System.out.println("The certificationType is : " + drone2.certificationType);

        drone2.droneBrand = "SkyTech";
        drone2.droneId = 2;
        drone2.dronePrice = 2500.99;
        drone2.isAvailable = true;
        drone2.droneType = "Quadcopter";
        drone2.maxSpeed = 60.0;
        drone2.weight = 1.4;
        drone2.hasCamera = true;
        drone2.cameraResolution = "4K";
        drone2.warrantyYears = 2;
        drone2.flightTime = 30.0;
        drone2.hasGPS = true;
        drone2.color = "Black";
        drone2.stockQuantity = 12;
        drone2.batteryCapacity = 4500.0;
        drone2.isEcoFriendly = true;
        drone2.controlType = "Remote";
        drone2.rating = 5;
        drone2.maxRange = 5000.0;
        drone2.isCertified = true;
        drone2.countryOfOrigin = "China";
        drone2.manufacturingYear = 2025;
        drone2.propellerSize = 10.0;
        drone2.supportsMobileApp = true;
        drone2.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone2.droneBrand);
        System.out.println("The droneId is : " + drone2.droneId);
        System.out.println("The dronePrice is : " + drone2.dronePrice);
        System.out.println("The isAvailable is : " + drone2.isAvailable);
        System.out.println("The droneType is : " + drone2.droneType);
        System.out.println("The maxSpeed is : " + drone2.maxSpeed);
        System.out.println("The weight is : " + drone2.weight);
        System.out.println("The hasCamera is : " + drone2.hasCamera);
        System.out.println("The cameraResolution is : " + drone2.cameraResolution);
        System.out.println("The warrantyYears is : " + drone2.warrantyYears);
        System.out.println("The flightTime is : " + drone2.flightTime);
        System.out.println("The hasGPS is : " + drone2.hasGPS);
        System.out.println("The color is : " + drone2.color);
        System.out.println("The stockQuantity is : " + drone2.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone2.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone2.isEcoFriendly);
        System.out.println("The controlType is : " + drone2.controlType);
        System.out.println("The rating is : " + drone2.rating);
        System.out.println("The maxRange is : " + drone2.maxRange);
        System.out.println("The isCertified is : " + drone2.isCertified);
        System.out.println("The countryOfOrigin is : " + drone2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone2.manufacturingYear);
        System.out.println("The propellerSize is : " + drone2.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone2.supportsMobileApp);
        System.out.println("The certificationType is : " + drone2.certificationType);


        Drone drone3 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone3.droneBrand);
        System.out.println("The droneId is : " + drone3.droneId);
        System.out.println("The dronePrice is : " + drone3.dronePrice);
        System.out.println("The isAvailable is : " + drone3.isAvailable);
        System.out.println("The droneType is : " + drone3.droneType);
        System.out.println("The maxSpeed is : " + drone3.maxSpeed);
        System.out.println("The weight is : " + drone3.weight);
        System.out.println("The hasCamera is : " + drone3.hasCamera);
        System.out.println("The cameraResolution is : " + drone3.cameraResolution);
        System.out.println("The warrantyYears is : " + drone3.warrantyYears);
        System.out.println("The flightTime is : " + drone3.flightTime);
        System.out.println("The hasGPS is : " + drone3.hasGPS);
        System.out.println("The color is : " + drone3.color);
        System.out.println("The stockQuantity is : " + drone3.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone3.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone3.isEcoFriendly);
        System.out.println("The controlType is : " + drone3.controlType);
        System.out.println("The rating is : " + drone3.rating);
        System.out.println("The maxRange is : " + drone3.maxRange);
        System.out.println("The isCertified is : " + drone3.isCertified);
        System.out.println("The countryOfOrigin is : " + drone3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone3.manufacturingYear);
        System.out.println("The propellerSize is : " + drone3.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone3.supportsMobileApp);
        System.out.println("The certificationType is : " + drone3.certificationType);

        drone3.droneBrand = "SkyTech";
        drone3.droneId = 3;
        drone3.dronePrice = 3500.99;
        drone3.isAvailable = true;
        drone3.droneType = "Quadcopter";
        drone3.maxSpeed = 60.0;
        drone3.weight = 1.4;
        drone3.hasCamera = true;
        drone3.cameraResolution = "4K";
        drone3.warrantyYears = 2;
        drone3.flightTime = 30.0;
        drone3.hasGPS = true;
        drone3.color = "Black";
        drone3.stockQuantity = 12;
        drone3.batteryCapacity = 4500.0;
        drone3.isEcoFriendly = true;
        drone3.controlType = "Remote";
        drone3.rating = 5;
        drone3.maxRange = 5000.0;
        drone3.isCertified = true;
        drone3.countryOfOrigin = "China";
        drone3.manufacturingYear = 2025;
        drone3.propellerSize = 10.0;
        drone3.supportsMobileApp = true;
        drone3.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone3.droneBrand);
        System.out.println("The droneId is : " + drone3.droneId);
        System.out.println("The dronePrice is : " + drone3.dronePrice);
        System.out.println("The isAvailable is : " + drone3.isAvailable);
        System.out.println("The droneType is : " + drone3.droneType);
        System.out.println("The maxSpeed is : " + drone3.maxSpeed);
        System.out.println("The weight is : " + drone3.weight);
        System.out.println("The hasCamera is : " + drone3.hasCamera);
        System.out.println("The cameraResolution is : " + drone3.cameraResolution);
        System.out.println("The warrantyYears is : " + drone3.warrantyYears);
        System.out.println("The flightTime is : " + drone3.flightTime);
        System.out.println("The hasGPS is : " + drone3.hasGPS);
        System.out.println("The color is : " + drone3.color);
        System.out.println("The stockQuantity is : " + drone3.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone3.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone3.isEcoFriendly);
        System.out.println("The controlType is : " + drone3.controlType);
        System.out.println("The rating is : " + drone3.rating);
        System.out.println("The maxRange is : " + drone3.maxRange);
        System.out.println("The isCertified is : " + drone3.isCertified);
        System.out.println("The countryOfOrigin is : " + drone3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone3.manufacturingYear);
        System.out.println("The propellerSize is : " + drone3.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone3.supportsMobileApp);
        System.out.println("The certificationType is : " + drone3.certificationType);


        Drone drone4 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone4.droneBrand);
        System.out.println("The droneId is : " + drone4.droneId);
        System.out.println("The dronePrice is : " + drone4.dronePrice);
        System.out.println("The isAvailable is : " + drone4.isAvailable);
        System.out.println("The droneType is : " + drone4.droneType);
        System.out.println("The maxSpeed is : " + drone4.maxSpeed);
        System.out.println("The weight is : " + drone4.weight);
        System.out.println("The hasCamera is : " + drone4.hasCamera);
        System.out.println("The cameraResolution is : " + drone4.cameraResolution);
        System.out.println("The warrantyYears is : " + drone4.warrantyYears);
        System.out.println("The flightTime is : " + drone4.flightTime);
        System.out.println("The hasGPS is : " + drone4.hasGPS);
        System.out.println("The color is : " + drone4.color);
        System.out.println("The stockQuantity is : " + drone4.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone4.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone4.isEcoFriendly);
        System.out.println("The controlType is : " + drone4.controlType);
        System.out.println("The rating is : " + drone4.rating);
        System.out.println("The maxRange is : " + drone4.maxRange);
        System.out.println("The isCertified is : " + drone4.isCertified);
        System.out.println("The countryOfOrigin is : " + drone4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone4.manufacturingYear);
        System.out.println("The propellerSize is : " + drone4.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone4.supportsMobileApp);
        System.out.println("The certificationType is : " + drone4.certificationType);

        drone4.droneBrand = "SkyTech";
        drone4.droneId = 4;
        drone4.dronePrice = 4500.99;
        drone4.isAvailable = true;
        drone4.droneType = "Quadcopter";
        drone4.maxSpeed = 60.0;
        drone4.weight = 1.4;
        drone4.hasCamera = true;
        drone4.cameraResolution = "4K";
        drone4.warrantyYears = 2;
        drone4.flightTime = 30.0;
        drone4.hasGPS = true;
        drone4.color = "Black";
        drone4.stockQuantity = 12;
        drone4.batteryCapacity = 4500.0;
        drone4.isEcoFriendly = true;
        drone4.controlType = "Remote";
        drone4.rating = 5;
        drone4.maxRange = 5000.0;
        drone4.isCertified = true;
        drone4.countryOfOrigin = "China";
        drone4.manufacturingYear = 2025;
        drone4.propellerSize = 10.0;
        drone4.supportsMobileApp = true;
        drone4.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone4.droneBrand);
        System.out.println("The droneId is : " + drone4.droneId);
        System.out.println("The dronePrice is : " + drone4.dronePrice);
        System.out.println("The isAvailable is : " + drone4.isAvailable);
        System.out.println("The droneType is : " + drone4.droneType);
        System.out.println("The maxSpeed is : " + drone4.maxSpeed);
        System.out.println("The weight is : " + drone4.weight);
        System.out.println("The hasCamera is : " + drone4.hasCamera);
        System.out.println("The cameraResolution is : " + drone4.cameraResolution);
        System.out.println("The warrantyYears is : " + drone4.warrantyYears);
        System.out.println("The flightTime is : " + drone4.flightTime);
        System.out.println("The hasGPS is : " + drone4.hasGPS);
        System.out.println("The color is : " + drone4.color);
        System.out.println("The stockQuantity is : " + drone4.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone4.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone4.isEcoFriendly);
        System.out.println("The controlType is : " + drone4.controlType);
        System.out.println("The rating is : " + drone4.rating);
        System.out.println("The maxRange is : " + drone4.maxRange);
        System.out.println("The isCertified is : " + drone4.isCertified);
        System.out.println("The countryOfOrigin is : " + drone4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone4.manufacturingYear);
        System.out.println("The propellerSize is : " + drone4.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone4.supportsMobileApp);
        System.out.println("The certificationType is : " + drone4.certificationType);


        Drone drone5 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone5.droneBrand);
        System.out.println("The droneId is : " + drone5.droneId);
        System.out.println("The dronePrice is : " + drone5.dronePrice);
        System.out.println("The isAvailable is : " + drone5.isAvailable);
        System.out.println("The droneType is : " + drone5.droneType);
        System.out.println("The maxSpeed is : " + drone5.maxSpeed);
        System.out.println("The weight is : " + drone5.weight);
        System.out.println("The hasCamera is : " + drone5.hasCamera);
        System.out.println("The cameraResolution is : " + drone5.cameraResolution);
        System.out.println("The warrantyYears is : " + drone5.warrantyYears);
        System.out.println("The flightTime is : " + drone5.flightTime);
        System.out.println("The hasGPS is : " + drone5.hasGPS);
        System.out.println("The color is : " + drone5.color);
        System.out.println("The stockQuantity is : " + drone5.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone5.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone5.isEcoFriendly);
        System.out.println("The controlType is : " + drone5.controlType);
        System.out.println("The rating is : " + drone5.rating);
        System.out.println("The maxRange is : " + drone5.maxRange);
        System.out.println("The isCertified is : " + drone5.isCertified);
        System.out.println("The countryOfOrigin is : " + drone5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone5.manufacturingYear);
        System.out.println("The propellerSize is : " + drone5.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone5.supportsMobileApp);
        System.out.println("The certificationType is : " + drone5.certificationType);

        drone5.droneBrand = "SkyTech";
        drone5.droneId = 5;
        drone5.dronePrice = 5500.99;
        drone5.isAvailable = true;
        drone5.droneType = "Quadcopter";
        drone5.maxSpeed = 60.0;
        drone5.weight = 1.4;
        drone5.hasCamera = true;
        drone5.cameraResolution = "4K";
        drone5.warrantyYears = 2;
        drone5.flightTime = 30.0;
        drone5.hasGPS = true;
        drone5.color = "Black";
        drone5.stockQuantity = 12;
        drone5.batteryCapacity = 4500.0;
        drone5.isEcoFriendly = true;
        drone5.controlType = "Remote";
        drone5.rating = 5;
        drone5.maxRange = 5000.0;
        drone5.isCertified = true;
        drone5.countryOfOrigin = "China";
        drone5.manufacturingYear = 2025;
        drone5.propellerSize = 10.0;
        drone5.supportsMobileApp = true;
        drone5.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone5.droneBrand);
        System.out.println("The droneId is : " + drone5.droneId);
        System.out.println("The dronePrice is : " + drone5.dronePrice);
        System.out.println("The isAvailable is : " + drone5.isAvailable);
        System.out.println("The droneType is : " + drone5.droneType);
        System.out.println("The maxSpeed is : " + drone5.maxSpeed);
        System.out.println("The weight is : " + drone5.weight);
        System.out.println("The hasCamera is : " + drone5.hasCamera);
        System.out.println("The cameraResolution is : " + drone5.cameraResolution);
        System.out.println("The warrantyYears is : " + drone5.warrantyYears);
        System.out.println("The flightTime is : " + drone5.flightTime);
        System.out.println("The hasGPS is : " + drone5.hasGPS);
        System.out.println("The color is : " + drone5.color);
        System.out.println("The stockQuantity is : " + drone5.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone5.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone5.isEcoFriendly);
        System.out.println("The controlType is : " + drone5.controlType);
        System.out.println("The rating is : " + drone5.rating);
        System.out.println("The maxRange is : " + drone5.maxRange);
        System.out.println("The isCertified is : " + drone5.isCertified);
        System.out.println("The countryOfOrigin is : " + drone5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone5.manufacturingYear);
        System.out.println("The propellerSize is : " + drone5.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone5.supportsMobileApp);
        System.out.println("The certificationType is : " + drone5.certificationType);


        Drone drone6 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone6.droneBrand);
        System.out.println("The droneId is : " + drone6.droneId);
        System.out.println("The dronePrice is : " + drone6.dronePrice);
        System.out.println("The isAvailable is : " + drone6.isAvailable);
        System.out.println("The droneType is : " + drone6.droneType);
        System.out.println("The maxSpeed is : " + drone6.maxSpeed);
        System.out.println("The weight is : " + drone6.weight);
        System.out.println("The hasCamera is : " + drone6.hasCamera);
        System.out.println("The cameraResolution is : " + drone6.cameraResolution);
        System.out.println("The warrantyYears is : " + drone6.warrantyYears);
        System.out.println("The flightTime is : " + drone6.flightTime);
        System.out.println("The hasGPS is : " + drone6.hasGPS);
        System.out.println("The color is : " + drone6.color);
        System.out.println("The stockQuantity is : " + drone6.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone6.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone6.isEcoFriendly);
        System.out.println("The controlType is : " + drone6.controlType);
        System.out.println("The rating is : " + drone6.rating);
        System.out.println("The maxRange is : " + drone6.maxRange);
        System.out.println("The isCertified is : " + drone6.isCertified);
        System.out.println("The countryOfOrigin is : " + drone6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone6.manufacturingYear);
        System.out.println("The propellerSize is : " + drone6.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone6.supportsMobileApp);
        System.out.println("The certificationType is : " + drone6.certificationType);

        drone6.droneBrand = "SkyTech";
        drone6.droneId = 6;
        drone6.dronePrice = 6500.99;
        drone6.isAvailable = true;
        drone6.droneType = "Quadcopter";
        drone6.maxSpeed = 60.0;
        drone6.weight = 1.4;
        drone6.hasCamera = true;
        drone6.cameraResolution = "4K";
        drone6.warrantyYears = 2;
        drone6.flightTime = 30.0;
        drone6.hasGPS = true;
        drone6.color = "Black";
        drone6.stockQuantity = 12;
        drone6.batteryCapacity = 4500.0;
        drone6.isEcoFriendly = true;
        drone6.controlType = "Remote";
        drone6.rating = 5;
        drone6.maxRange = 5000.0;
        drone6.isCertified = true;
        drone6.countryOfOrigin = "China";
        drone6.manufacturingYear = 2025;
        drone6.propellerSize = 10.0;
        drone6.supportsMobileApp = true;
        drone6.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone6.droneBrand);
        System.out.println("The droneId is : " + drone6.droneId);
        System.out.println("The dronePrice is : " + drone6.dronePrice);
        System.out.println("The isAvailable is : " + drone6.isAvailable);
        System.out.println("The droneType is : " + drone6.droneType);
        System.out.println("The maxSpeed is : " + drone6.maxSpeed);
        System.out.println("The weight is : " + drone6.weight);
        System.out.println("The hasCamera is : " + drone6.hasCamera);
        System.out.println("The cameraResolution is : " + drone6.cameraResolution);
        System.out.println("The warrantyYears is : " + drone6.warrantyYears);
        System.out.println("The flightTime is : " + drone6.flightTime);
        System.out.println("The hasGPS is : " + drone6.hasGPS);
        System.out.println("The color is : " + drone6.color);
        System.out.println("The stockQuantity is : " + drone6.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone6.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone6.isEcoFriendly);
        System.out.println("The controlType is : " + drone6.controlType);
        System.out.println("The rating is : " + drone6.rating);
        System.out.println("The maxRange is : " + drone6.maxRange);
        System.out.println("The isCertified is : " + drone6.isCertified);
        System.out.println("The countryOfOrigin is : " + drone6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone6.manufacturingYear);
        System.out.println("The propellerSize is : " + drone6.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone6.supportsMobileApp);
        System.out.println("The certificationType is : " + drone6.certificationType);


        Drone drone7 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone7.droneBrand);
        System.out.println("The droneId is : " + drone7.droneId);
        System.out.println("The dronePrice is : " + drone7.dronePrice);
        System.out.println("The isAvailable is : " + drone7.isAvailable);
        System.out.println("The droneType is : " + drone7.droneType);
        System.out.println("The maxSpeed is : " + drone7.maxSpeed);
        System.out.println("The weight is : " + drone7.weight);
        System.out.println("The hasCamera is : " + drone7.hasCamera);
        System.out.println("The cameraResolution is : " + drone7.cameraResolution);
        System.out.println("The warrantyYears is : " + drone7.warrantyYears);
        System.out.println("The flightTime is : " + drone7.flightTime);
        System.out.println("The hasGPS is : " + drone7.hasGPS);
        System.out.println("The color is : " + drone7.color);
        System.out.println("The stockQuantity is : " + drone7.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone7.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone7.isEcoFriendly);
        System.out.println("The controlType is : " + drone7.controlType);
        System.out.println("The rating is : " + drone7.rating);
        System.out.println("The maxRange is : " + drone7.maxRange);
        System.out.println("The isCertified is : " + drone7.isCertified);
        System.out.println("The countryOfOrigin is : " + drone7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone7.manufacturingYear);
        System.out.println("The propellerSize is : " + drone7.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone7.supportsMobileApp);
        System.out.println("The certificationType is : " + drone7.certificationType);

        drone7.droneBrand = "SkyTech";
        drone7.droneId = 7;
        drone7.dronePrice = 7500.99;
        drone7.isAvailable = true;
        drone7.droneType = "Quadcopter";
        drone7.maxSpeed = 60.0;
        drone7.weight = 1.4;
        drone7.hasCamera = true;
        drone7.cameraResolution = "4K";
        drone7.warrantyYears = 2;
        drone7.flightTime = 30.0;
        drone7.hasGPS = true;
        drone7.color = "Black";
        drone7.stockQuantity = 12;
        drone7.batteryCapacity = 4500.0;
        drone7.isEcoFriendly = true;
        drone7.controlType = "Remote";
        drone7.rating = 5;
        drone7.maxRange = 5000.0;
        drone7.isCertified = true;
        drone7.countryOfOrigin = "China";
        drone7.manufacturingYear = 2025;
        drone7.propellerSize = 10.0;
        drone7.supportsMobileApp = true;
        drone7.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone7.droneBrand);
        System.out.println("The droneId is : " + drone7.droneId);
        System.out.println("The dronePrice is : " + drone7.dronePrice);
        System.out.println("The isAvailable is : " + drone7.isAvailable);
        System.out.println("The droneType is : " + drone7.droneType);
        System.out.println("The maxSpeed is : " + drone7.maxSpeed);
        System.out.println("The weight is : " + drone7.weight);
        System.out.println("The hasCamera is : " + drone7.hasCamera);
        System.out.println("The cameraResolution is : " + drone7.cameraResolution);
        System.out.println("The warrantyYears is : " + drone7.warrantyYears);
        System.out.println("The flightTime is : " + drone7.flightTime);
        System.out.println("The hasGPS is : " + drone7.hasGPS);
        System.out.println("The color is : " + drone7.color);
        System.out.println("The stockQuantity is : " + drone7.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone7.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone7.isEcoFriendly);
        System.out.println("The controlType is : " + drone7.controlType);
        System.out.println("The rating is : " + drone7.rating);
        System.out.println("The maxRange is : " + drone7.maxRange);
        System.out.println("The isCertified is : " + drone7.isCertified);
        System.out.println("The countryOfOrigin is : " + drone7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone7.manufacturingYear);
        System.out.println("The propellerSize is : " + drone7.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone7.supportsMobileApp);
        System.out.println("The certificationType is : " + drone7.certificationType);


        Drone drone8 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone8.droneBrand);
        System.out.println("The droneId is : " + drone8.droneId);
        System.out.println("The dronePrice is : " + drone8.dronePrice);
        System.out.println("The isAvailable is : " + drone8.isAvailable);
        System.out.println("The droneType is : " + drone8.droneType);
        System.out.println("The maxSpeed is : " + drone8.maxSpeed);
        System.out.println("The weight is : " + drone8.weight);
        System.out.println("The hasCamera is : " + drone8.hasCamera);
        System.out.println("The cameraResolution is : " + drone8.cameraResolution);
        System.out.println("The warrantyYears is : " + drone8.warrantyYears);
        System.out.println("The flightTime is : " + drone8.flightTime);
        System.out.println("The hasGPS is : " + drone8.hasGPS);
        System.out.println("The color is : " + drone8.color);
        System.out.println("The stockQuantity is : " + drone8.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone8.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone8.isEcoFriendly);
        System.out.println("The controlType is : " + drone8.controlType);
        System.out.println("The rating is : " + drone8.rating);
        System.out.println("The maxRange is : " + drone8.maxRange);
        System.out.println("The isCertified is : " + drone8.isCertified);
        System.out.println("The countryOfOrigin is : " + drone8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone8.manufacturingYear);
        System.out.println("The propellerSize is : " + drone8.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone8.supportsMobileApp);
        System.out.println("The certificationType is : " + drone8.certificationType);

        drone8.droneBrand = "SkyTech";
        drone8.droneId = 8;
        drone8.dronePrice = 8500.99;
        drone8.isAvailable = true;
        drone8.droneType = "Quadcopter";
        drone8.maxSpeed = 60.0;
        drone8.weight = 1.4;
        drone8.hasCamera = true;
        drone8.cameraResolution = "4K";
        drone8.warrantyYears = 2;
        drone8.flightTime = 30.0;
        drone8.hasGPS = true;
        drone8.color = "Black";
        drone8.stockQuantity = 12;
        drone8.batteryCapacity = 4500.0;
        drone8.isEcoFriendly = true;
        drone8.controlType = "Remote";
        drone8.rating = 5;
        drone8.maxRange = 5000.0;
        drone8.isCertified = true;
        drone8.countryOfOrigin = "China";
        drone8.manufacturingYear = 2025;
        drone8.propellerSize = 10.0;
        drone8.supportsMobileApp = true;
        drone8.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone8.droneBrand);
        System.out.println("The droneId is : " + drone8.droneId);
        System.out.println("The dronePrice is : " + drone8.dronePrice);
        System.out.println("The isAvailable is : " + drone8.isAvailable);
        System.out.println("The droneType is : " + drone8.droneType);
        System.out.println("The maxSpeed is : " + drone8.maxSpeed);
        System.out.println("The weight is : " + drone8.weight);
        System.out.println("The hasCamera is : " + drone8.hasCamera);
        System.out.println("The cameraResolution is : " + drone8.cameraResolution);
        System.out.println("The warrantyYears is : " + drone8.warrantyYears);
        System.out.println("The flightTime is : " + drone8.flightTime);
        System.out.println("The hasGPS is : " + drone8.hasGPS);
        System.out.println("The color is : " + drone8.color);
        System.out.println("The stockQuantity is : " + drone8.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone8.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone8.isEcoFriendly);
        System.out.println("The controlType is : " + drone8.controlType);
        System.out.println("The rating is : " + drone8.rating);
        System.out.println("The maxRange is : " + drone8.maxRange);
        System.out.println("The isCertified is : " + drone8.isCertified);
        System.out.println("The countryOfOrigin is : " + drone8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone8.manufacturingYear);
        System.out.println("The propellerSize is : " + drone8.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone8.supportsMobileApp);
        System.out.println("The certificationType is : " + drone8.certificationType);


        Drone drone9 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone9.droneBrand);
        System.out.println("The droneId is : " + drone9.droneId);
        System.out.println("The dronePrice is : " + drone9.dronePrice);
        System.out.println("The isAvailable is : " + drone9.isAvailable);
        System.out.println("The droneType is : " + drone9.droneType);
        System.out.println("The maxSpeed is : " + drone9.maxSpeed);
        System.out.println("The weight is : " + drone9.weight);
        System.out.println("The hasCamera is : " + drone9.hasCamera);
        System.out.println("The cameraResolution is : " + drone9.cameraResolution);
        System.out.println("The warrantyYears is : " + drone9.warrantyYears);
        System.out.println("The flightTime is : " + drone9.flightTime);
        System.out.println("The hasGPS is : " + drone9.hasGPS);
        System.out.println("The color is : " + drone9.color);
        System.out.println("The stockQuantity is : " + drone9.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone9.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone9.isEcoFriendly);
        System.out.println("The controlType is : " + drone9.controlType);
        System.out.println("The rating is : " + drone9.rating);
        System.out.println("The maxRange is : " + drone9.maxRange);
        System.out.println("The isCertified is : " + drone9.isCertified);
        System.out.println("The countryOfOrigin is : " + drone9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone9.manufacturingYear);
        System.out.println("The propellerSize is : " + drone9.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone9.supportsMobileApp);
        System.out.println("The certificationType is : " + drone9.certificationType);

        drone9.droneBrand = "SkyTech";
        drone9.droneId = 9;
        drone9.dronePrice = 9500.99;
        drone9.isAvailable = true;
        drone9.droneType = "Quadcopter";
        drone9.maxSpeed = 60.0;
        drone9.weight = 1.4;
        drone9.hasCamera = true;
        drone9.cameraResolution = "4K";
        drone9.warrantyYears = 2;
        drone9.flightTime = 30.0;
        drone9.hasGPS = true;
        drone9.color = "Black";
        drone9.stockQuantity = 12;
        drone9.batteryCapacity = 4500.0;
        drone9.isEcoFriendly = true;
        drone9.controlType = "Remote";
        drone9.rating = 5;
        drone9.maxRange = 5000.0;
        drone9.isCertified = true;
        drone9.countryOfOrigin = "China";
        drone9.manufacturingYear = 2025;
        drone9.propellerSize = 10.0;
        drone9.supportsMobileApp = true;
        drone9.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone9.droneBrand);
        System.out.println("The droneId is : " + drone9.droneId);
        System.out.println("The dronePrice is : " + drone9.dronePrice);
        System.out.println("The isAvailable is : " + drone9.isAvailable);
        System.out.println("The droneType is : " + drone9.droneType);
        System.out.println("The maxSpeed is : " + drone9.maxSpeed);
        System.out.println("The weight is : " + drone9.weight);
        System.out.println("The hasCamera is : " + drone9.hasCamera);
        System.out.println("The cameraResolution is : " + drone9.cameraResolution);
        System.out.println("The warrantyYears is : " + drone9.warrantyYears);
        System.out.println("The flightTime is : " + drone9.flightTime);
        System.out.println("The hasGPS is : " + drone9.hasGPS);
        System.out.println("The color is : " + drone9.color);
        System.out.println("The stockQuantity is : " + drone9.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone9.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone9.isEcoFriendly);
        System.out.println("The controlType is : " + drone9.controlType);
        System.out.println("The rating is : " + drone9.rating);
        System.out.println("The maxRange is : " + drone9.maxRange);
        System.out.println("The isCertified is : " + drone9.isCertified);
        System.out.println("The countryOfOrigin is : " + drone9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone9.manufacturingYear);
        System.out.println("The propellerSize is : " + drone9.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone9.supportsMobileApp);
        System.out.println("The certificationType is : " + drone9.certificationType);


        Drone drone10 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone10.droneBrand);
        System.out.println("The droneId is : " + drone10.droneId);
        System.out.println("The dronePrice is : " + drone10.dronePrice);
        System.out.println("The isAvailable is : " + drone10.isAvailable);
        System.out.println("The droneType is : " + drone10.droneType);
        System.out.println("The maxSpeed is : " + drone10.maxSpeed);
        System.out.println("The weight is : " + drone10.weight);
        System.out.println("The hasCamera is : " + drone10.hasCamera);
        System.out.println("The cameraResolution is : " + drone10.cameraResolution);
        System.out.println("The warrantyYears is : " + drone10.warrantyYears);
        System.out.println("The flightTime is : " + drone10.flightTime);
        System.out.println("The hasGPS is : " + drone10.hasGPS);
        System.out.println("The color is : " + drone10.color);
        System.out.println("The stockQuantity is : " + drone10.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone10.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone10.isEcoFriendly);
        System.out.println("The controlType is : " + drone10.controlType);
        System.out.println("The rating is : " + drone10.rating);
        System.out.println("The maxRange is : " + drone10.maxRange);
        System.out.println("The isCertified is : " + drone10.isCertified);
        System.out.println("The countryOfOrigin is : " + drone10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone10.manufacturingYear);
        System.out.println("The propellerSize is : " + drone10.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone10.supportsMobileApp);
        System.out.println("The certificationType is : " + drone10.certificationType);

        drone10.droneBrand = "SkyTech";
        drone10.droneId = 10;
        drone10.dronePrice = 10500.99;
        drone10.isAvailable = true;
        drone10.droneType = "Quadcopter";
        drone10.maxSpeed = 60.0;
        drone10.weight = 1.4;
        drone10.hasCamera = true;
        drone10.cameraResolution = "4K";
        drone10.warrantyYears = 2;
        drone10.flightTime = 30.0;
        drone10.hasGPS = true;
        drone10.color = "Black";
        drone10.stockQuantity = 12;
        drone10.batteryCapacity = 4500.0;
        drone10.isEcoFriendly = true;
        drone10.controlType = "Remote";
        drone10.rating = 5;
        drone10.maxRange = 5000.0;
        drone10.isCertified = true;
        drone10.countryOfOrigin = "China";
        drone10.manufacturingYear = 2025;
        drone10.propellerSize = 10.0;
        drone10.supportsMobileApp = true;
        drone10.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone10.droneBrand);
        System.out.println("The droneId is : " + drone10.droneId);
        System.out.println("The dronePrice is : " + drone10.dronePrice);
        System.out.println("The isAvailable is : " + drone10.isAvailable);
        System.out.println("The droneType is : " + drone10.droneType);
        System.out.println("The maxSpeed is : " + drone10.maxSpeed);
        System.out.println("The weight is : " + drone10.weight);
        System.out.println("The hasCamera is : " + drone10.hasCamera);
        System.out.println("The cameraResolution is : " + drone10.cameraResolution);
        System.out.println("The warrantyYears is : " + drone10.warrantyYears);
        System.out.println("The flightTime is : " + drone10.flightTime);
        System.out.println("The hasGPS is : " + drone10.hasGPS);
        System.out.println("The color is : " + drone10.color);
        System.out.println("The stockQuantity is : " + drone10.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone10.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone10.isEcoFriendly);
        System.out.println("The controlType is : " + drone10.controlType);
        System.out.println("The rating is : " + drone10.rating);
        System.out.println("The maxRange is : " + drone10.maxRange);
        System.out.println("The isCertified is : " + drone10.isCertified);
        System.out.println("The countryOfOrigin is : " + drone10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone10.manufacturingYear);
        System.out.println("The propellerSize is : " + drone10.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone10.supportsMobileApp);
        System.out.println("The certificationType is : " + drone10.certificationType);


        Drone drone11 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone11.droneBrand);
        System.out.println("The droneId is : " + drone11.droneId);
        System.out.println("The dronePrice is : " + drone11.dronePrice);
        System.out.println("The isAvailable is : " + drone11.isAvailable);
        System.out.println("The droneType is : " + drone11.droneType);
        System.out.println("The maxSpeed is : " + drone11.maxSpeed);
        System.out.println("The weight is : " + drone11.weight);
        System.out.println("The hasCamera is : " + drone11.hasCamera);
        System.out.println("The cameraResolution is : " + drone11.cameraResolution);
        System.out.println("The warrantyYears is : " + drone11.warrantyYears);
        System.out.println("The flightTime is : " + drone11.flightTime);
        System.out.println("The hasGPS is : " + drone11.hasGPS);
        System.out.println("The color is : " + drone11.color);
        System.out.println("The stockQuantity is : " + drone11.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone11.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone11.isEcoFriendly);
        System.out.println("The controlType is : " + drone11.controlType);
        System.out.println("The rating is : " + drone11.rating);
        System.out.println("The maxRange is : " + drone11.maxRange);
        System.out.println("The isCertified is : " + drone11.isCertified);
        System.out.println("The countryOfOrigin is : " + drone11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone11.manufacturingYear);
        System.out.println("The propellerSize is : " + drone11.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone11.supportsMobileApp);
        System.out.println("The certificationType is : " + drone11.certificationType);

        drone11.droneBrand = "SkyTech";
        drone11.droneId = 11;
        drone11.dronePrice = 11500.99;
        drone11.isAvailable = true;
        drone11.droneType = "Quadcopter";
        drone11.maxSpeed = 60.0;
        drone11.weight = 1.4;
        drone11.hasCamera = true;
        drone11.cameraResolution = "4K";
        drone11.warrantyYears = 2;
        drone11.flightTime = 30.0;
        drone11.hasGPS = true;
        drone11.color = "Black";
        drone11.stockQuantity = 12;
        drone11.batteryCapacity = 4500.0;
        drone11.isEcoFriendly = true;
        drone11.controlType = "Remote";
        drone11.rating = 5;
        drone11.maxRange = 5000.0;
        drone11.isCertified = true;
        drone11.countryOfOrigin = "China";
        drone11.manufacturingYear = 2025;
        drone11.propellerSize = 10.0;
        drone11.supportsMobileApp = true;
        drone11.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone11.droneBrand);
        System.out.println("The droneId is : " + drone11.droneId);
        System.out.println("The dronePrice is : " + drone11.dronePrice);
        System.out.println("The isAvailable is : " + drone11.isAvailable);
        System.out.println("The droneType is : " + drone11.droneType);
        System.out.println("The maxSpeed is : " + drone11.maxSpeed);
        System.out.println("The weight is : " + drone11.weight);
        System.out.println("The hasCamera is : " + drone11.hasCamera);
        System.out.println("The cameraResolution is : " + drone11.cameraResolution);
        System.out.println("The warrantyYears is : " + drone11.warrantyYears);
        System.out.println("The flightTime is : " + drone11.flightTime);
        System.out.println("The hasGPS is : " + drone11.hasGPS);
        System.out.println("The color is : " + drone11.color);
        System.out.println("The stockQuantity is : " + drone11.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone11.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone11.isEcoFriendly);
        System.out.println("The controlType is : " + drone11.controlType);
        System.out.println("The rating is : " + drone11.rating);
        System.out.println("The maxRange is : " + drone11.maxRange);
        System.out.println("The isCertified is : " + drone11.isCertified);
        System.out.println("The countryOfOrigin is : " + drone11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone11.manufacturingYear);
        System.out.println("The propellerSize is : " + drone11.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone11.supportsMobileApp);
        System.out.println("The certificationType is : " + drone11.certificationType);


        Drone drone12 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone12.droneBrand);
        System.out.println("The droneId is : " + drone12.droneId);
        System.out.println("The dronePrice is : " + drone12.dronePrice);
        System.out.println("The isAvailable is : " + drone12.isAvailable);
        System.out.println("The droneType is : " + drone12.droneType);
        System.out.println("The maxSpeed is : " + drone12.maxSpeed);
        System.out.println("The weight is : " + drone12.weight);
        System.out.println("The hasCamera is : " + drone12.hasCamera);
        System.out.println("The cameraResolution is : " + drone12.cameraResolution);
        System.out.println("The warrantyYears is : " + drone12.warrantyYears);
        System.out.println("The flightTime is : " + drone12.flightTime);
        System.out.println("The hasGPS is : " + drone12.hasGPS);
        System.out.println("The color is : " + drone12.color);
        System.out.println("The stockQuantity is : " + drone12.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone12.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone12.isEcoFriendly);
        System.out.println("The controlType is : " + drone12.controlType);
        System.out.println("The rating is : " + drone12.rating);
        System.out.println("The maxRange is : " + drone12.maxRange);
        System.out.println("The isCertified is : " + drone12.isCertified);
        System.out.println("The countryOfOrigin is : " + drone12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone12.manufacturingYear);
        System.out.println("The propellerSize is : " + drone12.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone12.supportsMobileApp);
        System.out.println("The certificationType is : " + drone12.certificationType);

        drone12.droneBrand = "SkyTech";
        drone12.droneId = 12;
        drone12.dronePrice = 12500.99;
        drone12.isAvailable = true;
        drone12.droneType = "Quadcopter";
        drone12.maxSpeed = 60.0;
        drone12.weight = 1.4;
        drone12.hasCamera = true;
        drone12.cameraResolution = "4K";
        drone12.warrantyYears = 2;
        drone12.flightTime = 30.0;
        drone12.hasGPS = true;
        drone12.color = "Black";
        drone12.stockQuantity = 12;
        drone12.batteryCapacity = 4500.0;
        drone12.isEcoFriendly = true;
        drone12.controlType = "Remote";
        drone12.rating = 5;
        drone12.maxRange = 5000.0;
        drone12.isCertified = true;
        drone12.countryOfOrigin = "China";
        drone12.manufacturingYear = 2025;
        drone12.propellerSize = 10.0;
        drone12.supportsMobileApp = true;
        drone12.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone12.droneBrand);
        System.out.println("The droneId is : " + drone12.droneId);
        System.out.println("The dronePrice is : " + drone12.dronePrice);
        System.out.println("The isAvailable is : " + drone12.isAvailable);
        System.out.println("The droneType is : " + drone12.droneType);
        System.out.println("The maxSpeed is : " + drone12.maxSpeed);
        System.out.println("The weight is : " + drone12.weight);
        System.out.println("The hasCamera is : " + drone12.hasCamera);
        System.out.println("The cameraResolution is : " + drone12.cameraResolution);
        System.out.println("The warrantyYears is : " + drone12.warrantyYears);
        System.out.println("The flightTime is : " + drone12.flightTime);
        System.out.println("The hasGPS is : " + drone12.hasGPS);
        System.out.println("The color is : " + drone12.color);
        System.out.println("The stockQuantity is : " + drone12.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone12.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone12.isEcoFriendly);
        System.out.println("The controlType is : " + drone12.controlType);
        System.out.println("The rating is : " + drone12.rating);
        System.out.println("The maxRange is : " + drone12.maxRange);
        System.out.println("The isCertified is : " + drone12.isCertified);
        System.out.println("The countryOfOrigin is : " + drone12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone12.manufacturingYear);
        System.out.println("The propellerSize is : " + drone12.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone12.supportsMobileApp);
        System.out.println("The certificationType is : " + drone12.certificationType);


        Drone drone13 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone13.droneBrand);
        System.out.println("The droneId is : " + drone13.droneId);
        System.out.println("The dronePrice is : " + drone13.dronePrice);
        System.out.println("The isAvailable is : " + drone13.isAvailable);
        System.out.println("The droneType is : " + drone13.droneType);
        System.out.println("The maxSpeed is : " + drone13.maxSpeed);
        System.out.println("The weight is : " + drone13.weight);
        System.out.println("The hasCamera is : " + drone13.hasCamera);
        System.out.println("The cameraResolution is : " + drone13.cameraResolution);
        System.out.println("The warrantyYears is : " + drone13.warrantyYears);
        System.out.println("The flightTime is : " + drone13.flightTime);
        System.out.println("The hasGPS is : " + drone13.hasGPS);
        System.out.println("The color is : " + drone13.color);
        System.out.println("The stockQuantity is : " + drone13.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone13.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone13.isEcoFriendly);
        System.out.println("The controlType is : " + drone13.controlType);
        System.out.println("The rating is : " + drone13.rating);
        System.out.println("The maxRange is : " + drone13.maxRange);
        System.out.println("The isCertified is : " + drone13.isCertified);
        System.out.println("The countryOfOrigin is : " + drone13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone13.manufacturingYear);
        System.out.println("The propellerSize is : " + drone13.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone13.supportsMobileApp);
        System.out.println("The certificationType is : " + drone13.certificationType);

        drone13.droneBrand = "SkyTech";
        drone13.droneId = 13;
        drone13.dronePrice = 13500.99;
        drone13.isAvailable = true;
        drone13.droneType = "Quadcopter";
        drone13.maxSpeed = 60.0;
        drone13.weight = 1.4;
        drone13.hasCamera = true;
        drone13.cameraResolution = "4K";
        drone13.warrantyYears = 2;
        drone13.flightTime = 30.0;
        drone13.hasGPS = true;
        drone13.color = "Black";
        drone13.stockQuantity = 12;
        drone13.batteryCapacity = 4500.0;
        drone13.isEcoFriendly = true;
        drone13.controlType = "Remote";
        drone13.rating = 5;
        drone13.maxRange = 5000.0;
        drone13.isCertified = true;
        drone13.countryOfOrigin = "China";
        drone13.manufacturingYear = 2025;
        drone13.propellerSize = 10.0;
        drone13.supportsMobileApp = true;
        drone13.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone13.droneBrand);
        System.out.println("The droneId is : " + drone13.droneId);
        System.out.println("The dronePrice is : " + drone13.dronePrice);
        System.out.println("The isAvailable is : " + drone13.isAvailable);
        System.out.println("The droneType is : " + drone13.droneType);
        System.out.println("The maxSpeed is : " + drone13.maxSpeed);
        System.out.println("The weight is : " + drone13.weight);
        System.out.println("The hasCamera is : " + drone13.hasCamera);
        System.out.println("The cameraResolution is : " + drone13.cameraResolution);
        System.out.println("The warrantyYears is : " + drone13.warrantyYears);
        System.out.println("The flightTime is : " + drone13.flightTime);
        System.out.println("The hasGPS is : " + drone13.hasGPS);
        System.out.println("The color is : " + drone13.color);
        System.out.println("The stockQuantity is : " + drone13.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone13.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone13.isEcoFriendly);
        System.out.println("The controlType is : " + drone13.controlType);
        System.out.println("The rating is : " + drone13.rating);
        System.out.println("The maxRange is : " + drone13.maxRange);
        System.out.println("The isCertified is : " + drone13.isCertified);
        System.out.println("The countryOfOrigin is : " + drone13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone13.manufacturingYear);
        System.out.println("The propellerSize is : " + drone13.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone13.supportsMobileApp);
        System.out.println("The certificationType is : " + drone13.certificationType);


        Drone drone14 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone14.droneBrand);
        System.out.println("The droneId is : " + drone14.droneId);
        System.out.println("The dronePrice is : " + drone14.dronePrice);
        System.out.println("The isAvailable is : " + drone14.isAvailable);
        System.out.println("The droneType is : " + drone14.droneType);
        System.out.println("The maxSpeed is : " + drone14.maxSpeed);
        System.out.println("The weight is : " + drone14.weight);
        System.out.println("The hasCamera is : " + drone14.hasCamera);
        System.out.println("The cameraResolution is : " + drone14.cameraResolution);
        System.out.println("The warrantyYears is : " + drone14.warrantyYears);
        System.out.println("The flightTime is : " + drone14.flightTime);
        System.out.println("The hasGPS is : " + drone14.hasGPS);
        System.out.println("The color is : " + drone14.color);
        System.out.println("The stockQuantity is : " + drone14.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone14.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone14.isEcoFriendly);
        System.out.println("The controlType is : " + drone14.controlType);
        System.out.println("The rating is : " + drone14.rating);
        System.out.println("The maxRange is : " + drone14.maxRange);
        System.out.println("The isCertified is : " + drone14.isCertified);
        System.out.println("The countryOfOrigin is : " + drone14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone14.manufacturingYear);
        System.out.println("The propellerSize is : " + drone14.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone14.supportsMobileApp);
        System.out.println("The certificationType is : " + drone14.certificationType);

        drone14.droneBrand = "SkyTech";
        drone14.droneId = 14;
        drone14.dronePrice = 14500.99;
        drone14.isAvailable = true;
        drone14.droneType = "Quadcopter";
        drone14.maxSpeed = 60.0;
        drone14.weight = 1.4;
        drone14.hasCamera = true;
        drone14.cameraResolution = "4K";
        drone14.warrantyYears = 2;
        drone14.flightTime = 30.0;
        drone14.hasGPS = true;
        drone14.color = "Black";
        drone14.stockQuantity = 12;
        drone14.batteryCapacity = 4500.0;
        drone14.isEcoFriendly = true;
        drone14.controlType = "Remote";
        drone14.rating = 5;
        drone14.maxRange = 5000.0;
        drone14.isCertified = true;
        drone14.countryOfOrigin = "China";
        drone14.manufacturingYear = 2025;
        drone14.propellerSize = 10.0;
        drone14.supportsMobileApp = true;
        drone14.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone14.droneBrand);
        System.out.println("The droneId is : " + drone14.droneId);
        System.out.println("The dronePrice is : " + drone14.dronePrice);
        System.out.println("The isAvailable is : " + drone14.isAvailable);
        System.out.println("The droneType is : " + drone14.droneType);
        System.out.println("The maxSpeed is : " + drone14.maxSpeed);
        System.out.println("The weight is : " + drone14.weight);
        System.out.println("The hasCamera is : " + drone14.hasCamera);
        System.out.println("The cameraResolution is : " + drone14.cameraResolution);
        System.out.println("The warrantyYears is : " + drone14.warrantyYears);
        System.out.println("The flightTime is : " + drone14.flightTime);
        System.out.println("The hasGPS is : " + drone14.hasGPS);
        System.out.println("The color is : " + drone14.color);
        System.out.println("The stockQuantity is : " + drone14.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone14.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone14.isEcoFriendly);
        System.out.println("The controlType is : " + drone14.controlType);
        System.out.println("The rating is : " + drone14.rating);
        System.out.println("The maxRange is : " + drone14.maxRange);
        System.out.println("The isCertified is : " + drone14.isCertified);
        System.out.println("The countryOfOrigin is : " + drone14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone14.manufacturingYear);
        System.out.println("The propellerSize is : " + drone14.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone14.supportsMobileApp);
        System.out.println("The certificationType is : " + drone14.certificationType);


        Drone drone15 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone15.droneBrand);
        System.out.println("The droneId is : " + drone15.droneId);
        System.out.println("The dronePrice is : " + drone15.dronePrice);
        System.out.println("The isAvailable is : " + drone15.isAvailable);
        System.out.println("The droneType is : " + drone15.droneType);
        System.out.println("The maxSpeed is : " + drone15.maxSpeed);
        System.out.println("The weight is : " + drone15.weight);
        System.out.println("The hasCamera is : " + drone15.hasCamera);
        System.out.println("The cameraResolution is : " + drone15.cameraResolution);
        System.out.println("The warrantyYears is : " + drone15.warrantyYears);
        System.out.println("The flightTime is : " + drone15.flightTime);
        System.out.println("The hasGPS is : " + drone15.hasGPS);
        System.out.println("The color is : " + drone15.color);
        System.out.println("The stockQuantity is : " + drone15.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone15.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone15.isEcoFriendly);
        System.out.println("The controlType is : " + drone15.controlType);
        System.out.println("The rating is : " + drone15.rating);
        System.out.println("The maxRange is : " + drone15.maxRange);
        System.out.println("The isCertified is : " + drone15.isCertified);
        System.out.println("The countryOfOrigin is : " + drone15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone15.manufacturingYear);
        System.out.println("The propellerSize is : " + drone15.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone15.supportsMobileApp);
        System.out.println("The certificationType is : " + drone15.certificationType);

        drone15.droneBrand = "SkyTech";
        drone15.droneId = 15;
        drone15.dronePrice = 15500.99;
        drone15.isAvailable = true;
        drone15.droneType = "Quadcopter";
        drone15.maxSpeed = 60.0;
        drone15.weight = 1.4;
        drone15.hasCamera = true;
        drone15.cameraResolution = "4K";
        drone15.warrantyYears = 2;
        drone15.flightTime = 30.0;
        drone15.hasGPS = true;
        drone15.color = "Black";
        drone15.stockQuantity = 12;
        drone15.batteryCapacity = 4500.0;
        drone15.isEcoFriendly = true;
        drone15.controlType = "Remote";
        drone15.rating = 5;
        drone15.maxRange = 5000.0;
        drone15.isCertified = true;
        drone15.countryOfOrigin = "China";
        drone15.manufacturingYear = 2025;
        drone15.propellerSize = 10.0;
        drone15.supportsMobileApp = true;
        drone15.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone15.droneBrand);
        System.out.println("The droneId is : " + drone15.droneId);
        System.out.println("The dronePrice is : " + drone15.dronePrice);
        System.out.println("The isAvailable is : " + drone15.isAvailable);
        System.out.println("The droneType is : " + drone15.droneType);
        System.out.println("The maxSpeed is : " + drone15.maxSpeed);
        System.out.println("The weight is : " + drone15.weight);
        System.out.println("The hasCamera is : " + drone15.hasCamera);
        System.out.println("The cameraResolution is : " + drone15.cameraResolution);
        System.out.println("The warrantyYears is : " + drone15.warrantyYears);
        System.out.println("The flightTime is : " + drone15.flightTime);
        System.out.println("The hasGPS is : " + drone15.hasGPS);
        System.out.println("The color is : " + drone15.color);
        System.out.println("The stockQuantity is : " + drone15.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone15.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone15.isEcoFriendly);
        System.out.println("The controlType is : " + drone15.controlType);
        System.out.println("The rating is : " + drone15.rating);
        System.out.println("The maxRange is : " + drone15.maxRange);
        System.out.println("The isCertified is : " + drone15.isCertified);
        System.out.println("The countryOfOrigin is : " + drone15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone15.manufacturingYear);
        System.out.println("The propellerSize is : " + drone15.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone15.supportsMobileApp);
        System.out.println("The certificationType is : " + drone15.certificationType);


        Drone drone16 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone16.droneBrand);
        System.out.println("The droneId is : " + drone16.droneId);
        System.out.println("The dronePrice is : " + drone16.dronePrice);
        System.out.println("The isAvailable is : " + drone16.isAvailable);
        System.out.println("The droneType is : " + drone16.droneType);
        System.out.println("The maxSpeed is : " + drone16.maxSpeed);
        System.out.println("The weight is : " + drone16.weight);
        System.out.println("The hasCamera is : " + drone16.hasCamera);
        System.out.println("The cameraResolution is : " + drone16.cameraResolution);
        System.out.println("The warrantyYears is : " + drone16.warrantyYears);
        System.out.println("The flightTime is : " + drone16.flightTime);
        System.out.println("The hasGPS is : " + drone16.hasGPS);
        System.out.println("The color is : " + drone16.color);
        System.out.println("The stockQuantity is : " + drone16.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone16.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone16.isEcoFriendly);
        System.out.println("The controlType is : " + drone16.controlType);
        System.out.println("The rating is : " + drone16.rating);
        System.out.println("The maxRange is : " + drone16.maxRange);
        System.out.println("The isCertified is : " + drone16.isCertified);
        System.out.println("The countryOfOrigin is : " + drone16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone16.manufacturingYear);
        System.out.println("The propellerSize is : " + drone16.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone16.supportsMobileApp);
        System.out.println("The certificationType is : " + drone16.certificationType);

        drone16.droneBrand = "SkyTech";
        drone16.droneId = 16;
        drone16.dronePrice = 16500.99;
        drone16.isAvailable = true;
        drone16.droneType = "Quadcopter";
        drone16.maxSpeed = 60.0;
        drone16.weight = 1.4;
        drone16.hasCamera = true;
        drone16.cameraResolution = "4K";
        drone16.warrantyYears = 2;
        drone16.flightTime = 30.0;
        drone16.hasGPS = true;
        drone16.color = "Black";
        drone16.stockQuantity = 12;
        drone16.batteryCapacity = 4500.0;
        drone16.isEcoFriendly = true;
        drone16.controlType = "Remote";
        drone16.rating = 5;
        drone16.maxRange = 5000.0;
        drone16.isCertified = true;
        drone16.countryOfOrigin = "China";
        drone16.manufacturingYear = 2025;
        drone16.propellerSize = 10.0;
        drone16.supportsMobileApp = true;
        drone16.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone16.droneBrand);
        System.out.println("The droneId is : " + drone16.droneId);
        System.out.println("The dronePrice is : " + drone16.dronePrice);
        System.out.println("The isAvailable is : " + drone16.isAvailable);
        System.out.println("The droneType is : " + drone16.droneType);
        System.out.println("The maxSpeed is : " + drone16.maxSpeed);
        System.out.println("The weight is : " + drone16.weight);
        System.out.println("The hasCamera is : " + drone16.hasCamera);
        System.out.println("The cameraResolution is : " + drone16.cameraResolution);
        System.out.println("The warrantyYears is : " + drone16.warrantyYears);
        System.out.println("The flightTime is : " + drone16.flightTime);
        System.out.println("The hasGPS is : " + drone16.hasGPS);
        System.out.println("The color is : " + drone16.color);
        System.out.println("The stockQuantity is : " + drone16.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone16.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone16.isEcoFriendly);
        System.out.println("The controlType is : " + drone16.controlType);
        System.out.println("The rating is : " + drone16.rating);
        System.out.println("The maxRange is : " + drone16.maxRange);
        System.out.println("The isCertified is : " + drone16.isCertified);
        System.out.println("The countryOfOrigin is : " + drone16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone16.manufacturingYear);
        System.out.println("The propellerSize is : " + drone16.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone16.supportsMobileApp);
        System.out.println("The certificationType is : " + drone16.certificationType);


        Drone drone17 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone17.droneBrand);
        System.out.println("The droneId is : " + drone17.droneId);
        System.out.println("The dronePrice is : " + drone17.dronePrice);
        System.out.println("The isAvailable is : " + drone17.isAvailable);
        System.out.println("The droneType is : " + drone17.droneType);
        System.out.println("The maxSpeed is : " + drone17.maxSpeed);
        System.out.println("The weight is : " + drone17.weight);
        System.out.println("The hasCamera is : " + drone17.hasCamera);
        System.out.println("The cameraResolution is : " + drone17.cameraResolution);
        System.out.println("The warrantyYears is : " + drone17.warrantyYears);
        System.out.println("The flightTime is : " + drone17.flightTime);
        System.out.println("The hasGPS is : " + drone17.hasGPS);
        System.out.println("The color is : " + drone17.color);
        System.out.println("The stockQuantity is : " + drone17.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone17.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone17.isEcoFriendly);
        System.out.println("The controlType is : " + drone17.controlType);
        System.out.println("The rating is : " + drone17.rating);
        System.out.println("The maxRange is : " + drone17.maxRange);
        System.out.println("The isCertified is : " + drone17.isCertified);
        System.out.println("The countryOfOrigin is : " + drone17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone17.manufacturingYear);
        System.out.println("The propellerSize is : " + drone17.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone17.supportsMobileApp);
        System.out.println("The certificationType is : " + drone17.certificationType);

        drone17.droneBrand = "SkyTech";
        drone17.droneId = 17;
        drone17.dronePrice = 17500.99;
        drone17.isAvailable = true;
        drone17.droneType = "Quadcopter";
        drone17.maxSpeed = 60.0;
        drone17.weight = 1.4;
        drone17.hasCamera = true;
        drone17.cameraResolution = "4K";
        drone17.warrantyYears = 2;
        drone17.flightTime = 30.0;
        drone17.hasGPS = true;
        drone17.color = "Black";
        drone17.stockQuantity = 12;
        drone17.batteryCapacity = 4500.0;
        drone17.isEcoFriendly = true;
        drone17.controlType = "Remote";
        drone17.rating = 5;
        drone17.maxRange = 5000.0;
        drone17.isCertified = true;
        drone17.countryOfOrigin = "China";
        drone17.manufacturingYear = 2025;
        drone17.propellerSize = 10.0;
        drone17.supportsMobileApp = true;
        drone17.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone17.droneBrand);
        System.out.println("The droneId is : " + drone17.droneId);
        System.out.println("The dronePrice is : " + drone17.dronePrice);
        System.out.println("The isAvailable is : " + drone17.isAvailable);
        System.out.println("The droneType is : " + drone17.droneType);
        System.out.println("The maxSpeed is : " + drone17.maxSpeed);
        System.out.println("The weight is : " + drone17.weight);
        System.out.println("The hasCamera is : " + drone17.hasCamera);
        System.out.println("The cameraResolution is : " + drone17.cameraResolution);
        System.out.println("The warrantyYears is : " + drone17.warrantyYears);
        System.out.println("The flightTime is : " + drone17.flightTime);
        System.out.println("The hasGPS is : " + drone17.hasGPS);
        System.out.println("The color is : " + drone17.color);
        System.out.println("The stockQuantity is : " + drone17.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone17.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone17.isEcoFriendly);
        System.out.println("The controlType is : " + drone17.controlType);
        System.out.println("The rating is : " + drone17.rating);
        System.out.println("The maxRange is : " + drone17.maxRange);
        System.out.println("The isCertified is : " + drone17.isCertified);
        System.out.println("The countryOfOrigin is : " + drone17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone17.manufacturingYear);
        System.out.println("The propellerSize is : " + drone17.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone17.supportsMobileApp);
        System.out.println("The certificationType is : " + drone17.certificationType);


        Drone drone18 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone18.droneBrand);
        System.out.println("The droneId is : " + drone18.droneId);
        System.out.println("The dronePrice is : " + drone18.dronePrice);
        System.out.println("The isAvailable is : " + drone18.isAvailable);
        System.out.println("The droneType is : " + drone18.droneType);
        System.out.println("The maxSpeed is : " + drone18.maxSpeed);
        System.out.println("The weight is : " + drone18.weight);
        System.out.println("The hasCamera is : " + drone18.hasCamera);
        System.out.println("The cameraResolution is : " + drone18.cameraResolution);
        System.out.println("The warrantyYears is : " + drone18.warrantyYears);
        System.out.println("The flightTime is : " + drone18.flightTime);
        System.out.println("The hasGPS is : " + drone18.hasGPS);
        System.out.println("The color is : " + drone18.color);
        System.out.println("The stockQuantity is : " + drone18.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone18.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone18.isEcoFriendly);
        System.out.println("The controlType is : " + drone18.controlType);
        System.out.println("The rating is : " + drone18.rating);
        System.out.println("The maxRange is : " + drone18.maxRange);
        System.out.println("The isCertified is : " + drone18.isCertified);
        System.out.println("The countryOfOrigin is : " + drone18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone18.manufacturingYear);
        System.out.println("The propellerSize is : " + drone18.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone18.supportsMobileApp);
        System.out.println("The certificationType is : " + drone18.certificationType);

        drone18.droneBrand = "SkyTech";
        drone18.droneId = 18;
        drone18.dronePrice = 18500.99;
        drone18.isAvailable = true;
        drone18.droneType = "Quadcopter";
        drone18.maxSpeed = 60.0;
        drone18.weight = 1.4;
        drone18.hasCamera = true;
        drone18.cameraResolution = "4K";
        drone18.warrantyYears = 2;
        drone18.flightTime = 30.0;
        drone18.hasGPS = true;
        drone18.color = "Black";
        drone18.stockQuantity = 12;
        drone18.batteryCapacity = 4500.0;
        drone18.isEcoFriendly = true;
        drone18.controlType = "Remote";
        drone18.rating = 5;
        drone18.maxRange = 5000.0;
        drone18.isCertified = true;
        drone18.countryOfOrigin = "China";
        drone18.manufacturingYear = 2025;
        drone18.propellerSize = 10.0;
        drone18.supportsMobileApp = true;
        drone18.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone18.droneBrand);
        System.out.println("The droneId is : " + drone18.droneId);
        System.out.println("The dronePrice is : " + drone18.dronePrice);
        System.out.println("The isAvailable is : " + drone18.isAvailable);
        System.out.println("The droneType is : " + drone18.droneType);
        System.out.println("The maxSpeed is : " + drone18.maxSpeed);
        System.out.println("The weight is : " + drone18.weight);
        System.out.println("The hasCamera is : " + drone18.hasCamera);
        System.out.println("The cameraResolution is : " + drone18.cameraResolution);
        System.out.println("The warrantyYears is : " + drone18.warrantyYears);
        System.out.println("The flightTime is : " + drone18.flightTime);
        System.out.println("The hasGPS is : " + drone18.hasGPS);
        System.out.println("The color is : " + drone18.color);
        System.out.println("The stockQuantity is : " + drone18.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone18.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone18.isEcoFriendly);
        System.out.println("The controlType is : " + drone18.controlType);
        System.out.println("The rating is : " + drone18.rating);
        System.out.println("The maxRange is : " + drone18.maxRange);
        System.out.println("The isCertified is : " + drone18.isCertified);
        System.out.println("The countryOfOrigin is : " + drone18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone18.manufacturingYear);
        System.out.println("The propellerSize is : " + drone18.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone18.supportsMobileApp);
        System.out.println("The certificationType is : " + drone18.certificationType);


        Drone drone19 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone19.droneBrand);
        System.out.println("The droneId is : " + drone19.droneId);
        System.out.println("The dronePrice is : " + drone19.dronePrice);
        System.out.println("The isAvailable is : " + drone19.isAvailable);
        System.out.println("The droneType is : " + drone19.droneType);
        System.out.println("The maxSpeed is : " + drone19.maxSpeed);
        System.out.println("The weight is : " + drone19.weight);
        System.out.println("The hasCamera is : " + drone19.hasCamera);
        System.out.println("The cameraResolution is : " + drone19.cameraResolution);
        System.out.println("The warrantyYears is : " + drone19.warrantyYears);
        System.out.println("The flightTime is : " + drone19.flightTime);
        System.out.println("The hasGPS is : " + drone19.hasGPS);
        System.out.println("The color is : " + drone19.color);
        System.out.println("The stockQuantity is : " + drone19.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone19.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone19.isEcoFriendly);
        System.out.println("The controlType is : " + drone19.controlType);
        System.out.println("The rating is : " + drone19.rating);
        System.out.println("The maxRange is : " + drone19.maxRange);
        System.out.println("The isCertified is : " + drone19.isCertified);
        System.out.println("The countryOfOrigin is : " + drone19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone19.manufacturingYear);
        System.out.println("The propellerSize is : " + drone19.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone19.supportsMobileApp);
        System.out.println("The certificationType is : " + drone19.certificationType);

        drone19.droneBrand = "SkyTech";
        drone19.droneId = 19;
        drone19.dronePrice = 19500.99;
        drone19.isAvailable = true;
        drone19.droneType = "Quadcopter";
        drone19.maxSpeed = 60.0;
        drone19.weight = 1.4;
        drone19.hasCamera = true;
        drone19.cameraResolution = "4K";
        drone19.warrantyYears = 2;
        drone19.flightTime = 30.0;
        drone19.hasGPS = true;
        drone19.color = "Black";
        drone19.stockQuantity = 12;
        drone19.batteryCapacity = 4500.0;
        drone19.isEcoFriendly = true;
        drone19.controlType = "Remote";
        drone19.rating = 5;
        drone19.maxRange = 5000.0;
        drone19.isCertified = true;
        drone19.countryOfOrigin = "China";
        drone19.manufacturingYear = 2025;
        drone19.propellerSize = 10.0;
        drone19.supportsMobileApp = true;
        drone19.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone19.droneBrand);
        System.out.println("The droneId is : " + drone19.droneId);
        System.out.println("The dronePrice is : " + drone19.dronePrice);
        System.out.println("The isAvailable is : " + drone19.isAvailable);
        System.out.println("The droneType is : " + drone19.droneType);
        System.out.println("The maxSpeed is : " + drone19.maxSpeed);
        System.out.println("The weight is : " + drone19.weight);
        System.out.println("The hasCamera is : " + drone19.hasCamera);
        System.out.println("The cameraResolution is : " + drone19.cameraResolution);
        System.out.println("The warrantyYears is : " + drone19.warrantyYears);
        System.out.println("The flightTime is : " + drone19.flightTime);
        System.out.println("The hasGPS is : " + drone19.hasGPS);
        System.out.println("The color is : " + drone19.color);
        System.out.println("The stockQuantity is : " + drone19.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone19.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone19.isEcoFriendly);
        System.out.println("The controlType is : " + drone19.controlType);
        System.out.println("The rating is : " + drone19.rating);
        System.out.println("The maxRange is : " + drone19.maxRange);
        System.out.println("The isCertified is : " + drone19.isCertified);
        System.out.println("The countryOfOrigin is : " + drone19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone19.manufacturingYear);
        System.out.println("The propellerSize is : " + drone19.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone19.supportsMobileApp);
        System.out.println("The certificationType is : " + drone19.certificationType);


        Drone drone20 = new Drone();

        System.out.println("Before initialization");

        System.out.println("The droneBrand is : " + drone20.droneBrand);
        System.out.println("The droneId is : " + drone20.droneId);
        System.out.println("The dronePrice is : " + drone20.dronePrice);
        System.out.println("The isAvailable is : " + drone20.isAvailable);
        System.out.println("The droneType is : " + drone20.droneType);
        System.out.println("The maxSpeed is : " + drone20.maxSpeed);
        System.out.println("The weight is : " + drone20.weight);
        System.out.println("The hasCamera is : " + drone20.hasCamera);
        System.out.println("The cameraResolution is : " + drone20.cameraResolution);
        System.out.println("The warrantyYears is : " + drone20.warrantyYears);
        System.out.println("The flightTime is : " + drone20.flightTime);
        System.out.println("The hasGPS is : " + drone20.hasGPS);
        System.out.println("The color is : " + drone20.color);
        System.out.println("The stockQuantity is : " + drone20.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone20.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone20.isEcoFriendly);
        System.out.println("The controlType is : " + drone20.controlType);
        System.out.println("The rating is : " + drone20.rating);
        System.out.println("The maxRange is : " + drone20.maxRange);
        System.out.println("The isCertified is : " + drone20.isCertified);
        System.out.println("The countryOfOrigin is : " + drone20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone20.manufacturingYear);
        System.out.println("The propellerSize is : " + drone20.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone20.supportsMobileApp);
        System.out.println("The certificationType is : " + drone20.certificationType);

        drone20.droneBrand = "SkyTech";
        drone20.droneId = 20;
        drone20.dronePrice = 20500.99;
        drone20.isAvailable = true;
        drone20.droneType = "Quadcopter";
        drone20.maxSpeed = 60.0;
        drone20.weight = 1.4;
        drone20.hasCamera = true;
        drone20.cameraResolution = "4K";
        drone20.warrantyYears = 2;
        drone20.flightTime = 30.0;
        drone20.hasGPS = true;
        drone20.color = "Black";
        drone20.stockQuantity = 12;
        drone20.batteryCapacity = 4500.0;
        drone20.isEcoFriendly = true;
        drone20.controlType = "Remote";
        drone20.rating = 5;
        drone20.maxRange = 5000.0;
        drone20.isCertified = true;
        drone20.countryOfOrigin = "China";
        drone20.manufacturingYear = 2025;
        drone20.propellerSize = 10.0;
        drone20.supportsMobileApp = true;
        drone20.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The droneBrand is : " + drone20.droneBrand);
        System.out.println("The droneId is : " + drone20.droneId);
        System.out.println("The dronePrice is : " + drone20.dronePrice);
        System.out.println("The isAvailable is : " + drone20.isAvailable);
        System.out.println("The droneType is : " + drone20.droneType);
        System.out.println("The maxSpeed is : " + drone20.maxSpeed);
        System.out.println("The weight is : " + drone20.weight);
        System.out.println("The hasCamera is : " + drone20.hasCamera);
        System.out.println("The cameraResolution is : " + drone20.cameraResolution);
        System.out.println("The warrantyYears is : " + drone20.warrantyYears);
        System.out.println("The flightTime is : " + drone20.flightTime);
        System.out.println("The hasGPS is : " + drone20.hasGPS);
        System.out.println("The color is : " + drone20.color);
        System.out.println("The stockQuantity is : " + drone20.stockQuantity);
        System.out.println("The batteryCapacity is : " + drone20.batteryCapacity);
        System.out.println("The isEcoFriendly is : " + drone20.isEcoFriendly);
        System.out.println("The controlType is : " + drone20.controlType);
        System.out.println("The rating is : " + drone20.rating);
        System.out.println("The maxRange is : " + drone20.maxRange);
        System.out.println("The isCertified is : " + drone20.isCertified);
        System.out.println("The countryOfOrigin is : " + drone20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + drone20.manufacturingYear);
        System.out.println("The propellerSize is : " + drone20.propellerSize);
        System.out.println("The supportsMobileApp is : " + drone20.supportsMobileApp);
        System.out.println("The certificationType is : " + drone20.certificationType);


    }
}
