class GeneratorExecutor {

    public static void main(String[] args) {

        Generator gen1 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen1.generatorBrand);
        System.out.println("The generatorId is : " + gen1.generatorId);
        System.out.println("The generatorPrice is : " + gen1.generatorPrice);
        System.out.println("The isAvailable is : " + gen1.isAvailable);
        System.out.println("The generatorType is : " + gen1.generatorType);
        System.out.println("The powerOutputKW is : " + gen1.powerOutputKW);
        System.out.println("The weight is : " + gen1.weight);
        System.out.println("The isPortable is : " + gen1.isPortable);
        System.out.println("The fuelType is : " + gen1.fuelType);
        System.out.println("The warrantyYears is : " + gen1.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen1.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen1.hasElectricStart);
        System.out.println("The color is : " + gen1.color);
        System.out.println("The stockQuantity is : " + gen1.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen1.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen1.isEcoFriendly);
        System.out.println("The coolingType is : " + gen1.coolingType);
        System.out.println("The rating is : " + gen1.rating);
        System.out.println("The runningTime is : " + gen1.runningTime);
        System.out.println("The isCertified is : " + gen1.isCertified);
        System.out.println("The countryOfOrigin is : " + gen1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen1.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen1.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen1.supportsAutoStart);
        System.out.println("The certificationType is : " + gen1.certificationType);

        gen1.generatorBrand = "PowerGen";
        gen1.generatorId = 1;
        gen1.generatorPrice = 1000.99;
        gen1.isAvailable = true;
        gen1.generatorType = "Diesel";
        gen1.powerOutputKW = 5.5;
        gen1.weight = 85.0;
        gen1.isPortable = true;
        gen1.fuelType = "Diesel";
        gen1.warrantyYears = 2;
        gen1.fuelTankCapacity = 15.0;
        gen1.hasElectricStart = true;
        gen1.color = "Yellow";
        gen1.stockQuantity = 10;
        gen1.fuelConsumption = 1.2;
        gen1.isEcoFriendly = false;
        gen1.coolingType = "Air";
        gen1.rating = 4;
        gen1.runningTime = 10.0;
        gen1.isCertified = true;
        gen1.countryOfOrigin = "India";
        gen1.manufacturingYear = 2025;
        gen1.noiseLevel = 72.5;
        gen1.supportsAutoStart = true;
        gen1.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen1.generatorBrand);
        System.out.println("The generatorId is : " + gen1.generatorId);
        System.out.println("The generatorPrice is : " + gen1.generatorPrice);
        System.out.println("The isAvailable is : " + gen1.isAvailable);
        System.out.println("The generatorType is : " + gen1.generatorType);
        System.out.println("The powerOutputKW is : " + gen1.powerOutputKW);
        System.out.println("The weight is : " + gen1.weight);
        System.out.println("The isPortable is : " + gen1.isPortable);
        System.out.println("The fuelType is : " + gen1.fuelType);
        System.out.println("The warrantyYears is : " + gen1.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen1.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen1.hasElectricStart);
        System.out.println("The color is : " + gen1.color);
        System.out.println("The stockQuantity is : " + gen1.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen1.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen1.isEcoFriendly);
        System.out.println("The coolingType is : " + gen1.coolingType);
        System.out.println("The rating is : " + gen1.rating);
        System.out.println("The runningTime is : " + gen1.runningTime);
        System.out.println("The isCertified is : " + gen1.isCertified);
        System.out.println("The countryOfOrigin is : " + gen1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen1.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen1.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen1.supportsAutoStart);
        System.out.println("The certificationType is : " + gen1.certificationType);


        Generator gen2 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen2.generatorBrand);
        System.out.println("The generatorId is : " + gen2.generatorId);
        System.out.println("The generatorPrice is : " + gen2.generatorPrice);
        System.out.println("The isAvailable is : " + gen2.isAvailable);
        System.out.println("The generatorType is : " + gen2.generatorType);
        System.out.println("The powerOutputKW is : " + gen2.powerOutputKW);
        System.out.println("The weight is : " + gen2.weight);
        System.out.println("The isPortable is : " + gen2.isPortable);
        System.out.println("The fuelType is : " + gen2.fuelType);
        System.out.println("The warrantyYears is : " + gen2.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen2.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen2.hasElectricStart);
        System.out.println("The color is : " + gen2.color);
        System.out.println("The stockQuantity is : " + gen2.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen2.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen2.isEcoFriendly);
        System.out.println("The coolingType is : " + gen2.coolingType);
        System.out.println("The rating is : " + gen2.rating);
        System.out.println("The runningTime is : " + gen2.runningTime);
        System.out.println("The isCertified is : " + gen2.isCertified);
        System.out.println("The countryOfOrigin is : " + gen2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen2.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen2.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen2.supportsAutoStart);
        System.out.println("The certificationType is : " + gen2.certificationType);

        gen2.generatorBrand = "PowerGen";
        gen2.generatorId = 2;
        gen2.generatorPrice = 2000.99;
        gen2.isAvailable = true;
        gen2.generatorType = "Diesel";
        gen2.powerOutputKW = 5.5;
        gen2.weight = 85.0;
        gen2.isPortable = true;
        gen2.fuelType = "Diesel";
        gen2.warrantyYears = 2;
        gen2.fuelTankCapacity = 15.0;
        gen2.hasElectricStart = true;
        gen2.color = "Yellow";
        gen2.stockQuantity = 10;
        gen2.fuelConsumption = 1.2;
        gen2.isEcoFriendly = false;
        gen2.coolingType = "Air";
        gen2.rating = 4;
        gen2.runningTime = 10.0;
        gen2.isCertified = true;
        gen2.countryOfOrigin = "India";
        gen2.manufacturingYear = 2025;
        gen2.noiseLevel = 72.5;
        gen2.supportsAutoStart = true;
        gen2.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen2.generatorBrand);
        System.out.println("The generatorId is : " + gen2.generatorId);
        System.out.println("The generatorPrice is : " + gen2.generatorPrice);
        System.out.println("The isAvailable is : " + gen2.isAvailable);
        System.out.println("The generatorType is : " + gen2.generatorType);
        System.out.println("The powerOutputKW is : " + gen2.powerOutputKW);
        System.out.println("The weight is : " + gen2.weight);
        System.out.println("The isPortable is : " + gen2.isPortable);
        System.out.println("The fuelType is : " + gen2.fuelType);
        System.out.println("The warrantyYears is : " + gen2.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen2.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen2.hasElectricStart);
        System.out.println("The color is : " + gen2.color);
        System.out.println("The stockQuantity is : " + gen2.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen2.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen2.isEcoFriendly);
        System.out.println("The coolingType is : " + gen2.coolingType);
        System.out.println("The rating is : " + gen2.rating);
        System.out.println("The runningTime is : " + gen2.runningTime);
        System.out.println("The isCertified is : " + gen2.isCertified);
        System.out.println("The countryOfOrigin is : " + gen2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen2.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen2.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen2.supportsAutoStart);
        System.out.println("The certificationType is : " + gen2.certificationType);


        Generator gen3 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen3.generatorBrand);
        System.out.println("The generatorId is : " + gen3.generatorId);
        System.out.println("The generatorPrice is : " + gen3.generatorPrice);
        System.out.println("The isAvailable is : " + gen3.isAvailable);
        System.out.println("The generatorType is : " + gen3.generatorType);
        System.out.println("The powerOutputKW is : " + gen3.powerOutputKW);
        System.out.println("The weight is : " + gen3.weight);
        System.out.println("The isPortable is : " + gen3.isPortable);
        System.out.println("The fuelType is : " + gen3.fuelType);
        System.out.println("The warrantyYears is : " + gen3.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen3.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen3.hasElectricStart);
        System.out.println("The color is : " + gen3.color);
        System.out.println("The stockQuantity is : " + gen3.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen3.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen3.isEcoFriendly);
        System.out.println("The coolingType is : " + gen3.coolingType);
        System.out.println("The rating is : " + gen3.rating);
        System.out.println("The runningTime is : " + gen3.runningTime);
        System.out.println("The isCertified is : " + gen3.isCertified);
        System.out.println("The countryOfOrigin is : " + gen3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen3.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen3.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen3.supportsAutoStart);
        System.out.println("The certificationType is : " + gen3.certificationType);

        gen3.generatorBrand = "PowerGen";
        gen3.generatorId = 3;
        gen3.generatorPrice = 3000.99;
        gen3.isAvailable = true;
        gen3.generatorType = "Diesel";
        gen3.powerOutputKW = 5.5;
        gen3.weight = 85.0;
        gen3.isPortable = true;
        gen3.fuelType = "Diesel";
        gen3.warrantyYears = 2;
        gen3.fuelTankCapacity = 15.0;
        gen3.hasElectricStart = true;
        gen3.color = "Yellow";
        gen3.stockQuantity = 10;
        gen3.fuelConsumption = 1.2;
        gen3.isEcoFriendly = false;
        gen3.coolingType = "Air";
        gen3.rating = 4;
        gen3.runningTime = 10.0;
        gen3.isCertified = true;
        gen3.countryOfOrigin = "India";
        gen3.manufacturingYear = 2025;
        gen3.noiseLevel = 72.5;
        gen3.supportsAutoStart = true;
        gen3.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen3.generatorBrand);
        System.out.println("The generatorId is : " + gen3.generatorId);
        System.out.println("The generatorPrice is : " + gen3.generatorPrice);
        System.out.println("The isAvailable is : " + gen3.isAvailable);
        System.out.println("The generatorType is : " + gen3.generatorType);
        System.out.println("The powerOutputKW is : " + gen3.powerOutputKW);
        System.out.println("The weight is : " + gen3.weight);
        System.out.println("The isPortable is : " + gen3.isPortable);
        System.out.println("The fuelType is : " + gen3.fuelType);
        System.out.println("The warrantyYears is : " + gen3.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen3.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen3.hasElectricStart);
        System.out.println("The color is : " + gen3.color);
        System.out.println("The stockQuantity is : " + gen3.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen3.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen3.isEcoFriendly);
        System.out.println("The coolingType is : " + gen3.coolingType);
        System.out.println("The rating is : " + gen3.rating);
        System.out.println("The runningTime is : " + gen3.runningTime);
        System.out.println("The isCertified is : " + gen3.isCertified);
        System.out.println("The countryOfOrigin is : " + gen3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen3.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen3.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen3.supportsAutoStart);
        System.out.println("The certificationType is : " + gen3.certificationType);


        Generator gen4 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen4.generatorBrand);
        System.out.println("The generatorId is : " + gen4.generatorId);
        System.out.println("The generatorPrice is : " + gen4.generatorPrice);
        System.out.println("The isAvailable is : " + gen4.isAvailable);
        System.out.println("The generatorType is : " + gen4.generatorType);
        System.out.println("The powerOutputKW is : " + gen4.powerOutputKW);
        System.out.println("The weight is : " + gen4.weight);
        System.out.println("The isPortable is : " + gen4.isPortable);
        System.out.println("The fuelType is : " + gen4.fuelType);
        System.out.println("The warrantyYears is : " + gen4.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen4.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen4.hasElectricStart);
        System.out.println("The color is : " + gen4.color);
        System.out.println("The stockQuantity is : " + gen4.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen4.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen4.isEcoFriendly);
        System.out.println("The coolingType is : " + gen4.coolingType);
        System.out.println("The rating is : " + gen4.rating);
        System.out.println("The runningTime is : " + gen4.runningTime);
        System.out.println("The isCertified is : " + gen4.isCertified);
        System.out.println("The countryOfOrigin is : " + gen4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen4.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen4.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen4.supportsAutoStart);
        System.out.println("The certificationType is : " + gen4.certificationType);

        gen4.generatorBrand = "PowerGen";
        gen4.generatorId = 4;
        gen4.generatorPrice = 4000.99;
        gen4.isAvailable = true;
        gen4.generatorType = "Diesel";
        gen4.powerOutputKW = 5.5;
        gen4.weight = 85.0;
        gen4.isPortable = true;
        gen4.fuelType = "Diesel";
        gen4.warrantyYears = 2;
        gen4.fuelTankCapacity = 15.0;
        gen4.hasElectricStart = true;
        gen4.color = "Yellow";
        gen4.stockQuantity = 10;
        gen4.fuelConsumption = 1.2;
        gen4.isEcoFriendly = false;
        gen4.coolingType = "Air";
        gen4.rating = 4;
        gen4.runningTime = 10.0;
        gen4.isCertified = true;
        gen4.countryOfOrigin = "India";
        gen4.manufacturingYear = 2025;
        gen4.noiseLevel = 72.5;
        gen4.supportsAutoStart = true;
        gen4.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen4.generatorBrand);
        System.out.println("The generatorId is : " + gen4.generatorId);
        System.out.println("The generatorPrice is : " + gen4.generatorPrice);
        System.out.println("The isAvailable is : " + gen4.isAvailable);
        System.out.println("The generatorType is : " + gen4.generatorType);
        System.out.println("The powerOutputKW is : " + gen4.powerOutputKW);
        System.out.println("The weight is : " + gen4.weight);
        System.out.println("The isPortable is : " + gen4.isPortable);
        System.out.println("The fuelType is : " + gen4.fuelType);
        System.out.println("The warrantyYears is : " + gen4.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen4.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen4.hasElectricStart);
        System.out.println("The color is : " + gen4.color);
        System.out.println("The stockQuantity is : " + gen4.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen4.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen4.isEcoFriendly);
        System.out.println("The coolingType is : " + gen4.coolingType);
        System.out.println("The rating is : " + gen4.rating);
        System.out.println("The runningTime is : " + gen4.runningTime);
        System.out.println("The isCertified is : " + gen4.isCertified);
        System.out.println("The countryOfOrigin is : " + gen4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen4.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen4.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen4.supportsAutoStart);
        System.out.println("The certificationType is : " + gen4.certificationType);


        Generator gen5 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen5.generatorBrand);
        System.out.println("The generatorId is : " + gen5.generatorId);
        System.out.println("The generatorPrice is : " + gen5.generatorPrice);
        System.out.println("The isAvailable is : " + gen5.isAvailable);
        System.out.println("The generatorType is : " + gen5.generatorType);
        System.out.println("The powerOutputKW is : " + gen5.powerOutputKW);
        System.out.println("The weight is : " + gen5.weight);
        System.out.println("The isPortable is : " + gen5.isPortable);
        System.out.println("The fuelType is : " + gen5.fuelType);
        System.out.println("The warrantyYears is : " + gen5.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen5.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen5.hasElectricStart);
        System.out.println("The color is : " + gen5.color);
        System.out.println("The stockQuantity is : " + gen5.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen5.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen5.isEcoFriendly);
        System.out.println("The coolingType is : " + gen5.coolingType);
        System.out.println("The rating is : " + gen5.rating);
        System.out.println("The runningTime is : " + gen5.runningTime);
        System.out.println("The isCertified is : " + gen5.isCertified);
        System.out.println("The countryOfOrigin is : " + gen5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen5.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen5.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen5.supportsAutoStart);
        System.out.println("The certificationType is : " + gen5.certificationType);

        gen5.generatorBrand = "PowerGen";
        gen5.generatorId = 5;
        gen5.generatorPrice = 5000.99;
        gen5.isAvailable = true;
        gen5.generatorType = "Diesel";
        gen5.powerOutputKW = 5.5;
        gen5.weight = 85.0;
        gen5.isPortable = true;
        gen5.fuelType = "Diesel";
        gen5.warrantyYears = 2;
        gen5.fuelTankCapacity = 15.0;
        gen5.hasElectricStart = true;
        gen5.color = "Yellow";
        gen5.stockQuantity = 10;
        gen5.fuelConsumption = 1.2;
        gen5.isEcoFriendly = false;
        gen5.coolingType = "Air";
        gen5.rating = 4;
        gen5.runningTime = 10.0;
        gen5.isCertified = true;
        gen5.countryOfOrigin = "India";
        gen5.manufacturingYear = 2025;
        gen5.noiseLevel = 72.5;
        gen5.supportsAutoStart = true;
        gen5.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen5.generatorBrand);
        System.out.println("The generatorId is : " + gen5.generatorId);
        System.out.println("The generatorPrice is : " + gen5.generatorPrice);
        System.out.println("The isAvailable is : " + gen5.isAvailable);
        System.out.println("The generatorType is : " + gen5.generatorType);
        System.out.println("The powerOutputKW is : " + gen5.powerOutputKW);
        System.out.println("The weight is : " + gen5.weight);
        System.out.println("The isPortable is : " + gen5.isPortable);
        System.out.println("The fuelType is : " + gen5.fuelType);
        System.out.println("The warrantyYears is : " + gen5.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen5.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen5.hasElectricStart);
        System.out.println("The color is : " + gen5.color);
        System.out.println("The stockQuantity is : " + gen5.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen5.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen5.isEcoFriendly);
        System.out.println("The coolingType is : " + gen5.coolingType);
        System.out.println("The rating is : " + gen5.rating);
        System.out.println("The runningTime is : " + gen5.runningTime);
        System.out.println("The isCertified is : " + gen5.isCertified);
        System.out.println("The countryOfOrigin is : " + gen5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen5.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen5.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen5.supportsAutoStart);
        System.out.println("The certificationType is : " + gen5.certificationType);


        Generator gen6 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen6.generatorBrand);
        System.out.println("The generatorId is : " + gen6.generatorId);
        System.out.println("The generatorPrice is : " + gen6.generatorPrice);
        System.out.println("The isAvailable is : " + gen6.isAvailable);
        System.out.println("The generatorType is : " + gen6.generatorType);
        System.out.println("The powerOutputKW is : " + gen6.powerOutputKW);
        System.out.println("The weight is : " + gen6.weight);
        System.out.println("The isPortable is : " + gen6.isPortable);
        System.out.println("The fuelType is : " + gen6.fuelType);
        System.out.println("The warrantyYears is : " + gen6.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen6.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen6.hasElectricStart);
        System.out.println("The color is : " + gen6.color);
        System.out.println("The stockQuantity is : " + gen6.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen6.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen6.isEcoFriendly);
        System.out.println("The coolingType is : " + gen6.coolingType);
        System.out.println("The rating is : " + gen6.rating);
        System.out.println("The runningTime is : " + gen6.runningTime);
        System.out.println("The isCertified is : " + gen6.isCertified);
        System.out.println("The countryOfOrigin is : " + gen6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen6.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen6.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen6.supportsAutoStart);
        System.out.println("The certificationType is : " + gen6.certificationType);

        gen6.generatorBrand = "PowerGen";
        gen6.generatorId = 6;
        gen6.generatorPrice = 6000.99;
        gen6.isAvailable = true;
        gen6.generatorType = "Diesel";
        gen6.powerOutputKW = 5.5;
        gen6.weight = 85.0;
        gen6.isPortable = true;
        gen6.fuelType = "Diesel";
        gen6.warrantyYears = 2;
        gen6.fuelTankCapacity = 15.0;
        gen6.hasElectricStart = true;
        gen6.color = "Yellow";
        gen6.stockQuantity = 10;
        gen6.fuelConsumption = 1.2;
        gen6.isEcoFriendly = false;
        gen6.coolingType = "Air";
        gen6.rating = 4;
        gen6.runningTime = 10.0;
        gen6.isCertified = true;
        gen6.countryOfOrigin = "India";
        gen6.manufacturingYear = 2025;
        gen6.noiseLevel = 72.5;
        gen6.supportsAutoStart = true;
        gen6.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen6.generatorBrand);
        System.out.println("The generatorId is : " + gen6.generatorId);
        System.out.println("The generatorPrice is : " + gen6.generatorPrice);
        System.out.println("The isAvailable is : " + gen6.isAvailable);
        System.out.println("The generatorType is : " + gen6.generatorType);
        System.out.println("The powerOutputKW is : " + gen6.powerOutputKW);
        System.out.println("The weight is : " + gen6.weight);
        System.out.println("The isPortable is : " + gen6.isPortable);
        System.out.println("The fuelType is : " + gen6.fuelType);
        System.out.println("The warrantyYears is : " + gen6.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen6.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen6.hasElectricStart);
        System.out.println("The color is : " + gen6.color);
        System.out.println("The stockQuantity is : " + gen6.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen6.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen6.isEcoFriendly);
        System.out.println("The coolingType is : " + gen6.coolingType);
        System.out.println("The rating is : " + gen6.rating);
        System.out.println("The runningTime is : " + gen6.runningTime);
        System.out.println("The isCertified is : " + gen6.isCertified);
        System.out.println("The countryOfOrigin is : " + gen6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen6.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen6.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen6.supportsAutoStart);
        System.out.println("The certificationType is : " + gen6.certificationType);


        Generator gen7 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen7.generatorBrand);
        System.out.println("The generatorId is : " + gen7.generatorId);
        System.out.println("The generatorPrice is : " + gen7.generatorPrice);
        System.out.println("The isAvailable is : " + gen7.isAvailable);
        System.out.println("The generatorType is : " + gen7.generatorType);
        System.out.println("The powerOutputKW is : " + gen7.powerOutputKW);
        System.out.println("The weight is : " + gen7.weight);
        System.out.println("The isPortable is : " + gen7.isPortable);
        System.out.println("The fuelType is : " + gen7.fuelType);
        System.out.println("The warrantyYears is : " + gen7.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen7.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen7.hasElectricStart);
        System.out.println("The color is : " + gen7.color);
        System.out.println("The stockQuantity is : " + gen7.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen7.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen7.isEcoFriendly);
        System.out.println("The coolingType is : " + gen7.coolingType);
        System.out.println("The rating is : " + gen7.rating);
        System.out.println("The runningTime is : " + gen7.runningTime);
        System.out.println("The isCertified is : " + gen7.isCertified);
        System.out.println("The countryOfOrigin is : " + gen7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen7.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen7.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen7.supportsAutoStart);
        System.out.println("The certificationType is : " + gen7.certificationType);

        gen7.generatorBrand = "PowerGen";
        gen7.generatorId = 7;
        gen7.generatorPrice = 7000.99;
        gen7.isAvailable = true;
        gen7.generatorType = "Diesel";
        gen7.powerOutputKW = 5.5;
        gen7.weight = 85.0;
        gen7.isPortable = true;
        gen7.fuelType = "Diesel";
        gen7.warrantyYears = 2;
        gen7.fuelTankCapacity = 15.0;
        gen7.hasElectricStart = true;
        gen7.color = "Yellow";
        gen7.stockQuantity = 10;
        gen7.fuelConsumption = 1.2;
        gen7.isEcoFriendly = false;
        gen7.coolingType = "Air";
        gen7.rating = 4;
        gen7.runningTime = 10.0;
        gen7.isCertified = true;
        gen7.countryOfOrigin = "India";
        gen7.manufacturingYear = 2025;
        gen7.noiseLevel = 72.5;
        gen7.supportsAutoStart = true;
        gen7.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen7.generatorBrand);
        System.out.println("The generatorId is : " + gen7.generatorId);
        System.out.println("The generatorPrice is : " + gen7.generatorPrice);
        System.out.println("The isAvailable is : " + gen7.isAvailable);
        System.out.println("The generatorType is : " + gen7.generatorType);
        System.out.println("The powerOutputKW is : " + gen7.powerOutputKW);
        System.out.println("The weight is : " + gen7.weight);
        System.out.println("The isPortable is : " + gen7.isPortable);
        System.out.println("The fuelType is : " + gen7.fuelType);
        System.out.println("The warrantyYears is : " + gen7.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen7.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen7.hasElectricStart);
        System.out.println("The color is : " + gen7.color);
        System.out.println("The stockQuantity is : " + gen7.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen7.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen7.isEcoFriendly);
        System.out.println("The coolingType is : " + gen7.coolingType);
        System.out.println("The rating is : " + gen7.rating);
        System.out.println("The runningTime is : " + gen7.runningTime);
        System.out.println("The isCertified is : " + gen7.isCertified);
        System.out.println("The countryOfOrigin is : " + gen7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen7.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen7.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen7.supportsAutoStart);
        System.out.println("The certificationType is : " + gen7.certificationType);


        Generator gen8 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen8.generatorBrand);
        System.out.println("The generatorId is : " + gen8.generatorId);
        System.out.println("The generatorPrice is : " + gen8.generatorPrice);
        System.out.println("The isAvailable is : " + gen8.isAvailable);
        System.out.println("The generatorType is : " + gen8.generatorType);
        System.out.println("The powerOutputKW is : " + gen8.powerOutputKW);
        System.out.println("The weight is : " + gen8.weight);
        System.out.println("The isPortable is : " + gen8.isPortable);
        System.out.println("The fuelType is : " + gen8.fuelType);
        System.out.println("The warrantyYears is : " + gen8.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen8.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen8.hasElectricStart);
        System.out.println("The color is : " + gen8.color);
        System.out.println("The stockQuantity is : " + gen8.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen8.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen8.isEcoFriendly);
        System.out.println("The coolingType is : " + gen8.coolingType);
        System.out.println("The rating is : " + gen8.rating);
        System.out.println("The runningTime is : " + gen8.runningTime);
        System.out.println("The isCertified is : " + gen8.isCertified);
        System.out.println("The countryOfOrigin is : " + gen8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen8.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen8.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen8.supportsAutoStart);
        System.out.println("The certificationType is : " + gen8.certificationType);

        gen8.generatorBrand = "PowerGen";
        gen8.generatorId = 8;
        gen8.generatorPrice = 8000.99;
        gen8.isAvailable = true;
        gen8.generatorType = "Diesel";
        gen8.powerOutputKW = 5.5;
        gen8.weight = 85.0;
        gen8.isPortable = true;
        gen8.fuelType = "Diesel";
        gen8.warrantyYears = 2;
        gen8.fuelTankCapacity = 15.0;
        gen8.hasElectricStart = true;
        gen8.color = "Yellow";
        gen8.stockQuantity = 10;
        gen8.fuelConsumption = 1.2;
        gen8.isEcoFriendly = false;
        gen8.coolingType = "Air";
        gen8.rating = 4;
        gen8.runningTime = 10.0;
        gen8.isCertified = true;
        gen8.countryOfOrigin = "India";
        gen8.manufacturingYear = 2025;
        gen8.noiseLevel = 72.5;
        gen8.supportsAutoStart = true;
        gen8.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen8.generatorBrand);
        System.out.println("The generatorId is : " + gen8.generatorId);
        System.out.println("The generatorPrice is : " + gen8.generatorPrice);
        System.out.println("The isAvailable is : " + gen8.isAvailable);
        System.out.println("The generatorType is : " + gen8.generatorType);
        System.out.println("The powerOutputKW is : " + gen8.powerOutputKW);
        System.out.println("The weight is : " + gen8.weight);
        System.out.println("The isPortable is : " + gen8.isPortable);
        System.out.println("The fuelType is : " + gen8.fuelType);
        System.out.println("The warrantyYears is : " + gen8.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen8.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen8.hasElectricStart);
        System.out.println("The color is : " + gen8.color);
        System.out.println("The stockQuantity is : " + gen8.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen8.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen8.isEcoFriendly);
        System.out.println("The coolingType is : " + gen8.coolingType);
        System.out.println("The rating is : " + gen8.rating);
        System.out.println("The runningTime is : " + gen8.runningTime);
        System.out.println("The isCertified is : " + gen8.isCertified);
        System.out.println("The countryOfOrigin is : " + gen8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen8.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen8.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen8.supportsAutoStart);
        System.out.println("The certificationType is : " + gen8.certificationType);


        Generator gen9 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen9.generatorBrand);
        System.out.println("The generatorId is : " + gen9.generatorId);
        System.out.println("The generatorPrice is : " + gen9.generatorPrice);
        System.out.println("The isAvailable is : " + gen9.isAvailable);
        System.out.println("The generatorType is : " + gen9.generatorType);
        System.out.println("The powerOutputKW is : " + gen9.powerOutputKW);
        System.out.println("The weight is : " + gen9.weight);
        System.out.println("The isPortable is : " + gen9.isPortable);
        System.out.println("The fuelType is : " + gen9.fuelType);
        System.out.println("The warrantyYears is : " + gen9.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen9.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen9.hasElectricStart);
        System.out.println("The color is : " + gen9.color);
        System.out.println("The stockQuantity is : " + gen9.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen9.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen9.isEcoFriendly);
        System.out.println("The coolingType is : " + gen9.coolingType);
        System.out.println("The rating is : " + gen9.rating);
        System.out.println("The runningTime is : " + gen9.runningTime);
        System.out.println("The isCertified is : " + gen9.isCertified);
        System.out.println("The countryOfOrigin is : " + gen9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen9.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen9.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen9.supportsAutoStart);
        System.out.println("The certificationType is : " + gen9.certificationType);

        gen9.generatorBrand = "PowerGen";
        gen9.generatorId = 9;
        gen9.generatorPrice = 9000.99;
        gen9.isAvailable = true;
        gen9.generatorType = "Diesel";
        gen9.powerOutputKW = 5.5;
        gen9.weight = 85.0;
        gen9.isPortable = true;
        gen9.fuelType = "Diesel";
        gen9.warrantyYears = 2;
        gen9.fuelTankCapacity = 15.0;
        gen9.hasElectricStart = true;
        gen9.color = "Yellow";
        gen9.stockQuantity = 10;
        gen9.fuelConsumption = 1.2;
        gen9.isEcoFriendly = false;
        gen9.coolingType = "Air";
        gen9.rating = 4;
        gen9.runningTime = 10.0;
        gen9.isCertified = true;
        gen9.countryOfOrigin = "India";
        gen9.manufacturingYear = 2025;
        gen9.noiseLevel = 72.5;
        gen9.supportsAutoStart = true;
        gen9.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen9.generatorBrand);
        System.out.println("The generatorId is : " + gen9.generatorId);
        System.out.println("The generatorPrice is : " + gen9.generatorPrice);
        System.out.println("The isAvailable is : " + gen9.isAvailable);
        System.out.println("The generatorType is : " + gen9.generatorType);
        System.out.println("The powerOutputKW is : " + gen9.powerOutputKW);
        System.out.println("The weight is : " + gen9.weight);
        System.out.println("The isPortable is : " + gen9.isPortable);
        System.out.println("The fuelType is : " + gen9.fuelType);
        System.out.println("The warrantyYears is : " + gen9.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen9.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen9.hasElectricStart);
        System.out.println("The color is : " + gen9.color);
        System.out.println("The stockQuantity is : " + gen9.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen9.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen9.isEcoFriendly);
        System.out.println("The coolingType is : " + gen9.coolingType);
        System.out.println("The rating is : " + gen9.rating);
        System.out.println("The runningTime is : " + gen9.runningTime);
        System.out.println("The isCertified is : " + gen9.isCertified);
        System.out.println("The countryOfOrigin is : " + gen9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen9.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen9.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen9.supportsAutoStart);
        System.out.println("The certificationType is : " + gen9.certificationType);


        Generator gen10 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen10.generatorBrand);
        System.out.println("The generatorId is : " + gen10.generatorId);
        System.out.println("The generatorPrice is : " + gen10.generatorPrice);
        System.out.println("The isAvailable is : " + gen10.isAvailable);
        System.out.println("The generatorType is : " + gen10.generatorType);
        System.out.println("The powerOutputKW is : " + gen10.powerOutputKW);
        System.out.println("The weight is : " + gen10.weight);
        System.out.println("The isPortable is : " + gen10.isPortable);
        System.out.println("The fuelType is : " + gen10.fuelType);
        System.out.println("The warrantyYears is : " + gen10.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen10.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen10.hasElectricStart);
        System.out.println("The color is : " + gen10.color);
        System.out.println("The stockQuantity is : " + gen10.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen10.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen10.isEcoFriendly);
        System.out.println("The coolingType is : " + gen10.coolingType);
        System.out.println("The rating is : " + gen10.rating);
        System.out.println("The runningTime is : " + gen10.runningTime);
        System.out.println("The isCertified is : " + gen10.isCertified);
        System.out.println("The countryOfOrigin is : " + gen10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen10.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen10.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen10.supportsAutoStart);
        System.out.println("The certificationType is : " + gen10.certificationType);

        gen10.generatorBrand = "PowerGen";
        gen10.generatorId = 10;
        gen10.generatorPrice = 10000.99;
        gen10.isAvailable = true;
        gen10.generatorType = "Diesel";
        gen10.powerOutputKW = 5.5;
        gen10.weight = 85.0;
        gen10.isPortable = true;
        gen10.fuelType = "Diesel";
        gen10.warrantyYears = 2;
        gen10.fuelTankCapacity = 15.0;
        gen10.hasElectricStart = true;
        gen10.color = "Yellow";
        gen10.stockQuantity = 10;
        gen10.fuelConsumption = 1.2;
        gen10.isEcoFriendly = false;
        gen10.coolingType = "Air";
        gen10.rating = 4;
        gen10.runningTime = 10.0;
        gen10.isCertified = true;
        gen10.countryOfOrigin = "India";
        gen10.manufacturingYear = 2025;
        gen10.noiseLevel = 72.5;
        gen10.supportsAutoStart = true;
        gen10.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen10.generatorBrand);
        System.out.println("The generatorId is : " + gen10.generatorId);
        System.out.println("The generatorPrice is : " + gen10.generatorPrice);
        System.out.println("The isAvailable is : " + gen10.isAvailable);
        System.out.println("The generatorType is : " + gen10.generatorType);
        System.out.println("The powerOutputKW is : " + gen10.powerOutputKW);
        System.out.println("The weight is : " + gen10.weight);
        System.out.println("The isPortable is : " + gen10.isPortable);
        System.out.println("The fuelType is : " + gen10.fuelType);
        System.out.println("The warrantyYears is : " + gen10.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen10.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen10.hasElectricStart);
        System.out.println("The color is : " + gen10.color);
        System.out.println("The stockQuantity is : " + gen10.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen10.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen10.isEcoFriendly);
        System.out.println("The coolingType is : " + gen10.coolingType);
        System.out.println("The rating is : " + gen10.rating);
        System.out.println("The runningTime is : " + gen10.runningTime);
        System.out.println("The isCertified is : " + gen10.isCertified);
        System.out.println("The countryOfOrigin is : " + gen10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen10.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen10.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen10.supportsAutoStart);
        System.out.println("The certificationType is : " + gen10.certificationType);


        Generator gen11 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen11.generatorBrand);
        System.out.println("The generatorId is : " + gen11.generatorId);
        System.out.println("The generatorPrice is : " + gen11.generatorPrice);
        System.out.println("The isAvailable is : " + gen11.isAvailable);
        System.out.println("The generatorType is : " + gen11.generatorType);
        System.out.println("The powerOutputKW is : " + gen11.powerOutputKW);
        System.out.println("The weight is : " + gen11.weight);
        System.out.println("The isPortable is : " + gen11.isPortable);
        System.out.println("The fuelType is : " + gen11.fuelType);
        System.out.println("The warrantyYears is : " + gen11.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen11.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen11.hasElectricStart);
        System.out.println("The color is : " + gen11.color);
        System.out.println("The stockQuantity is : " + gen11.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen11.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen11.isEcoFriendly);
        System.out.println("The coolingType is : " + gen11.coolingType);
        System.out.println("The rating is : " + gen11.rating);
        System.out.println("The runningTime is : " + gen11.runningTime);
        System.out.println("The isCertified is : " + gen11.isCertified);
        System.out.println("The countryOfOrigin is : " + gen11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen11.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen11.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen11.supportsAutoStart);
        System.out.println("The certificationType is : " + gen11.certificationType);

        gen11.generatorBrand = "PowerGen";
        gen11.generatorId = 11;
        gen11.generatorPrice = 11000.99;
        gen11.isAvailable = true;
        gen11.generatorType = "Diesel";
        gen11.powerOutputKW = 5.5;
        gen11.weight = 85.0;
        gen11.isPortable = true;
        gen11.fuelType = "Diesel";
        gen11.warrantyYears = 2;
        gen11.fuelTankCapacity = 15.0;
        gen11.hasElectricStart = true;
        gen11.color = "Yellow";
        gen11.stockQuantity = 10;
        gen11.fuelConsumption = 1.2;
        gen11.isEcoFriendly = false;
        gen11.coolingType = "Air";
        gen11.rating = 4;
        gen11.runningTime = 10.0;
        gen11.isCertified = true;
        gen11.countryOfOrigin = "India";
        gen11.manufacturingYear = 2025;
        gen11.noiseLevel = 72.5;
        gen11.supportsAutoStart = true;
        gen11.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen11.generatorBrand);
        System.out.println("The generatorId is : " + gen11.generatorId);
        System.out.println("The generatorPrice is : " + gen11.generatorPrice);
        System.out.println("The isAvailable is : " + gen11.isAvailable);
        System.out.println("The generatorType is : " + gen11.generatorType);
        System.out.println("The powerOutputKW is : " + gen11.powerOutputKW);
        System.out.println("The weight is : " + gen11.weight);
        System.out.println("The isPortable is : " + gen11.isPortable);
        System.out.println("The fuelType is : " + gen11.fuelType);
        System.out.println("The warrantyYears is : " + gen11.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen11.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen11.hasElectricStart);
        System.out.println("The color is : " + gen11.color);
        System.out.println("The stockQuantity is : " + gen11.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen11.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen11.isEcoFriendly);
        System.out.println("The coolingType is : " + gen11.coolingType);
        System.out.println("The rating is : " + gen11.rating);
        System.out.println("The runningTime is : " + gen11.runningTime);
        System.out.println("The isCertified is : " + gen11.isCertified);
        System.out.println("The countryOfOrigin is : " + gen11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen11.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen11.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen11.supportsAutoStart);
        System.out.println("The certificationType is : " + gen11.certificationType);


        Generator gen12 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen12.generatorBrand);
        System.out.println("The generatorId is : " + gen12.generatorId);
        System.out.println("The generatorPrice is : " + gen12.generatorPrice);
        System.out.println("The isAvailable is : " + gen12.isAvailable);
        System.out.println("The generatorType is : " + gen12.generatorType);
        System.out.println("The powerOutputKW is : " + gen12.powerOutputKW);
        System.out.println("The weight is : " + gen12.weight);
        System.out.println("The isPortable is : " + gen12.isPortable);
        System.out.println("The fuelType is : " + gen12.fuelType);
        System.out.println("The warrantyYears is : " + gen12.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen12.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen12.hasElectricStart);
        System.out.println("The color is : " + gen12.color);
        System.out.println("The stockQuantity is : " + gen12.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen12.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen12.isEcoFriendly);
        System.out.println("The coolingType is : " + gen12.coolingType);
        System.out.println("The rating is : " + gen12.rating);
        System.out.println("The runningTime is : " + gen12.runningTime);
        System.out.println("The isCertified is : " + gen12.isCertified);
        System.out.println("The countryOfOrigin is : " + gen12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen12.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen12.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen12.supportsAutoStart);
        System.out.println("The certificationType is : " + gen12.certificationType);

        gen12.generatorBrand = "PowerGen";
        gen12.generatorId = 12;
        gen12.generatorPrice = 12000.99;
        gen12.isAvailable = true;
        gen12.generatorType = "Diesel";
        gen12.powerOutputKW = 5.5;
        gen12.weight = 85.0;
        gen12.isPortable = true;
        gen12.fuelType = "Diesel";
        gen12.warrantyYears = 2;
        gen12.fuelTankCapacity = 15.0;
        gen12.hasElectricStart = true;
        gen12.color = "Yellow";
        gen12.stockQuantity = 10;
        gen12.fuelConsumption = 1.2;
        gen12.isEcoFriendly = false;
        gen12.coolingType = "Air";
        gen12.rating = 4;
        gen12.runningTime = 10.0;
        gen12.isCertified = true;
        gen12.countryOfOrigin = "India";
        gen12.manufacturingYear = 2025;
        gen12.noiseLevel = 72.5;
        gen12.supportsAutoStart = true;
        gen12.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen12.generatorBrand);
        System.out.println("The generatorId is : " + gen12.generatorId);
        System.out.println("The generatorPrice is : " + gen12.generatorPrice);
        System.out.println("The isAvailable is : " + gen12.isAvailable);
        System.out.println("The generatorType is : " + gen12.generatorType);
        System.out.println("The powerOutputKW is : " + gen12.powerOutputKW);
        System.out.println("The weight is : " + gen12.weight);
        System.out.println("The isPortable is : " + gen12.isPortable);
        System.out.println("The fuelType is : " + gen12.fuelType);
        System.out.println("The warrantyYears is : " + gen12.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen12.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen12.hasElectricStart);
        System.out.println("The color is : " + gen12.color);
        System.out.println("The stockQuantity is : " + gen12.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen12.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen12.isEcoFriendly);
        System.out.println("The coolingType is : " + gen12.coolingType);
        System.out.println("The rating is : " + gen12.rating);
        System.out.println("The runningTime is : " + gen12.runningTime);
        System.out.println("The isCertified is : " + gen12.isCertified);
        System.out.println("The countryOfOrigin is : " + gen12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen12.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen12.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen12.supportsAutoStart);
        System.out.println("The certificationType is : " + gen12.certificationType);


        Generator gen13 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen13.generatorBrand);
        System.out.println("The generatorId is : " + gen13.generatorId);
        System.out.println("The generatorPrice is : " + gen13.generatorPrice);
        System.out.println("The isAvailable is : " + gen13.isAvailable);
        System.out.println("The generatorType is : " + gen13.generatorType);
        System.out.println("The powerOutputKW is : " + gen13.powerOutputKW);
        System.out.println("The weight is : " + gen13.weight);
        System.out.println("The isPortable is : " + gen13.isPortable);
        System.out.println("The fuelType is : " + gen13.fuelType);
        System.out.println("The warrantyYears is : " + gen13.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen13.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen13.hasElectricStart);
        System.out.println("The color is : " + gen13.color);
        System.out.println("The stockQuantity is : " + gen13.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen13.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen13.isEcoFriendly);
        System.out.println("The coolingType is : " + gen13.coolingType);
        System.out.println("The rating is : " + gen13.rating);
        System.out.println("The runningTime is : " + gen13.runningTime);
        System.out.println("The isCertified is : " + gen13.isCertified);
        System.out.println("The countryOfOrigin is : " + gen13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen13.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen13.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen13.supportsAutoStart);
        System.out.println("The certificationType is : " + gen13.certificationType);

        gen13.generatorBrand = "PowerGen";
        gen13.generatorId = 13;
        gen13.generatorPrice = 13000.99;
        gen13.isAvailable = true;
        gen13.generatorType = "Diesel";
        gen13.powerOutputKW = 5.5;
        gen13.weight = 85.0;
        gen13.isPortable = true;
        gen13.fuelType = "Diesel";
        gen13.warrantyYears = 2;
        gen13.fuelTankCapacity = 15.0;
        gen13.hasElectricStart = true;
        gen13.color = "Yellow";
        gen13.stockQuantity = 10;
        gen13.fuelConsumption = 1.2;
        gen13.isEcoFriendly = false;
        gen13.coolingType = "Air";
        gen13.rating = 4;
        gen13.runningTime = 10.0;
        gen13.isCertified = true;
        gen13.countryOfOrigin = "India";
        gen13.manufacturingYear = 2025;
        gen13.noiseLevel = 72.5;
        gen13.supportsAutoStart = true;
        gen13.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen13.generatorBrand);
        System.out.println("The generatorId is : " + gen13.generatorId);
        System.out.println("The generatorPrice is : " + gen13.generatorPrice);
        System.out.println("The isAvailable is : " + gen13.isAvailable);
        System.out.println("The generatorType is : " + gen13.generatorType);
        System.out.println("The powerOutputKW is : " + gen13.powerOutputKW);
        System.out.println("The weight is : " + gen13.weight);
        System.out.println("The isPortable is : " + gen13.isPortable);
        System.out.println("The fuelType is : " + gen13.fuelType);
        System.out.println("The warrantyYears is : " + gen13.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen13.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen13.hasElectricStart);
        System.out.println("The color is : " + gen13.color);
        System.out.println("The stockQuantity is : " + gen13.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen13.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen13.isEcoFriendly);
        System.out.println("The coolingType is : " + gen13.coolingType);
        System.out.println("The rating is : " + gen13.rating);
        System.out.println("The runningTime is : " + gen13.runningTime);
        System.out.println("The isCertified is : " + gen13.isCertified);
        System.out.println("The countryOfOrigin is : " + gen13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen13.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen13.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen13.supportsAutoStart);
        System.out.println("The certificationType is : " + gen13.certificationType);


        Generator gen14 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen14.generatorBrand);
        System.out.println("The generatorId is : " + gen14.generatorId);
        System.out.println("The generatorPrice is : " + gen14.generatorPrice);
        System.out.println("The isAvailable is : " + gen14.isAvailable);
        System.out.println("The generatorType is : " + gen14.generatorType);
        System.out.println("The powerOutputKW is : " + gen14.powerOutputKW);
        System.out.println("The weight is : " + gen14.weight);
        System.out.println("The isPortable is : " + gen14.isPortable);
        System.out.println("The fuelType is : " + gen14.fuelType);
        System.out.println("The warrantyYears is : " + gen14.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen14.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen14.hasElectricStart);
        System.out.println("The color is : " + gen14.color);
        System.out.println("The stockQuantity is : " + gen14.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen14.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen14.isEcoFriendly);
        System.out.println("The coolingType is : " + gen14.coolingType);
        System.out.println("The rating is : " + gen14.rating);
        System.out.println("The runningTime is : " + gen14.runningTime);
        System.out.println("The isCertified is : " + gen14.isCertified);
        System.out.println("The countryOfOrigin is : " + gen14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen14.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen14.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen14.supportsAutoStart);
        System.out.println("The certificationType is : " + gen14.certificationType);

        gen14.generatorBrand = "PowerGen";
        gen14.generatorId = 14;
        gen14.generatorPrice = 14000.99;
        gen14.isAvailable = true;
        gen14.generatorType = "Diesel";
        gen14.powerOutputKW = 5.5;
        gen14.weight = 85.0;
        gen14.isPortable = true;
        gen14.fuelType = "Diesel";
        gen14.warrantyYears = 2;
        gen14.fuelTankCapacity = 15.0;
        gen14.hasElectricStart = true;
        gen14.color = "Yellow";
        gen14.stockQuantity = 10;
        gen14.fuelConsumption = 1.2;
        gen14.isEcoFriendly = false;
        gen14.coolingType = "Air";
        gen14.rating = 4;
        gen14.runningTime = 10.0;
        gen14.isCertified = true;
        gen14.countryOfOrigin = "India";
        gen14.manufacturingYear = 2025;
        gen14.noiseLevel = 72.5;
        gen14.supportsAutoStart = true;
        gen14.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen14.generatorBrand);
        System.out.println("The generatorId is : " + gen14.generatorId);
        System.out.println("The generatorPrice is : " + gen14.generatorPrice);
        System.out.println("The isAvailable is : " + gen14.isAvailable);
        System.out.println("The generatorType is : " + gen14.generatorType);
        System.out.println("The powerOutputKW is : " + gen14.powerOutputKW);
        System.out.println("The weight is : " + gen14.weight);
        System.out.println("The isPortable is : " + gen14.isPortable);
        System.out.println("The fuelType is : " + gen14.fuelType);
        System.out.println("The warrantyYears is : " + gen14.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen14.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen14.hasElectricStart);
        System.out.println("The color is : " + gen14.color);
        System.out.println("The stockQuantity is : " + gen14.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen14.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen14.isEcoFriendly);
        System.out.println("The coolingType is : " + gen14.coolingType);
        System.out.println("The rating is : " + gen14.rating);
        System.out.println("The runningTime is : " + gen14.runningTime);
        System.out.println("The isCertified is : " + gen14.isCertified);
        System.out.println("The countryOfOrigin is : " + gen14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen14.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen14.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen14.supportsAutoStart);
        System.out.println("The certificationType is : " + gen14.certificationType);


        Generator gen15 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen15.generatorBrand);
        System.out.println("The generatorId is : " + gen15.generatorId);
        System.out.println("The generatorPrice is : " + gen15.generatorPrice);
        System.out.println("The isAvailable is : " + gen15.isAvailable);
        System.out.println("The generatorType is : " + gen15.generatorType);
        System.out.println("The powerOutputKW is : " + gen15.powerOutputKW);
        System.out.println("The weight is : " + gen15.weight);
        System.out.println("The isPortable is : " + gen15.isPortable);
        System.out.println("The fuelType is : " + gen15.fuelType);
        System.out.println("The warrantyYears is : " + gen15.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen15.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen15.hasElectricStart);
        System.out.println("The color is : " + gen15.color);
        System.out.println("The stockQuantity is : " + gen15.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen15.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen15.isEcoFriendly);
        System.out.println("The coolingType is : " + gen15.coolingType);
        System.out.println("The rating is : " + gen15.rating);
        System.out.println("The runningTime is : " + gen15.runningTime);
        System.out.println("The isCertified is : " + gen15.isCertified);
        System.out.println("The countryOfOrigin is : " + gen15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen15.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen15.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen15.supportsAutoStart);
        System.out.println("The certificationType is : " + gen15.certificationType);

        gen15.generatorBrand = "PowerGen";
        gen15.generatorId = 15;
        gen15.generatorPrice = 15000.99;
        gen15.isAvailable = true;
        gen15.generatorType = "Diesel";
        gen15.powerOutputKW = 5.5;
        gen15.weight = 85.0;
        gen15.isPortable = true;
        gen15.fuelType = "Diesel";
        gen15.warrantyYears = 2;
        gen15.fuelTankCapacity = 15.0;
        gen15.hasElectricStart = true;
        gen15.color = "Yellow";
        gen15.stockQuantity = 10;
        gen15.fuelConsumption = 1.2;
        gen15.isEcoFriendly = false;
        gen15.coolingType = "Air";
        gen15.rating = 4;
        gen15.runningTime = 10.0;
        gen15.isCertified = true;
        gen15.countryOfOrigin = "India";
        gen15.manufacturingYear = 2025;
        gen15.noiseLevel = 72.5;
        gen15.supportsAutoStart = true;
        gen15.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen15.generatorBrand);
        System.out.println("The generatorId is : " + gen15.generatorId);
        System.out.println("The generatorPrice is : " + gen15.generatorPrice);
        System.out.println("The isAvailable is : " + gen15.isAvailable);
        System.out.println("The generatorType is : " + gen15.generatorType);
        System.out.println("The powerOutputKW is : " + gen15.powerOutputKW);
        System.out.println("The weight is : " + gen15.weight);
        System.out.println("The isPortable is : " + gen15.isPortable);
        System.out.println("The fuelType is : " + gen15.fuelType);
        System.out.println("The warrantyYears is : " + gen15.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen15.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen15.hasElectricStart);
        System.out.println("The color is : " + gen15.color);
        System.out.println("The stockQuantity is : " + gen15.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen15.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen15.isEcoFriendly);
        System.out.println("The coolingType is : " + gen15.coolingType);
        System.out.println("The rating is : " + gen15.rating);
        System.out.println("The runningTime is : " + gen15.runningTime);
        System.out.println("The isCertified is : " + gen15.isCertified);
        System.out.println("The countryOfOrigin is : " + gen15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen15.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen15.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen15.supportsAutoStart);
        System.out.println("The certificationType is : " + gen15.certificationType);


        Generator gen16 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen16.generatorBrand);
        System.out.println("The generatorId is : " + gen16.generatorId);
        System.out.println("The generatorPrice is : " + gen16.generatorPrice);
        System.out.println("The isAvailable is : " + gen16.isAvailable);
        System.out.println("The generatorType is : " + gen16.generatorType);
        System.out.println("The powerOutputKW is : " + gen16.powerOutputKW);
        System.out.println("The weight is : " + gen16.weight);
        System.out.println("The isPortable is : " + gen16.isPortable);
        System.out.println("The fuelType is : " + gen16.fuelType);
        System.out.println("The warrantyYears is : " + gen16.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen16.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen16.hasElectricStart);
        System.out.println("The color is : " + gen16.color);
        System.out.println("The stockQuantity is : " + gen16.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen16.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen16.isEcoFriendly);
        System.out.println("The coolingType is : " + gen16.coolingType);
        System.out.println("The rating is : " + gen16.rating);
        System.out.println("The runningTime is : " + gen16.runningTime);
        System.out.println("The isCertified is : " + gen16.isCertified);
        System.out.println("The countryOfOrigin is : " + gen16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen16.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen16.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen16.supportsAutoStart);
        System.out.println("The certificationType is : " + gen16.certificationType);

        gen16.generatorBrand = "PowerGen";
        gen16.generatorId = 16;
        gen16.generatorPrice = 16000.99;
        gen16.isAvailable = true;
        gen16.generatorType = "Diesel";
        gen16.powerOutputKW = 5.5;
        gen16.weight = 85.0;
        gen16.isPortable = true;
        gen16.fuelType = "Diesel";
        gen16.warrantyYears = 2;
        gen16.fuelTankCapacity = 15.0;
        gen16.hasElectricStart = true;
        gen16.color = "Yellow";
        gen16.stockQuantity = 10;
        gen16.fuelConsumption = 1.2;
        gen16.isEcoFriendly = false;
        gen16.coolingType = "Air";
        gen16.rating = 4;
        gen16.runningTime = 10.0;
        gen16.isCertified = true;
        gen16.countryOfOrigin = "India";
        gen16.manufacturingYear = 2025;
        gen16.noiseLevel = 72.5;
        gen16.supportsAutoStart = true;
        gen16.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen16.generatorBrand);
        System.out.println("The generatorId is : " + gen16.generatorId);
        System.out.println("The generatorPrice is : " + gen16.generatorPrice);
        System.out.println("The isAvailable is : " + gen16.isAvailable);
        System.out.println("The generatorType is : " + gen16.generatorType);
        System.out.println("The powerOutputKW is : " + gen16.powerOutputKW);
        System.out.println("The weight is : " + gen16.weight);
        System.out.println("The isPortable is : " + gen16.isPortable);
        System.out.println("The fuelType is : " + gen16.fuelType);
        System.out.println("The warrantyYears is : " + gen16.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen16.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen16.hasElectricStart);
        System.out.println("The color is : " + gen16.color);
        System.out.println("The stockQuantity is : " + gen16.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen16.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen16.isEcoFriendly);
        System.out.println("The coolingType is : " + gen16.coolingType);
        System.out.println("The rating is : " + gen16.rating);
        System.out.println("The runningTime is : " + gen16.runningTime);
        System.out.println("The isCertified is : " + gen16.isCertified);
        System.out.println("The countryOfOrigin is : " + gen16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen16.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen16.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen16.supportsAutoStart);
        System.out.println("The certificationType is : " + gen16.certificationType);


        Generator gen17 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen17.generatorBrand);
        System.out.println("The generatorId is : " + gen17.generatorId);
        System.out.println("The generatorPrice is : " + gen17.generatorPrice);
        System.out.println("The isAvailable is : " + gen17.isAvailable);
        System.out.println("The generatorType is : " + gen17.generatorType);
        System.out.println("The powerOutputKW is : " + gen17.powerOutputKW);
        System.out.println("The weight is : " + gen17.weight);
        System.out.println("The isPortable is : " + gen17.isPortable);
        System.out.println("The fuelType is : " + gen17.fuelType);
        System.out.println("The warrantyYears is : " + gen17.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen17.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen17.hasElectricStart);
        System.out.println("The color is : " + gen17.color);
        System.out.println("The stockQuantity is : " + gen17.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen17.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen17.isEcoFriendly);
        System.out.println("The coolingType is : " + gen17.coolingType);
        System.out.println("The rating is : " + gen17.rating);
        System.out.println("The runningTime is : " + gen17.runningTime);
        System.out.println("The isCertified is : " + gen17.isCertified);
        System.out.println("The countryOfOrigin is : " + gen17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen17.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen17.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen17.supportsAutoStart);
        System.out.println("The certificationType is : " + gen17.certificationType);

        gen17.generatorBrand = "PowerGen";
        gen17.generatorId = 17;
        gen17.generatorPrice = 17000.99;
        gen17.isAvailable = true;
        gen17.generatorType = "Diesel";
        gen17.powerOutputKW = 5.5;
        gen17.weight = 85.0;
        gen17.isPortable = true;
        gen17.fuelType = "Diesel";
        gen17.warrantyYears = 2;
        gen17.fuelTankCapacity = 15.0;
        gen17.hasElectricStart = true;
        gen17.color = "Yellow";
        gen17.stockQuantity = 10;
        gen17.fuelConsumption = 1.2;
        gen17.isEcoFriendly = false;
        gen17.coolingType = "Air";
        gen17.rating = 4;
        gen17.runningTime = 10.0;
        gen17.isCertified = true;
        gen17.countryOfOrigin = "India";
        gen17.manufacturingYear = 2025;
        gen17.noiseLevel = 72.5;
        gen17.supportsAutoStart = true;
        gen17.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen17.generatorBrand);
        System.out.println("The generatorId is : " + gen17.generatorId);
        System.out.println("The generatorPrice is : " + gen17.generatorPrice);
        System.out.println("The isAvailable is : " + gen17.isAvailable);
        System.out.println("The generatorType is : " + gen17.generatorType);
        System.out.println("The powerOutputKW is : " + gen17.powerOutputKW);
        System.out.println("The weight is : " + gen17.weight);
        System.out.println("The isPortable is : " + gen17.isPortable);
        System.out.println("The fuelType is : " + gen17.fuelType);
        System.out.println("The warrantyYears is : " + gen17.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen17.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen17.hasElectricStart);
        System.out.println("The color is : " + gen17.color);
        System.out.println("The stockQuantity is : " + gen17.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen17.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen17.isEcoFriendly);
        System.out.println("The coolingType is : " + gen17.coolingType);
        System.out.println("The rating is : " + gen17.rating);
        System.out.println("The runningTime is : " + gen17.runningTime);
        System.out.println("The isCertified is : " + gen17.isCertified);
        System.out.println("The countryOfOrigin is : " + gen17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen17.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen17.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen17.supportsAutoStart);
        System.out.println("The certificationType is : " + gen17.certificationType);


        Generator gen18 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen18.generatorBrand);
        System.out.println("The generatorId is : " + gen18.generatorId);
        System.out.println("The generatorPrice is : " + gen18.generatorPrice);
        System.out.println("The isAvailable is : " + gen18.isAvailable);
        System.out.println("The generatorType is : " + gen18.generatorType);
        System.out.println("The powerOutputKW is : " + gen18.powerOutputKW);
        System.out.println("The weight is : " + gen18.weight);
        System.out.println("The isPortable is : " + gen18.isPortable);
        System.out.println("The fuelType is : " + gen18.fuelType);
        System.out.println("The warrantyYears is : " + gen18.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen18.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen18.hasElectricStart);
        System.out.println("The color is : " + gen18.color);
        System.out.println("The stockQuantity is : " + gen18.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen18.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen18.isEcoFriendly);
        System.out.println("The coolingType is : " + gen18.coolingType);
        System.out.println("The rating is : " + gen18.rating);
        System.out.println("The runningTime is : " + gen18.runningTime);
        System.out.println("The isCertified is : " + gen18.isCertified);
        System.out.println("The countryOfOrigin is : " + gen18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen18.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen18.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen18.supportsAutoStart);
        System.out.println("The certificationType is : " + gen18.certificationType);

        gen18.generatorBrand = "PowerGen";
        gen18.generatorId = 18;
        gen18.generatorPrice = 18000.99;
        gen18.isAvailable = true;
        gen18.generatorType = "Diesel";
        gen18.powerOutputKW = 5.5;
        gen18.weight = 85.0;
        gen18.isPortable = true;
        gen18.fuelType = "Diesel";
        gen18.warrantyYears = 2;
        gen18.fuelTankCapacity = 15.0;
        gen18.hasElectricStart = true;
        gen18.color = "Yellow";
        gen18.stockQuantity = 10;
        gen18.fuelConsumption = 1.2;
        gen18.isEcoFriendly = false;
        gen18.coolingType = "Air";
        gen18.rating = 4;
        gen18.runningTime = 10.0;
        gen18.isCertified = true;
        gen18.countryOfOrigin = "India";
        gen18.manufacturingYear = 2025;
        gen18.noiseLevel = 72.5;
        gen18.supportsAutoStart = true;
        gen18.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen18.generatorBrand);
        System.out.println("The generatorId is : " + gen18.generatorId);
        System.out.println("The generatorPrice is : " + gen18.generatorPrice);
        System.out.println("The isAvailable is : " + gen18.isAvailable);
        System.out.println("The generatorType is : " + gen18.generatorType);
        System.out.println("The powerOutputKW is : " + gen18.powerOutputKW);
        System.out.println("The weight is : " + gen18.weight);
        System.out.println("The isPortable is : " + gen18.isPortable);
        System.out.println("The fuelType is : " + gen18.fuelType);
        System.out.println("The warrantyYears is : " + gen18.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen18.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen18.hasElectricStart);
        System.out.println("The color is : " + gen18.color);
        System.out.println("The stockQuantity is : " + gen18.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen18.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen18.isEcoFriendly);
        System.out.println("The coolingType is : " + gen18.coolingType);
        System.out.println("The rating is : " + gen18.rating);
        System.out.println("The runningTime is : " + gen18.runningTime);
        System.out.println("The isCertified is : " + gen18.isCertified);
        System.out.println("The countryOfOrigin is : " + gen18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen18.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen18.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen18.supportsAutoStart);
        System.out.println("The certificationType is : " + gen18.certificationType);


        Generator gen19 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen19.generatorBrand);
        System.out.println("The generatorId is : " + gen19.generatorId);
        System.out.println("The generatorPrice is : " + gen19.generatorPrice);
        System.out.println("The isAvailable is : " + gen19.isAvailable);
        System.out.println("The generatorType is : " + gen19.generatorType);
        System.out.println("The powerOutputKW is : " + gen19.powerOutputKW);
        System.out.println("The weight is : " + gen19.weight);
        System.out.println("The isPortable is : " + gen19.isPortable);
        System.out.println("The fuelType is : " + gen19.fuelType);
        System.out.println("The warrantyYears is : " + gen19.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen19.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen19.hasElectricStart);
        System.out.println("The color is : " + gen19.color);
        System.out.println("The stockQuantity is : " + gen19.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen19.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen19.isEcoFriendly);
        System.out.println("The coolingType is : " + gen19.coolingType);
        System.out.println("The rating is : " + gen19.rating);
        System.out.println("The runningTime is : " + gen19.runningTime);
        System.out.println("The isCertified is : " + gen19.isCertified);
        System.out.println("The countryOfOrigin is : " + gen19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen19.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen19.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen19.supportsAutoStart);
        System.out.println("The certificationType is : " + gen19.certificationType);

        gen19.generatorBrand = "PowerGen";
        gen19.generatorId = 19;
        gen19.generatorPrice = 19000.99;
        gen19.isAvailable = true;
        gen19.generatorType = "Diesel";
        gen19.powerOutputKW = 5.5;
        gen19.weight = 85.0;
        gen19.isPortable = true;
        gen19.fuelType = "Diesel";
        gen19.warrantyYears = 2;
        gen19.fuelTankCapacity = 15.0;
        gen19.hasElectricStart = true;
        gen19.color = "Yellow";
        gen19.stockQuantity = 10;
        gen19.fuelConsumption = 1.2;
        gen19.isEcoFriendly = false;
        gen19.coolingType = "Air";
        gen19.rating = 4;
        gen19.runningTime = 10.0;
        gen19.isCertified = true;
        gen19.countryOfOrigin = "India";
        gen19.manufacturingYear = 2025;
        gen19.noiseLevel = 72.5;
        gen19.supportsAutoStart = true;
        gen19.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen19.generatorBrand);
        System.out.println("The generatorId is : " + gen19.generatorId);
        System.out.println("The generatorPrice is : " + gen19.generatorPrice);
        System.out.println("The isAvailable is : " + gen19.isAvailable);
        System.out.println("The generatorType is : " + gen19.generatorType);
        System.out.println("The powerOutputKW is : " + gen19.powerOutputKW);
        System.out.println("The weight is : " + gen19.weight);
        System.out.println("The isPortable is : " + gen19.isPortable);
        System.out.println("The fuelType is : " + gen19.fuelType);
        System.out.println("The warrantyYears is : " + gen19.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen19.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen19.hasElectricStart);
        System.out.println("The color is : " + gen19.color);
        System.out.println("The stockQuantity is : " + gen19.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen19.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen19.isEcoFriendly);
        System.out.println("The coolingType is : " + gen19.coolingType);
        System.out.println("The rating is : " + gen19.rating);
        System.out.println("The runningTime is : " + gen19.runningTime);
        System.out.println("The isCertified is : " + gen19.isCertified);
        System.out.println("The countryOfOrigin is : " + gen19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen19.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen19.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen19.supportsAutoStart);
        System.out.println("The certificationType is : " + gen19.certificationType);


        Generator gen20 = new Generator();

        System.out.println("Before initialization");

        System.out.println("The generatorBrand is : " + gen20.generatorBrand);
        System.out.println("The generatorId is : " + gen20.generatorId);
        System.out.println("The generatorPrice is : " + gen20.generatorPrice);
        System.out.println("The isAvailable is : " + gen20.isAvailable);
        System.out.println("The generatorType is : " + gen20.generatorType);
        System.out.println("The powerOutputKW is : " + gen20.powerOutputKW);
        System.out.println("The weight is : " + gen20.weight);
        System.out.println("The isPortable is : " + gen20.isPortable);
        System.out.println("The fuelType is : " + gen20.fuelType);
        System.out.println("The warrantyYears is : " + gen20.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen20.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen20.hasElectricStart);
        System.out.println("The color is : " + gen20.color);
        System.out.println("The stockQuantity is : " + gen20.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen20.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen20.isEcoFriendly);
        System.out.println("The coolingType is : " + gen20.coolingType);
        System.out.println("The rating is : " + gen20.rating);
        System.out.println("The runningTime is : " + gen20.runningTime);
        System.out.println("The isCertified is : " + gen20.isCertified);
        System.out.println("The countryOfOrigin is : " + gen20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen20.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen20.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen20.supportsAutoStart);
        System.out.println("The certificationType is : " + gen20.certificationType);

        gen20.generatorBrand = "PowerGen";
        gen20.generatorId = 20;
        gen20.generatorPrice = 20000.99;
        gen20.isAvailable = true;
        gen20.generatorType = "Diesel";
        gen20.powerOutputKW = 5.5;
        gen20.weight = 85.0;
        gen20.isPortable = true;
        gen20.fuelType = "Diesel";
        gen20.warrantyYears = 2;
        gen20.fuelTankCapacity = 15.0;
        gen20.hasElectricStart = true;
        gen20.color = "Yellow";
        gen20.stockQuantity = 10;
        gen20.fuelConsumption = 1.2;
        gen20.isEcoFriendly = false;
        gen20.coolingType = "Air";
        gen20.rating = 4;
        gen20.runningTime = 10.0;
        gen20.isCertified = true;
        gen20.countryOfOrigin = "India";
        gen20.manufacturingYear = 2025;
        gen20.noiseLevel = 72.5;
        gen20.supportsAutoStart = true;
        gen20.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The generatorBrand is : " + gen20.generatorBrand);
        System.out.println("The generatorId is : " + gen20.generatorId);
        System.out.println("The generatorPrice is : " + gen20.generatorPrice);
        System.out.println("The isAvailable is : " + gen20.isAvailable);
        System.out.println("The generatorType is : " + gen20.generatorType);
        System.out.println("The powerOutputKW is : " + gen20.powerOutputKW);
        System.out.println("The weight is : " + gen20.weight);
        System.out.println("The isPortable is : " + gen20.isPortable);
        System.out.println("The fuelType is : " + gen20.fuelType);
        System.out.println("The warrantyYears is : " + gen20.warrantyYears);
        System.out.println("The fuelTankCapacity is : " + gen20.fuelTankCapacity);
        System.out.println("The hasElectricStart is : " + gen20.hasElectricStart);
        System.out.println("The color is : " + gen20.color);
        System.out.println("The stockQuantity is : " + gen20.stockQuantity);
        System.out.println("The fuelConsumption is : " + gen20.fuelConsumption);
        System.out.println("The isEcoFriendly is : " + gen20.isEcoFriendly);
        System.out.println("The coolingType is : " + gen20.coolingType);
        System.out.println("The rating is : " + gen20.rating);
        System.out.println("The runningTime is : " + gen20.runningTime);
        System.out.println("The isCertified is : " + gen20.isCertified);
        System.out.println("The countryOfOrigin is : " + gen20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + gen20.manufacturingYear);
        System.out.println("The noiseLevel is : " + gen20.noiseLevel);
        System.out.println("The supportsAutoStart is : " + gen20.supportsAutoStart);
        System.out.println("The certificationType is : " + gen20.certificationType);


    }
}
